<br />
<h2>
    <?=$cmodule->name; ?>
    <?php if (substr($cmodule->template_codename, 0, 4) != "del_") { ?>
    - <?=$cmodule->template_codename; ?>
    <?php } ?>
    <?php if ($cmodule->is_teacher) { ?>
	<a href="index.php?p=InstancesMenu&amp;activity=<?=$cmodule->id; ?>">
	    <?=$Dictionnary["Edit"]; ?>
	</a>
    <?php } ?>
</h2>
<br />
<?php if ($my_module) { ?>
    <form method="post" action="index.php?<?=unrollget(); ?>">
	<?php if ($cmodule->registered == false) { ?>
	    <input type="hidden" name="action" value="subscribe" />
	    <input type="hidden" name="module" value="<?=$cmodule->id; ?>" />
	    <input type="submit" value="<?=$Dictionnary["Subscribe"]; ?>" />
	<?php } else { ?>
	    <input type="hidden" name="action" value="unsubscribe" />
	    <input type="hidden" name="module" value="<?=$cmodule->id; ?>" />
	    <input type="submit" value="<?=$Dictionnary["Unsubscribe"]; ?>" />
	<?php } // Il faut déplacer ca apres la boucle une fois l'inscription fonctionnelle ?>
    </form>
<?php } ?>


<div class="panel" style="height: 150px; text-align: center; padding: 10px 10px 10px 10px; width: calc(90% - 20px);">
    <table>
	<tr>
	    <td style="width: 280px;">
		<?php if ($display_students == false) { ?>
		<a href="index.php?p=ModulesMenu&amp;a=<?=$current_module; ?>&amp;student=1" class="dynbutton">
		    <div class="aligned_box box250x25 bigtext lightbackground" style="height: 20px;">
			<?=$Dictionnary["SeeRegisteredStudents"]; ?>
		    </div></a>
		<?php } else { ?>
		<a href="index.php?p=ModulesMenu&amp;a=<?=$current_module; ?>" class="dynbutton">
		    <div class="aligned_box box250x25 bigtext lightbackground" style="height: 20px;">
			<?=$Dictionnary["SeeActivityList"]; ?>
		    </div></a>
		<?php } ?>
		<div
		    class="aligned_box box250x25 bigtext lightbackground"
		    style="margin-top: 5px; height: 85px;"
		>
		    <table style="font-size: x-small; height: 100%;">
			<?php if (count($cmodule->teacher)) { ?>
			<tr>
			    <td><b><?=$Dictionnary["Teacher"]; ?></b>:</td>
			    <td>
				<?php foreach ($cmodule->teacher as $teacher) { ?>
				<?php if (substr($teacher["codename"], 0, 1) == "#") { ?>
				<a href="index.php?p=LaboratoriesMenu&amp;a=<?=$teacher["id_laboratory"]; ?>">
				    <?=$teacher["codename"]; ?></a>
				<?php } else { ?>
				<a href="index.php?p=ProfileMenu&amp;a=<?=$teacher["id_user"]; ?>">
				    <?=$teacher["codename"]; ?></a>
				<?php } ?>
				<?php } ?>
			    </td>
			</tr>
			<?php } ?>
			<?php if ($cmodule->credit != 0) { ?>
			<tr>
			    <td><b><?=$Dictionnary["Credit"]; ?></b>:</td>
			    <td><?=$cmodule->credit; ?></td>
			</tr>
			<?php } ?>

			<?php if ($cmodule->emergence_date) { ?>
			<tr>
			    <td><b><?=$Dictionnary["EmergenceDate"]; ?></b>:</td>
			    <td><?=human_date($cmodule->emergence_date); ?></td>
			</tr>
			<?php } ?>

			<?php if ($cmodule->done_date) { ?>
			<tr>
			    <td><b><?=$Dictionnary["DoneDate"]; ?></b>:</td>
			    <td><?=human_date($cmodule->done_date); ?></td>
			</tr>
			<?php } ?>

			<?php if ($cmodule->registration_date) { ?>
			<tr>
			    <td><b><?=$Dictionnary["RegistrationDate"]; ?></b>:</td>
			    <td><?=human_date($cmodule->registration_date); ?></td>
			</tr>
			<?php } ?>

			<?php if ($cmodule->close_date) { ?>
			<tr>
			    <td><b><?=$Dictionnary["CloseDate"]; ?></b>:</td>
			    <td><?=human_date($cmodule->close_date); ?></td>
			</tr>
			<?php } ?>
		    </table>
		</div>
	    </td>
	    <td>
		<div
		    class="aligned_box box250x25 bigtext lightbackground tinyscroll"
		    style="margin-top: 5px; height: 125px; overflow: auto; width: calc(100% - 20px);"
		>
		    <?php
		    $sorted_medal = sort_by_medal_grade($cmodule->medal);
		    foreach ($sorted_medal as $medal)
		    {
		      if ($medal["icon"] != "" && $medal["bonus"] == 0)
		      {
		        $medal["module_medal"] = true;
		        print_medal($medal, $cmodule);
		      }
		    }

	            foreach ($sorted_medal as $medal)
		    {
		      if ($medal["icon"] == "" && $medal["bonus"] == 0)
		      {
		        $medal["module_medal"] = true;
		        print_medal($medal, $cmodule);
		      }
		    }
		    ?>
		</div>
	    </td>
	</tr>
    </table>
</div>
