
<?php foreach ($medals as $medal) { ?>
    <table class="medal_box" <?php if ($medal["hidden"] != NULL) { ?> style="background-color: gray;" <?php } ?>>
	<tr><td style="width: 100px;">
	    <img
		loading="lazy"
		src="<?=$medal["icon"]; ?>"
		class="medal_box_picture"
		onclick="document.location='index.php?p=MedalsMenu&amp;a=<?=$medal["id"]; ?>';"
	    />
	    <!--div
		class="medal_box_picture"
		onclick="document.location='index.php?p=MedalsMenu&amp;a=<?=$medal["id"]; ?>';"
		style="
		       background-image: url('<?=$medal["icon"]; ?>');
		       <?php if ($medal["band"] != NULL) { ?>
		       border-radius: 50px;
		       <?php } ?>
		       "
	    ></div-->
	</td><td style="padding-left: 10px; width: 270px;">
	    <div style="width: 100%; height: 100px; overflow: auto;">
		<h4><?=$medal["name"]; ?><?=is_teacher() ? " (".$medal["codename"].")" : ""; ?></h4>
		<h5><?=$Dictionnary["Tags"]; ?>: <?=$medal["tags"]; ?></h5>
		<p style="font-size: small;">
		    <?=$Dictionnary[["PositiveMedal", "NegativeMedal", "CriticalNegativeMedal"][$medal["type"]]]; ?><br />
		    <?=$medal["description"]; ?>
		</p>
	    </div>
	</td>
	<?php if (is_teacher()) { ?>
	    <script>
	     <?php
	     $mcli = explode(" ", $medal["command"]);
	     array_shift($mcli); // ./genicon
	     $medal["shape"] = $mcli[0] == "pins" ? "0" : "1";
	     array_shift($mcli); // [sband, band, pins]
	     array_shift($mcli); // medal_name
	     $medal["specificator"] = "";
	     $medal["picture"] = "";
	     for ($imcli = 0; $imcli < count($mcli); ++$imcli)
	     {
		 if ($mcli[$imcli] == "-p")
		 {
		     $imcli += 1;
		     $medal["picture"] = $mcli[$imcli];
		     $medal["picture"] = str_replace("dres/medals/.ressources/", "", $medal["picture"]);
		 }
		 else if ($mcli[$imcli] == "-s")
		 {
		     $imcli += 1;
		     $medal["specificator"] = $mcli[$imcli];
		 }
		 else if ($mcli[$imcli] == "-c")
		 {
		     $imcli += 1;
		     if (!strstr($mcli[$imcli], ".default_style.dab"))
		     {
			 $medal["configuration"] = $mcli[$imcli];
			 $path = "dres/medals/.ressources/";
			 if (strncmp($path, $medal["configuration"], strlen($path))
			     == 0)
			     $medal["configuration"] =
				 substr($medal["configuration"], strlen($path));
		     }
		     else
			 $medal["configuration"] = "";
		 }
	     }
	     foreach ([
		 "command",
		 "name",
		 "description",
		 "deleted",
		 "band",
		 "icon"
	     ] as $cc)
	         unset($medal[$cc]);
	     ?>
	     var _<?=$medal["codename"]; ?> = {
		 <?php foreach ($medal as $kmed => $med) { ?>
		     <?=$kmed; ?>: "<?=str_replace("\n", "\\n", addslashes($med)); ?>",
		 <?php } ?>
		 edit: true
	     };
	    </script>
	    <?php $js = "silent_submit(this, 'medallist');"; ?>
	    <td style="width: 20px;">
		<form method="delete" action="/api/medal/<?=$medal["id"]; ?>" onsubmit="confirm() && <?=$js; ?>;">
		    <input type="button" value="&#10007;" onclick="confirm() && <?=$js; ?>;" style="color: red;" />
		</form>
		<form method="put" action="/api/medal/<?=$medal["id"]; ?>" onsubmit="load_form(document.getElementById('medal_formular'), _<?=$medal["codename"]; ?>);">
		    <input type="button" value="E" onclick="load_form(document.getElementById('medal_formular'), _<?=$medal["codename"]; ?>);" style="color: #00FFFF;" />
		</form>
		<input type="button"
		       <?php if (isset($srvmeds[$medal["codename"]])) { ?>
		       style="background-color: green;"
		       <?php } else { ?>
		       style="background-color: red;"
		       <?php } ?>
		/>
	    </td>
	<?php } ?>
	</tr>
    </table>
<?php } ?>

