<h3><?=$fetch["name"]; ?></h3>
<a href="index.php?p=<?=$Position; ?>">
    &larr;
</a>
<div style="text-align: center;">
    <?php if (@strlen($fetch["icon"])) { ?>
    <img src="<?=$fetch["icon"]; ?>" />
    <?php } else { ?>
    <img src="genicon.php?function=<?=$fetch["codename"]; ?>" />
    <?php } ?>
    <br />
    <br />
    <br />
</div>
<div>
    <?=$Dictionnary["ImpliedMedals"]; ?><br />
    <?php foreach ($fetch["implied"] as $imp) { ?>
    <?php $URL = "index.php?p=".$Position."&amp;a=".$imp["id"]; ?>
    <a href="<?=$URL; ?>">
	<div style="text-align: center;">
	    <?php if ($imp["icon"] != "") { ?>
	    <img src="<?=$imp["icon"]; ?>" width="50" height="50" />
	    <?php } else { ?>
	    <img src="genicon.php?function=<?=$imp["codename"]; ?>" width="150" height="25" />
	    <?php } ?>
	    <br /><?=$imp["codename"]; ?>
	    <br />x<?=$imp["nbr"]; ?>
	</div>
    </a>
    <?php } ?>
    <br />
</div>
<table class="content_table">
    <!-- EN TETE ---------------------------------------------->
    <tr>
	<th class="id_column">#</th>
	<th class="codename_column"><?=$Dictionnary["CodeName"]; ?></th>
	<th class="name_column"><?=$Dictionnary["Name"]; ?></th>
	<th class="description_column"><?=$Dictionnary["Description"]; ?></th>
	<?php if ($User != NULL && $User["authority"] >= ADMINISTRATOR) { ?>
	    <th class="edit_column"><img src="./res/cog.png" /></th>
	<?php } ?>
    </tr>
    <!-- CORPS ------------------------------------------------>
    <?php
    $cnt = 0;
    foreach ($fetch["activity"] as $i => $content)
    {
    $URL = "index.php?p=ActivityMenu&amp;a=".$content["id"];
    ?>
	<tr class="content_<?=$cnt++ % 2 ? "even" : "odd"; ?>">
	    <td <?=clickable($URL); ?>><?=$content["id"]; ?></td>
	    <td <?=clickable($URL); ?>><?=$content["codename"]; ?></td>
	    <td <?=clickable($URL); ?>><?=$content["name"]; ?></td>
	    <td <?=clickable($URL); ?>><?=$content["description"]; ?></td>
	    <?php if ($User != NULL && $User["authority"] >= ADMINISTRATOR) { ?>
	    <?php require ("edit_activity.phtml"); ?>
	    <?php } ?>
	</tr>
	<?php
	}
	?>
</table>

<table class="content_table">
    <!-- EN TETE ---------------------------------------------->
    <tr>
	<th class="id_column">#</th>
	<th class="codename_column"><?=$Dictionnary["CodeName"]; ?></th>
	<th class="name_column">$</th>
    </tr>
    <!-- CORPS ------------------------------------------------>
    <?php $cnt = 0; ?>
    <?php foreach ($fetch["user"] as $i => $content) { ?>
    <?php $URL = "index.php?p=ProfileMenu&amp;a=".$content["id"]; ?>
    <tr class="content_<?=$cnt++ % 2 ? "even" : "odd"; ?>">
	<td <?=clickable($URL); ?>><?=$content["id"]; ?></td>
	<td <?=clickable($URL); ?>><?=$content["codename"]; ?></td>
	<td <?=clickable($URL); ?>><?=$content["got"]; ?></td>
    </tr>
    <?php } ?>
</table>

<?php
if ($User != NULL && $User["authority"] >= ADMINISTRATOR)
require ("add_activity.phtml");
?>

<br />
<br />
<br />
