<html>
    <head>
	<title>Infosphere's installation</title>
	<style>
	 form
	 {
	     width: 100%;
	     text-align: center;
	 }
	 input
	 {
	     width: 33%;
	     height: 50px;
	     font-size: 33px;
	 }
	 .sexy
	 {
	     width: 66%;
	     height: 100px;
	     font-size: 66px;
	 }
	</style>
    </head>
    <body>
	<form method="post" action="install.php">
	    <h1>Infosphere's installation</h1>
            <p><?=$ErrorMsg != "" ? $Dictionnary[$ErrorMsg] : ""; ?></p>
	    <h2>Database</h2>
	    <input type="text" name="host" placeholder="host" value="<?=try_get($_POST, "host"); ?>" /><br />
	    <input type="text" name="login" placeholder="login" value="<?=try_get($_POST, "login"); ?>" /><br />
	    <input type="password" name="password" placeholder="password" value="<?=try_get($_POST, "password"); ?>" /><br />
	    <input type="text" name="database" placeholder="database name" value="<?=try_get($_POST, "database"); ?>" /><br />
	    <h2>Administrator's account</h2>
	    <input type="text" name="admin_login" placeholder="administrator's login" value="<?=try_get($_POST, "admin_login"); ?>" /><br />
	    <input type="text" name="admin_mail" placeholder="administrator's mail" value="<?=try_get($_POST, "admin_mail"); ?>" /><br />
	    <input type="password" name="admin_password" placeholder="administrator's password" value="<?=try_get($_POST, "admin_password"); ?>" /><br />
	    <input type="password" name="admin_repassword" placeholder="administrator's password again" value="<?=try_get($_POST, "admin_repassword"); ?>" /><br />
	    <br />
	    <input type="submit" class="sexy" value="Install the Infosphere" />
	</form>
    </body>
</html>
