
<form id="fullpage_form" method="POST" action="index.php?p=<?=$PreviousPosition; ?>">
    <h2><?=$Dictionnary["Subscribe"]; ?></h2>
    <p>
	<input type="hidden" name="logaction" value="subscribe" />
	<input
	    type="text"
	    name="login"
	    placeholder="<?=$Dictionnary["Login"]; ?>"
	    value="<?=isset($_POST["login"]) ? $_POST["login"] : ""; ?>"
	/>
	<br />
	<input
	    type="text"
	    name="mail"
	    placeholder="<?=$Dictionnary["Mail"]; ?>"
	    value="<?=isset($_POST["mail"]) ? $_POST["mail"] : ""; ?>"
	/>
	<br />

	<input
	    type="password"
	    name="password"
	    placeholder="<?=$Dictionnary["Password"]; ?>"
	/>
	<br />
	<input
	    type="password"
	    name="repassword"
	    placeholder="<?=$Dictionnary["RepeatPassword"]; ?>"
	/>
	<br />

	<input type="submit" value="<?=$Dictionnary["Subscribe"]; ?>" />
    </p>
</form>
