<?php
global $Configuration;
global $BackgroundColor;
global $Background;
global $LanguageList;

$BCookie = $template ? "template" : "module";
$BackgroundColor = ' style="background-color: rgba(0, 0, 0, 0.1);" ';
$Background = true;
$js = "silent_submit(this)";
?>
<table id="down_edit_formular">
    <tr>
	<td colspan="2"><div class="final_box">
	    <input type="text" readonly style="width: 100%; text-align: center;"
		   <?php if ($module->id_template == -1) { ?>
		   value="<?=$Dictionnary["NoTemplate"]; ?>"
		   <?php } else { ?>
		   value="<?=$Dictionnary["BasedOn"]." ".$module->template_codename." - ".($module->template_link ? $Dictionnary["ActiveLink"] : $Dictionnary["BrokenLink"]); ?>"
		   <?php } ?>
	    />
	    <input type="text" readonly style="width: 100%; text-align: center;" value="<?=$module->codename; ?>" />
	    <?php edit_codename_form($page, $module); ?>
	    <?php edit_type_form($page, $module); ?>
	    <form
		method="put"
		onsubmit="return <?=$js; ?>;"
		action="/api/<?=$page; ?>/<?=$module->id; ?>"
		<?=$Background ? $BackgroundColor : ""; ?>
	    >
		<label for="subscription"><?=$Dictionnary["Subscription"]; ?></label>
		<select name="subscription" onchange="<?=$js; ?>">
		    <option value="0" <?=$module->subscription == 0 ? "selected" : ""; ?>>
			<?=$Dictionnary["Manual"]; ?>
		    </option>
		    <option value="1" <?=$module->subscription == 1 ? "selected" : ""; ?>>
			<?=$Dictionnary["Mandatory"]; ?>
		    </option>
		    <option value="2" <?=$module->subscription == 2 ? "selected" : ""; ?>>
			<?=$Dictionnary["Automatic"]; ?>
		    </option>
		</select>
	    </form>
	    <?php if ($module->parent_activity != -1 && $module->type_type == 2) { ?>
		<form
		    method="put"
		    onsubmit="return <?=$js; ?>;"
		    action="/api/<?=$page; ?>/<?=$module->id; ?>"
		    <?=$Background ? $BackgroundColor : ""; ?>
		>
		    <label for="declaration_type"><?=$Dictionnary["DeclarationType"]; ?></label>
		    <select name="declaration_type" onchange="<?=$js; ?>">
			<option value="0" <?=$module->declaration_type == 0 ? "selected" : ""; ?>>
			    <?=$Dictionnary["NoDeclaration"]; ?>
			</option>
			<option value="1" <?=$module->declaration_type == 1 ? "selected" : ""; ?>>
			    <?=$Dictionnary["LocalDeclaration"]; ?>
			</option>
			<option value="2" <?=$module->declaration_type == 2 ? "selected" : ""; ?>>
			    <?=$Dictionnary["GlobalDeclaration"]; ?>
			</option>
		    </select>
		</form>
	    <?php } ?>
	    <?php check_form($page, $module, "allow_unregistration", "AllowUnregistration"); ?>

	    <?php if ($module->parent_activity == -1) { ?>
		<?php check_form($page, $module, "hidden", "Hidden"); ?>
	    <?php } ?>
	    <?php check_form($page, $module, "validated", "Validated"); ?>

	    <?php $dates = ["emergence", "done", "registration", "close"]; ?>
	    <?php if ($module->parent_activity != -1) { ?>
		<?php $dates = array_merge($dates, ["subject_appeir", "subject_disappeir", "pickup"]); ?>
	    <?php } ?>
	   
	    <?php if ($template) { ?>

		<?php check_form($page, $module, "enabled", "Enabled"); ?>
		<br />

		<?php $Background = false; ?>
		<?php foreach ($dates as $dtype) { ?>
		    <?php $fields = ["week_{$dtype}_date", "day_{$dtype}_date", "hour_{$dtype}_date", $dtype]; ?>
		    <form
			method="put"
			onsubmit="return <?=$js; ?>;"
			action="/api/<?=$page; ?>/<?=$module->id; ?>"
			class="weekday_selector"
			<?=$Background ? $BackgroundColor : ""; ?>
		    >
			<label for="<?=$dtype; ?>_date">
			    <?=$Dictionnary[ucfirst($dtype)."Date"]; ?>
			</label>
			<?php $dtype_field = "{$dtype}_date"; ?>
			<?php print_weekday_selector(
			    $module->$dtype_field,
			    $fields,
			    NULL,
			    true,
			    $js
			); ?>
		    </form>
		<?php } ?>

	    <?php } else { ?>

		<br />
		<?php $Background = false; ?>
		<?php foreach ($dates as $dtype) { ?>
		    <form
			method="put"
			onsubmit="return <?=$js; ?>;"
			action="/api/<?=$page; ?>/<?=$module->id; ?>"
			class="weekday_selector"
			<?=$Background ? $BackgroundColor : ""; ?>
		    >
			<label for="<?=$dtype; ?>_date">
			    <?=$Dictionnary[ucfirst($dtype)."Date"]; ?>
			</label>
			<?php $dtype_field = "{$dtype}_date"; ?>
			<?php print_datetime(
			    $dtype,
			    [$dtype => $module->$dtype_field],
			    true,
			    "full_date",
			    "checkweekday",
			    $js
			); ?>
		    </form>
		<?php } ?>
		
	    <?php } ?>    
	    <br />

	    <?php $Background = !$Background; ?>
	    <?php if ($module->parent_activity == -1) { ?>
		
		<?php foreach ([
		    "credit_a" => "CreditA",
		    "credit_b" => "CreditB",
		    "credit_c" => "CreditC",
		    "credit_d" => "CreditD"
		] as $k => $v) { ?>
		    <?php single_field_form($page, $module, $k, $v, -1); ?>
		<?php } ?>
		<br />

		<?php $Background = !$Background; ?>
		<?php $js = "silent_submit(this)"; ?>
		<form method="put" onsubmit="return <?=$js; ?>;" action="/api/<?=$page; ?>/<?=$module->id; ?>">
		    <label for="validation"><?=$Dictionnary["Validation"]; ?></label>
		    <select
			name="validation"
			onchange="<?=$js; ?>"
			style="position: relative; left: -5px"
		    >
			<!-- Il faut un nombre précis de médaille pour chaque grade -->
			<option value="4" <?=$module->validation == 4 ? "selected" : ""; ?>>
			    <?=$Dictionnary["ValidationByCount"]; ?>
			</option>
			<!-- Il faut un pourcentage de médailles obligatoire a chaque grade -->
			<option value="3" <?=$module->validation == 3 ? "selected" : ""; ?>>
			    <?=$Dictionnary["ValidationByRank"]; ?>
			</option>
			<!-- Il faut une certaine moyenne pour avoir un grade donné -->
			<option value="2" <?=$module->validation == 2 ? "selected" : ""; ?>>
			    <?=$Dictionnary["ValidationByGrade"]; ?>
			</option>
			<!-- Il faut un pourcentage donné de la réserve de médaille -->
			<option value="1" <?=$module->validation == 1 ? "selected" : ""; ?>>
			    <?=$Dictionnary["ValidationByPercent"]; ?>
			</option>
			<!-- Il n'y a pas de validation -->
			<option value="0" <?=$module->validation == 0 ? "selected" : ""; ?>>
			    <?=$Dictionnary["NoGrade"]; ?>
			</option>
		    </select>
		</form>
		
		<?php foreach ([
		    "grade_a" => "GradeA",
		    "grade_b" => "GradeB",
		    "grade_c" => "GradeC",
		    "grade_d" => "GradeD",
		    "grade_bonus" => "GradeBonus"
		] as $k => $v) { ?>
		    <?php single_field_form($page, $module, $k, $v); ?>
		<?php } ?>

	    <?php } else { ?>

		<?php
		if (isset($module->reference_activity) && $module->reference_activity != NULL && $module->reference_activity != -1)
		    $module->reference_activity = db_select_one("codename FROM activity WHERE id = {$module->reference_activity}")["codename"];
		?>
		
		<?php single_field_form($page, $module, "reference_activity", "ReferenceActivity", -1); ?>
		<?php single_field_form($page, $module, "min_team_size", "MinTeamSize"); ?>
		<?php single_field_form($page, $module, "max_team_size", "MaxTeamSize"); ?>
		<?php single_field_form($page, $module, "repository_name", "RepositoryName"); ?>
		<?php single_field_form($page, $module, "slot_duration", "SlotDuration", -1); ?>
		<?php check_form($page, $module, "progressive_slot_opening", "ProgressiveSlotOpening"); ?>
		<?php check_form($page, $module, "team_based_slot_opening", "TeamBasedSlotOpening"); ?>
		<?php single_field_form($page, $module, "mark", "Mark"); ?>
		<?php single_field_form($page, $module, "estimated_work_duration", "EstimatedWorkDuration"); ?>

	    <?php } ?>

	    <br />

	</div></td>
	<td colspan="2"><div class="box_of_centered_div final_box" id="medal_box">
	    <?php require_once ("display_medal.phtml"); ?>
	</div></td>
	<td colspan="2">
	    <?php
	    if ($module->parent_activity != -1)
		$js = "silent_submitf(this, {after_success: list_activities(getCookie('".($template ? "template" : "activity")."-module'))});";
	    else
		$js = "silent_submitf(this, {after_success: function () { list_modules(); remove_down_formular(); } })";
	    ?>
	    <form
		method="delete"
		onsubmit="return window.confirm('<?=$Dictionnary["Confirm"]; ?>') && <?=$js; ?>;"
		action="/api/<?=$page; ?>/<?=$module->id; ?>"
	    >
		<input
		    type="button"
		    class="delete_wide"
		    onclick="window.confirm('<?=$Dictionnary["Confirm"]; ?>') && <?=$js; ?>;"
		    value="&#10007;"
		/>
	    </form>
	    <div class="final_box">

		<form
		    action="/api/activity/<?=$module->id; ?>/todolist"
		    method="put"
		    style="height; 120px;"
		>
		    <textarea
			name="todolist"
			id="todolist"
			oninput="delay_before_submit(1000, this, 'todolist');"
			style="width: calc(100% - 0px); margin: 0; height: 100px; resize: none;"
		    ><?=strlen(@$module->todolist) ? $module->todolist : ""; ?></textarea>
		</form>

		<?php list_of_links([
		    "hook_name" => "activity",
		    "hook_id" => $module->id,
		    "linked_name" => "cycle",
		    "linked_elems" => $module->cycle,
		    "admin_func" => "is_director_for_activity"
		]); ?>

		<?php
		$elems = [
		    "placeholder" => "Teacher or laboratory",
		    "table" => "teacher",
		    "" => "teacher", // Pas user, afin d'éviter de confondre avec les inscrits
		    "#" => "laboratory",
		];
		?>
		<?php list_of_links([
		    "hook_name" => "activity",
		    "hook_id" => $module->id,
		    "linked_name" => $elems,
		    "linked_elems" => $module->teacher,
		    "admin_func" => "am_i_director"
		]); ?>

		<?php
		$elems = [
		    "placeholder" => "Category, Lesson, Chapter, Activity",
		    "table" => "support",
		    "" => "support",
		    "#" => "support_asset",
		    "@" => "support_category",
		    "$" => "activity"
		];
		?>
		<?php list_of_links([
		    "hook_name" => "activity",
		    "hook_id" => $module->id,
		    "linked_name" => $elems,
		    "linked_elems" => $module->support,
		    "admin_func" => "is_teacher_for_activity"
		]); ?>

		<?php list_of_links([
		    "hook_name" => "activity",
		    "hook_id" => $module->id,
		    "linked_name" => "scale",
		    "linked_elems" => $module->scale,
		    "admin_func" => "is_teacher_for_activity"
		]); ?>
		<?php list_of_links([
		    "hook_name" => "activity",
		    "hook_id" => $module->id,
		    "linked_name" => "mcq",
		    "linked_elems" => $module->mcq,
		    "admin_func" => "is_teacher_for_activity"
		]); ?>
		<?php list_of_links([
		    "hook_name" => "activity",
		    "hook_id" => $module->id,
		    "linked_name" => "satisfaction",
		    "linked_elems" => $module->satisfaction,
		    "admin_func" => "is_teacher_or_director_for_activity"
		]); ?>
	    </div>
	</td>
    </tr>
    <?php $LngList = array_merge(["NA" => $Dictionnary["AllLanguages"]], $LanguageList); ?>
    <tr>
	<td>
	    <table class="table_split_halfv"><tr><td>
		<div class="language_buttons">
		    <?php foreach ($LngList as $k => $v) { ?>
			<input
			    type="button"
			    value="<?=$v; ?>";
			    class="languages_buttons"
			    onclick="select_language('<?=$k; ?>', this);"
			    style="
				  height: <?=100 / count($LngList); ?>%;
				  <?php if ($k == @$_COOKIE[$BCookie."-language"]) { ?>
				  color: white;
				  font-weight: bold;
				  <?php } ?>
				  "
			/>
		    <?php } ?>
		</div>
	    </td></tr><tr><td>
		<div class="category_buttons">
		    <?php foreach (($bts = ["basic", "syllabus", "training"]) as $cat) { ?>
			<input
			    type="button"
			    value="<?=$Dictionnary[ucfirst($cat)]; ?>"
			    onclick="select_category('<?=$cat; ?>', this);"
			    class="categories_buttons"
			    style="
				  height: <?=100 / count($bts); ?>%;
				  <?php if ($cat == @$_COOKIE[$BCookie."-category"]) { ?>
				  color: white;
				  font-weight: bold;
				  <?php } ?>
				  "
			/>
		    <?php } ?>
		</div>
	    </td></tr></table>
	</div></td>
	<td colspan="2"><div class="final_box">
	    <?php foreach ($LngList as $k => $v) { ?>
		<?php // Pour l'intra ?>
		<div class="activity_configuration_block basic_<?=$k; ?> basic">
		    <?php if ($k != "NA") { ?>
			<?php $js = "silent_submit(this)"; ?>
			<?php $field = "name"; ?>
			<form onsubmit="return <?=$js; ?>;" method="put" action="/api/<?=$page; ?>/<?=$module->id; ?>">
			    <?php if (is_teacher_for_activity($module->id) && $k != "NA") { ?>
				<input type="button" onclick="<?=$js; ?>" value="&#10003;" />
			    <?php } ?>
			    <input
				id="<?=$k; ?>_<?=$field; ?>_field"
				type="text"
				class="<?=$field; ?>_field"
				name="<?=$k; ?>_<?=$field; ?>"
				value="<?php $tmp = "{$k}_{$field}"; echo isset($module->$tmp) ? $module->$tmp : ""; ?>"
				<?php if (!is_teacher_for_activity($module->id) || $k == "NA") { ?>
				    style="background-color: lightgray;" readonly
				<?php } ?>
			    />
			    <?php $field = "description"; ?>
			    <textarea
				id="<?=$k; ?>_<?=$field; ?>_field"
				class="<?=$field; ?>_field"
				name="<?=$k; ?>_<?=$field; ?>"
				<?php if (!is_teacher_for_activity($module->id) || $k == "NA") { ?>
				    style="background-color: lightgray;" readonly
				<?php } ?>
			    ><?php $tmp = "{$k}_{$field}"; echo isset($module->$tmp) ? $module->$tmp : ""; ?></textarea>
			</form>
		    <?php } ?>
		</div>
		<?php // Pour le syllabus ?>
		<div class="activity_configuration_block syllabus_<?=$k; ?> syllabus">
		    <?php if ($k != "NA") { ?>
			<form onsubmit="<?=$js; ?>" method="put" action="/api/<?=$page; ?>/<?=$module->id; ?>">
			    <?php if (is_teacher_for_activity($module->id) && $k != "NA") { ?>
				<input type="button" onclick="<?=$js; ?>" value="&#10003;" />
			    <?php } ?>
			    <?php foreach (["objective", "method", "reference"] as $field) { ?>
				<?=$Dictionnary[ucfirst($field)]; ?>
				<textarea
				    id="<?=$k; ?>_<?=$field; ?>_field"
					class="<?=$field; ?>_field"
					name="<?=$k; ?>_<?=$field; ?>"
					<?php if (!is_teacher_for_activity($module->id) || $k == "NA") { ?>
					style="background-color: lightgray;" readonly
					<?php } ?>
				><?php $tmp = "{$k}_{$field}"; echo isset($module->$tmp) ? $module->$tmp : ""; ?></textarea>
			    <?php } ?>
			</form>
		    <?php } else { ?>
			<div style="position: relative;">
			    <?php list_of_links([
				"hook_name" => "activity",
				"hook_id" => $module->id,
				"linked_name" => "skill",
				"linked_elems" => $module->skill,
				"admin_func" => "is_teacher_for_activity"
			    ]); ?>
			</div>
		    <?php } ?>
		</div>
		<?php // Pour les formations pros ?>
		<div class="activity_configuration_block training_<?=$k; ?> training">
		    <?php if ($k != "NA") { ?>
			<form onsubmit="<?=$js; ?>" method="put" action="/api/<?=$page; ?>/<?=$module->id; ?>">
			    <?php if (is_teacher_for_activity($module->id)) { ?>
				<input type="button" onclick="<?=$js; ?>" value="&#10003;" />
			    <?php } ?>
			    <?php foreach (["TODO"] as $field) { ?>
				<?=$Dictionnary[ucfirst($field)]; ?>
				<textarea
				    id="<?=$k; ?>_<?=$field; ?>_field"
					class="<?=$field; ?>_field"
					name="<?=$k; ?>_<?=$field; ?>"
					<?php if (!is_teacher_for_activity($module->id) || $k == "NA") { ?>
					style="background-color: lightgray;" readonly
					<?php } ?>
				><?php $tmp = "{$k}_{$field}"; echo isset($module->$tmp) ? $module->$tmp : ""; ?></textarea>
			    <?php } ?>
			</form>
		    <?php } ?>
		</div>
	    <?php } ?>
	</td>
	<td><div>
	    <div class="ressource_buttons">
		<?php foreach (($bts = ["actions", "subject_configuration", "files", "mood", "softwares"]) as $res) { ?>
		    <input
			type="button"
			value="<?=$Dictionnary[ucfirst($res)]; ?>"
			onclick="select_ressource('<?=$res; ?>', this);"
			class="ressources_buttons"
			style="
			      height: <?=100 / count($bts); ?>%;
			      <?php if ($res == @$_COOKIE[$BCookie."-ressource"]) { ?>
			      color: white;
			      font-weight: bold;
			      <?php } ?>
			      "
		    />
		<?php } ?>
	    </div>
	</div></td>
	<td colspan="2"><div class="final_box">
	    <?php foreach ($LngList as $k => $v) { ?>
		<?php // Actions ?>
		<div class="activity_configuration_block actions_<?=$k; ?>">
		    <?php require ("control_panel.phtml"); ?>
		</div>
		<?php // Sujet/Configuration ?>
		<div class="activity_configuration_block subject_configuration_<?=$k; ?>">
		    <?php $fbid = "subject_browser"; ?>
		    <?php if (is_teacher_for_activity($module->id)) { ?>
			<?php $js = "silent_submit(this, '$fbid$k');"; ?>
			<form
			    method="post"
			    onsubmit="return <?=$js; ?>;"
			    action="/api/<?=$page; ?>/<?=$module->id; ?>/subject"
			    class="activity_file_upload_form"
			>
			    <label for="file"><?=$Dictionnary["Configuration"]; ?></label>
			    <input type="hidden" name="language" value="<?=$k; ?>" />
			    <input type="hidden" name="kind" value="configuration" />
			    <input
				type="file"
				name="file"
				accept=".dab"
				onchange="<?=$js; ?>"
			    />
			</form>
			<form
			    method="post"
			    onsubmit="return <?=$js; ?>;"
			    action="/api/<?=$page; ?>/<?=$module->id; ?>/subject"
			    class="activity_file_upload_form"
			>
			    <label for="file"><?=$Dictionnary["Subject"]; ?></label>
			    <input type="hidden" name="language" value="<?=$k; ?>" />
			    <input type="hidden" name="kind" value="subject" />
			    <input
				type="file"
				name="file"
				accept=".pdf,.txt,.htm,.html"
				onchange="<?=$js; ?>"
			    />
			</form>
		    <?php } ?>
		    <?php if (is_assistant_for_activity($module->id)) { ?>
			<div class="activity_file_browser_box">
			    <?=render_activity_subject_browser($page, $module->id, $module, $k); ?>
			</div>
		    <?php } ?>
		</div>
		<?php // Fichiers disponibles pour les élèves ?>
		<div class="activity_configuration_block files_<?=$k; ?>">
		    <div class="activity_file_column">
			<h5><?=$Dictionnary["Ressources"]; ?></h5>
			<?php $fbid = "file_browser"; ?>
			<?php if (is_teacher_for_activity($module->id)) { ?>
			    <?php $js = "silent_submit(this, '$fbid$k');"; ?>
			    <form
				method="post"
				onsubmit="return <?=$js; ?>;"
				action="/api/<?=$page; ?>/<?=$module->id; ?>/ressource"
				class="activity_file_upload_form"
			    >
				<label for="file"><?=$Dictionnary["File"]; ?></label>
				<input type="hidden" name="language" value="<?=$k; ?>" />
				<input id="path<?=$k; ?>2" type="hidden" name="path" value="" />
				<input
				    type="file"
				    name="file"
				    multiple="true"
				    onchange="document.getElementById('path<?=$k; ?>2').value = document.getElementById('pathfile_browser<?=$k; ?>').value; <?=$js; ?>"
				/>
			    </form>
			<?php } ?>
			<?php if (is_assistant_for_activity($module->id)) { ?>
			    <div id="subject_ressources_<?=$k; ?>">
				<?php
				$language = $k;
				$root = $Configuration->ActivitiesDir($module->codename, $k == "NA" ? "" : $k)."ressource/";
				$path = "/";
				$target = $root;
				$type = "ressource";
				$hidden_entries = ["admin"];
				new_directory($target);
				require ("./tools/template/path_browser.phtml");
				unset($hidden_entries);
				?>
			    </div>
			<?php } ?>
		    </div>
		    <div class="activity_file_column">
			<h5>Admin</h5>
			<?php $fbid = "admin_file_browser"; ?>
			<?php if (is_teacher_for_activity($module->id)) { ?>
			    <?php $js = "silent_submit(this, '$fbid$k');"; ?>
			    <form
				method="post"
				onsubmit="return <?=$js; ?>;"
				action="/api/<?=$page; ?>/<?=$module->id; ?>/ressource"
				class="activity_file_upload_form"
			    >
				<label for="file"><?=$Dictionnary["File"]; ?></label>
				<input type="hidden" name="language" value="<?=$k; ?>" />
				<input type="hidden" name="locked_path" value="admin" />
				<input id="admin_path<?=$k; ?>" type="hidden" name="path" value="admin" />
				<input
				    type="file"
				    name="file"
				    multiple="true"
				    onchange="document.getElementById('admin_path<?=$k; ?>').value = document.getElementById('pathadmin_file_browser<?=$k; ?>').value; <?=$js; ?>"
				/>
			    </form>
			<?php } ?>
			<?php if (is_teacher_for_activity($module->id)) { ?>
			    <div id="subject_admin_ressources_<?=$k; ?>">
				<?php
				$language = $k;
				$root = $Configuration->ActivitiesDir($module->codename, $k == "NA" ? "" : $k)."ressource/";
				$path = "/admin";
				$target = $root."admin/";
				$type = "ressource";
				$locked_path = "admin";
				new_directory($target);
				require ("./tools/template/path_browser.phtml");
				unset($locked_path);
				?>
			    </div>
			<?php } ?>
		    </div>
		</div>
		<?php // Fichiers d'ambiances - communs à toutes les langues ?>
		<?php if ($k == "NA") { ?>
		<div class="activity_configuration_block mood_NA">
		    <div class="activity_mood_unique_files">
			<?php if (is_teacher_for_activity($module->id)) { ?>
			    <?php $js = "silent_submit(this, 'wallpaper_configuration_$k');"; ?>
			    <form
				method="post"
				onsubmit="return <?=$js; ?>;"
				action="/api/<?=$page; ?>/<?=$module->id; ?>/wallpaper"
				class="activity_file_upload_form"
			    >
				<label for="file"><?=$Dictionnary["Wallpaper"]; ?></label>
				<input type="hidden" name="language" value="NA" />
				<input
				    type="file"
				    name="file"
				    accept=".jpg,.jpeg,.png"
				    onchange="<?=$js; ?>"
				/>
			    </form>
			<?php } ?>
			<?php if (is_assistant_for_activity($module->id) && 0) { ?>
			    <div class="activity_mood_preview" id="wallpaper_configuration_<?=$k; ?>">
				<?php if (isset($module->wallpaper["NA"][0])) { ?>
				<div
				    class="wallpaper_sample" style="background-image: url('<?=$module->wallpaper["NA"][0]; ?>');"
				    ondblclick="window.open('<?=$module->wallpaper["NA"][0]; ?>', '_blank');"
				>
				</div>
				<?php } ?>
			    </div>
			<?php } ?>
			<?php if (is_teacher_for_activity($module->id)) { ?>
			    <?php $js = "silent_submit(this, 'icon_configuration_$k');"; ?>
			    <form
				method="post"
				onsubmit="return <?=$js; ?>;"
				action="/api/<?=$page; ?>/<?=$module->id; ?>/icon"
				class="activity_file_upload_form"
			    >
				<label for="file"><?=$Dictionnary["Icon"]; ?></label>
				<input type="hidden" name="language" value="NA" />
				<input
				    type="file"
				    name="file"
				    accept=".jpg,.jpeg,.png"
				    onchange="<?=$js; ?>"
				/>
			    </form>
			<?php } ?>
			<?php if (is_assistant_for_activity($module->id) && 0) { ?>
			    <div class="activity_mood_preview" id="icon_configuration_<?=$k; ?>">
				<?php if (isset($module->icon["NA"][0])) { ?>
				<div
				    class="wallpaper_sample" style="background-image: url('<?=$module->icon["NA"][0]; ?>');"
				    ondblclick="window.open('<?=$module->icon["NA"][0]; ?>', '_blank');"
				>
				</div>
				<?php } ?>
			    </div>
			<?php } ?>
			<?php if (is_teacher_for_activity($module->id)) { ?>
			    <?php $js = "silent_submit(this, 'intro_configuration_$k');"; ?>
			    <form
				method="post"
				onsubmit="return <?=$js; ?>;"
				action="/api/<?=$page; ?>/<?=$module->id; ?>/intro"
				class="activity_file_upload_form"
			    >
				<label for="file"><?=$Dictionnary["AnimatedWallpaper"]; ?></label>
				<input type="hidden" name="language" value="NA" />
				<input
				    type="file"
				    name="file"
				    accept=".mp4,.ogv"
				    onchange="<?=$js; ?>"
				/>
			    </form>
			<?php } ?>
			<?php if (is_assistant_for_activity($module->id) && 0) { ?>
			    <div class="activity_mood_preview" id="intro_configuration_<?=$k; ?>">
				<?php if (isset($module->intro["NA"][0])) { ?>
				<video
				    controls
				    class="wallpaper_sample" src="<?=$module->intro["NA"][0]; ?>"
				    ondblclick="window.open('<?=$module->intro["NA"][0]; ?>', '_blank');"
				>
				</video>
				<?php } ?>
			    </div>
			<?php } ?>
		    </div>
		    <div class="activity_mood_music_files">
		    <?php $fbid = "mood_browser_"; ?>
		    <?php if (is_teacher_for_activity($module->id)) { ?>
			<?php $js = "silent_submit(this, '{$fbid}NA');"; ?>
			<form
			    method="post"
			    onsubmit="return <?=$js; ?>;"
			    action="/api/<?=$page; ?>/<?=$module->id; ?>/mood"
			    class="activity_file_upload_form"
			>
			    <label for="file"><?=$Dictionnary["MusicOrPlaylist"]; ?></label>
			    <input type="hidden" name="language" value="NA" />
			    <input type="hidden" name="fbid" value="<?=$fbid; ?>" />
			    <input
				type="file"
				name="file"
				multiple="true"
				accept=".txt,.mp3,.ogg"
				onchange="<?=$js; ?>"
			    />
			</form>
		    <?php } ?>
		    <?php if (is_assistant_for_activity($module->id)) { ?>
			<div class="activity_mood_browser" id="music_configuration_<?=$k; ?>">
			    <?php
			    $file_browser_height = "calc(100% - 45px)";
			    $language = "NA";
			    $root = $Configuration->ActivitiesDir($module->codename, "")."mood/";
			    $path = "/";
			    $target = $root;
			    $type = "mood";
			    new_directory($target);
			    require ("./tools/template/path_browser.phtml");
			    ?>
			</div>
		    <?php } ?>
		    </div>
		</div>
		<?php } ?>
		<?php // Moulinettes et binaire de référence - communs à toutes les langues ?>
		<?php if ($k == "NA") { ?>
		<div class="activity_configuration_block softwares_NA">
		    <?=render_activity_software_panel($page, $module->id, $module, "NA"); ?>
		</div>
		<?php } ?>
	    <?php } ?>
	</div></td>
    </tr>
</table>
