<tr>
    <th class="id_column" style="width: <?=30 - $left; ?>px;">#</th>
    <th class="codename_column"><?=$Dictionnary["CodeName"]; ?></th>
    <th class="description_column"><?=$Dictionnary["Description"]; ?></th>
    <th class="date_column"><?=$Dictionnary["Date"]; ?></th>
    <th class="medal_column"><?=$Dictionnary["Medals"]; ?></th>
    <th class="edit_column"><img src="./res/cog.png" /></th>
</tr>
