<form
    method="POST"
    action="index.php?<?=unrollget(); ?>"
    class="add_formular"
>
    <input type="hidden" name="action" value="add_user" />
    <input type="hidden" name="cycle" value="<?=$cycle; ?>" />

    <h2><?=$Dictionnary["AddUser"]; ?></h2><br />
    <div>
	<input
	    type="text"
	    name="login"
	    placeholder="<?=$Dictionnary["Login"]; ?>"
	    value="<?=try_get($_POST, "login"); ?>"
	/><br />
	<br />
	<input type="submit" value="&#10003;" />
    </div>
</form>
