
<?php if ($page == "cycle") { ?>
    <td class="click_list">
	<?php
	$users = db_select_all("
	  id, codename
          FROM user
          WHERE deleted IS NULL
          ORDER BY codename ASC
        ");
	foreach ($users as $usr) { ?>
	    <div onclick="add_to_listfield(this, '<?=$usr["codename"]; ?>', 'user<?=$cycle["id"]; ?>_name');">
		<div <?=clickable("index.php?p=ProfileMenu&amp;a={$usr["id"]}"); ?>>&#x1F50D;&#xFE0E</div>
		<?=display_avatar($usr, 50); ?>
		<p><?=$usr["codename"]; ?></p>
	    </div>
	<?php } ?>
    </td>

    <td>
	<?php list_of_links([
	    "hook_name" => "cycle",
	    "hook_id" => $cycle["id"],
	    "linked_name" => "user",
	    "linked_elems" => $cycle["user"],
	    "admin_func" => "is_director_for_cycle",
	]); ?>
    </td>
<?php } ?>

<td class="click_list">
    <?php
    $link = $page == "cursus" ? "ActivityTemplatesMenu" : "InstancesMenu";
    $not_too_old = "";
    if ($page == "cycle")
	$not_too_old = "
          AND done_date > '".$cycle["first_day"]."'
	  ";
    $acts = db_select_all("
       id, codename, {$Language}_name as name
       FROM activity
       WHERE is_template = ".($page == "cursus" ? 1 : 0)."
       AND deleted IS NULL $not_too_old
       ");
    foreach ($acts as $act) { ?>
	<div onclick="add_to_listfield('<?=$usr["codename"]; ?>', 'activity<?=$cycle["id"]; ?>_name');">
	    <div <?=clickable("index.php?p=$link&amp;a={$act["id"]}"); ?>>&#x1F50D;&#xFE0E</div>
	    <p><?=$act["codename"]; ?> <?=$act["name"]; ?></p>
	</div>
    <?php } ?>
</td>

<td>
    <?php list_of_links([
	"hook_name" => "cycle",
	"hook_id" => $cycle["id"],
	"linked_name" => "activity",
	"linked_elems" => $cycle["user"],
	"admin_func" => "is_director_for_cycle",
    ]); ?>
</td>
