<td style="padding-left: 0px !important; padding-right: 0px !important; margin: 0;">
    <table class="no_border" style="height: 100%; width: 100%;"><tr><td style="width: 50%;">
	<?php list_of_links([
	    "hook_name" => $page,
	    "hook_id" => $content["id"],
	    "linked_name" => [
		"placeholder" => "Teacher or laboratory",
		"table" => "teacher",
		"" => "teacher",
		"#" => "laboratory",
	    ],
	    "linked_elems" => $content["teacher"],
	    "admin_func" => "is_director_for_cycle"
	]); ?>
	<?php if ($page == "cycle") { ?>
	    <?php list_of_links([
		"hook_name" => "cycle",
		"hook_id" => $content["id"],
		"linked_name" => "school",
		"linked_elems" => $content["school"],
		"admin_func" => "is_director_for_cycle"
	    ]); ?>
	<?php } ?>
	<?php if ($page == "cursus") { ?>
	    <?php if (count($content["instance"])) { ?>
		<h5><?=$Dictionnary["CycleInstances"]; ?></h5>
		<?php foreach ($content["instance"] as $instance) { ?>
		    <a href="index.php?p=CycleMenu&amp;a=<?=$instance["id"]; ?>">
			<?=$instance["codename"]; ?>
		    </a>
		<?php } ?>
	    <?php } ?>
	<?php } else if ($content["id_template"] != -1) { ?>
	    <h5><?=$Dictionnary["Template"]; ?></h5>
	    <a href="index.php?p=CycleTemplateMenu&amp;a=<?=$content["id_template"]; ?>">
		<?=$content["codename_template"]; ?>
	    </a>
	<?php } ?>
    </td><td>

	<?php $js = "silent_submit(this);" ?>
	<?php if ($page == "cycle") { ?>
	    <form
		method="put"
		action="/api/<?=$page; ?>/<?=$content["id"]; ?>"
		style="display: inline-block;"
	    >
		<input type="hidden" name="check_done" value="1">
		<input type="checkbox" name="done" onchange="silent_submit(this);" <?=$content["done"] ? "checked" : ""; ?> />
		<label for="done"><?=$Dictionnary["CycleDone"]; ?></label>
	    </form>
	<?php } else { ?>
	    <form
		method="post"
		action="/api/<?=$page; ?>/<?=$content["id"]; ?>/instantiate"
	    >
		<input
		    type="date"
		    name="first_week"
		    placeholder="<?=$Dictionnary["FirstWeekDate"]; ?>"
		/><br />
		<input
		    type="text"
		    name="instance_name"
		    placeholder="<?=$Dictionnary["CodeName"]; ?>"
		/><br />
		<input type="button" onclick="<?=$js; ?>" value="<?=$Dictionnary["Instantiate"]; ?>" />
	    </form>
	<?php } ?>

	<form method="post" action="index.php?<?=unrollget(["silent" => 1, "export" => 1]); ?>" style="display: inline-block;">
	    <input type="hidden" name="action" value="export_activity" />
	    <input type="hidden" name="cycle" value="<?=$content["id"]; ?>" />
	    <select name="format">
		<option value="sketch"><?=$Dictionnary["Sketch"]; ?></option>
		<option value="detailed_sketch"><?=$Dictionnary["DetailedSketch"]; ?></option>
		<option value="syllabus"><?=$Dictionnary["Syllabus"]; ?></option>
	    </select>
	    <input type="submit" value="<?=$Dictionnary["Export"]; ?>" />
	</form>
    </td><td style="width: 50px; padding-right: 0px;">

	<?php $js = "window.confirm('".$Dictionnary["ConfirmDeletion"]."') && silent_submit(this, 'cyclelist');" ?>
	<form
	    method="delete"
	    action="/api/<?=$page; ?>/<?=$content["id"]; ?>"
	    style="width: 100%; height: 100%;"
	    onsubmit="return <?=$js; ?>;"
	>
	    <input
		type="button"
		onclick="<?=$js; ?>"
		value="&#10007;"
		style="color: red; width: 50px; height: 100%;"
	    />
	</form>
    </td></tr></table>
</td>
