<?php
$page = ($Position == "CycleTemplateMenu") ? "cursus" : "cycle";
$id = try_get($_GET, "a", -1);
$unique = $id != -1;
?>

<div>
    <?php if ($page == "cycle") { ?>
	<h2 class="alignable_blocks"><?=$Dictionnary["Cycle"]; ?></h2>
    <?php } else { ?>
	<h2 class="alignable_blocks"><?=$Dictionnary["CycleTemplate"]; ?></h2>
    <?php } ?>
    <?php if ($id != -1) { ?>
	<?php if (($cycle = fetch_cycle($page, $id, true, false, true)) != []) { ?>
	    <?php $cycle = $cycle[array_key_first($cycle)]; ?>
	    <h2 class="alignable_blocks">- <?=$cycle["codename"]; ?></h2>
	<?php } ?>
    <?php } else { ?>
	<form
	    class="alignable_blocks searchbar"
	    method="get"
	    onsubmit="return use_search('/api/<?=$page; ?>', this, 'cyclelist');"
	>
	    <input
		type="text"
		id="searchbar"
		placeholder="<?=$Dictionnary["Search"]; ?>"
	    />
	</form>
    <?php } ?>
</div>

<?php if ($unique) { ?>

    <table class="big_top_table"><tr>
	<?php require ("display_cycle.phtml"); ?>
    </tr></table>
    
<?php } else { ?>

    <?php if (is_admin()) { ?>
	<table class="edit_console"><tr><td>
    <?php }?>
    <div class="fullscreen scrollable" id="cyclelist">
	<?php require ("list_cycle.phtml"); ?>
    </div>
    <?php if (is_admin()) { ?>
    </td><td class="formular_slot">
        <?php require ("add_cycle.phtml"); ?>
    </td></tr></table>
<?php } ?>

<?php } ?>


