<?php
if (is_admin())
    $colspan = 5;
else
    $colspan = 3;

$hidden = [];
?>
<script language="Javascript">
 function toggle(source)
 {
     if ((checkboxes = document.getElementsByName('id_user[]')) == NULL)
	 return ;
     for (var i = 0, n = checkboxes.length; i<n; i++)
     {
	 checkboxes[i].checked = source.checked;
     }
 }
</script>
<input type="hidden" name="action" value="move">

<div class="double_horizontal" style="height: 80%;">
    <div style="overflow: auto;">
	<h3><?=$Dictionnary["Users"]; ?></h3>

	<table class="content_table"
	    <tr>
		<th>#</th>
		<th><?=$Dictionnary["Avatar"]; ?></th>
		<th><?=$Dictionnary["Login"]; ?></th>
		<th><?=$Dictionnary["CreditOnThatCycle"]; ?></th>
		<?php if (is_admin()) { ?>
		<th class="edit_column"><img src="./res/cog.png" /></th>
		<?php } ?>
	    </tr>
	    <?php foreach ($fetch["user"] as $y) { ?>
		<?php if (is_cycle_hidden($y, $cycle)) { $hidden[$y->codename] = true; continue ; } ?>
	    <tr>
		<td><?=$y->id; ?></td>
		<td>
		    <?php display_avatar($y, 50); ?>
		</td>
		<td>
		    <a href="index.php?p=ProfileMenu&amp;a=<?=$y->id; ?>"><?=$y->codename; ?>
		</td>
		<td>
		    <?php
		    foreach ($y->sublayer as $sub)
		    {
			if ($sub->id == $fetch["id"])
			{
			    echo $sub->acquired_credit." / ".$sub->credit;
			}
		    }
		    ?>
		</td>
		<?php if (is_admin()) { ?>
		<td>
		    <form action="index.php?p=<?=$Position; ?>&amp;a=<?=try_get($_GET, "a", -1); ?>" method="post">
			<input type="hidden" name="action" value="remove_user" />
			<input type="hidden" name="user" value="<?=$y->id; ?>" />
			<input type="hidden" name="cycle" value="<?=$fetch["id"]; ?>" />
			<input type="submit" value="&#10007;" style="color: red; font-size: xx-large;" />
		    </form>
		</td>
		<?php } ?>
	    </tr>
	    <?php } ?>
	    <tr>
		<td colspan="<?=$colspan; ?>">
		    <?php $namelist = []; ?>
		    <?php foreach ($fetch["user"] as $y) { ?>
			<?php if (isset($hidden[$y->codename])) continue ; ?>
			<?php $namelist[] = $y->codename; ?>
		    <?php } ?>
		    <input type="text" value="<?=implode(";", $namelist); ?>" />
		</td>
	    </tr>
	    <?php if (is_admin()) { ?>
		<tr>
		    <td colspan="<?=$colspan; ?>">
		    <?php require_once ("add_student.phtml"); ?>
		</td>
	    </tr>
	    <?php } ?>
	</table>
    </div>

    <?php
    if (is_admin())
	$colspan = 5;
    else
	$colspan = 4;
    ?>

    <div style="overflow: auto;">
	<h3><?=$Dictionnary["Activity"]; ?></h3>

	<table class="content_table">
	    <tr>
		<th>#</th>
		<th><?=$Dictionnary["Module"]; ?></th>
		<th><?=$Dictionnary["Name"]; ?></th>
		<th><?=$Dictionnary["BeginDate"]; ?></th>
		<?php if (is_admin()) { ?>
		<th class="edit_column"><img src="./res/cog.png" /></th>
		<?php } ?>
	    </tr>
	    <?php foreach ($fetch["activity"] as $y) { ?>
	    <tr>
		<td><?=$y["id"]; ?></td>
		<td>
		    <a href="index.php?p=InstancesMenu&amp;activity=<?=$y["id"]; ?>">
			<?=$y["codename"]; ?>
		    </a>
		</td>
		<td>
		    <a href="index.php?p=ModulesMenu&amp;a=<?=$y["id"]; ?>&amp;student=1">
			<?=$y["name"]; ?>
		    </a>
		</td>
		<td>
		    <?php if ($y["emergence_date"] != NULL) { ?>
			<?=$y["emergence_date"]; ?>
		    <?php } else { ?>
			<?=$fetch["first_day"]; ?>
		    <?php } ?>
		    <?php if ($y["subscription"] == 2) { ?>
			<?=$Dictionnary["Automatic"]; ?>
		    <?php } ?>
		</td>
		<?php if (is_admin()) { ?>
		<td>
		    <form action="index.php?<?=unrollget(); ?>" method="post" style="width: 100%;">
			<input type="hidden" name="action" value="subscribe" />
			<input type="hidden" name="activity" value="<?=$y["id"]; ?>" />
			<input type="text" name="logins" style="width: 49%;" />
			<input type="submit" value="<?=$Dictionnary["Subscribe"]; ?>" style="width: 49%;" />
		    </form>
		    <form action="index.php?<?=unrollget(); ?>" method="post" style="width: 100%;">
			<input type="hidden" name="action" value="unsubscribe" />
			<input type="hidden" name="activity" value="<?=$y["id"]; ?>" />
			<input type="text" name="logins" style="width: 49%;" />
			<input type="submit" value="<?=$Dictionnary["Unsubscribe"]; ?>" style="width: 49%;" />
		    </form>
		    <form action="index.php?<?=unrollget(); ?>" method="post">
			<input type="hidden" name="action" value="remove_activity" />
			<input type="hidden" name="activity" value="<?=$y["id"]; ?>" />
			<input type="hidden" name="cycle" value="<?=$fetch["id"]; ?>" />
			<input type="submit" value="&#10007;" style="color: red; width: 100%;" />
		    </form>
		</td>
		 <?php } ?>
	    </tr>
	    <tr>
		<td colspan="<?=is_admin() ? "5" : "4"; ?>" style="column-count: 5; text-align: center;">
		    <?php
		    foreach ($y["user"] as $usr)
		    {
			$fnd = false;
			foreach ($fetch["user"] as $usr2)
			{
			    if ($usr2->codename == $usr["codename"])
				$fnd = true;
			}
			if (isset($hidden[$usr["codename"]]))
			    continue ;
			if ($fnd)
			    echo $usr["codename"]."<br />";
		    }
		    ?>
		</td>
	    </tr>
	    <?php } ?>
	    <tr>
		<td colspan="<?=$colspan; ?>">
		    <?php $namelist = []; ?>
		    <?php foreach ($fetch["activity"] as $y) { ?>
			<?php $namelist[] = $y["codename"]; ?>
		    <?php } ?>
		    <input type="text" value="<?=implode(";", $namelist); ?>" />
		</td>
	    </tr>
	    <?php if (is_admin()) { ?>
	    <tr>
		<td colspan="<?=$colspan; ?>">
		    <?php require_once ("add_activity.phtml"); ?>
		</td>
	    </tr>
	    <?php } ?>
	</table>
    </div>
</div>
