<?php $URL = unrollurl(["a" => $content["id"]]); ?>

<td <?=clickable($URL); ?>><?=$content["id"]; ?></td>
<td>
    <b><?=$content["codename"]; ?></b><br />
    <?=@$content["name"]; ?>
</td>
<td>
    <?=$content["min_credit"]; ?> - <?=$content["max_credit"]; ?>
</td>
<?php if ($content["is_template"] == 0) { ?>
    <td <?=clickable($URL); ?>><?=datex("d/m/Y", $content["first_day"]); ?></td>
    <td <?=clickable($URL); ?>><?=datex("d/m/Y", $content["last_day"]); ?></td>
<?php } ?>
<td <?=clickable($URL); ?>><?=$content["cycle"]; ?> (<?=$Dictionnary["Year"]; ?> <?=floor($content["cycle"] / 4) + 1; ?>, <?=$Dictionnary["Cycle"]; ?> <?=$content["cycle"] % 4 + 1; ?>)</td>
<?php if ($page == "cycle") { ?>
    <td <?=clickable($URL); ?>><?=count($content["user"]); ?></td>
<?php } ?>
<td <?=clickable($URL); ?>><?=count($content["activity"]); ?></td>
<?php if (!is_admin()) { ?>
    <td>
	<h5><?=$Dictionnary["Teacher"]; ?></h5>
	<?php foreach ($content["teacher"] as $teacher) { ?>
	    <?php $dest = $teacher["codename"][0] != "#" ? "Profile" : "Laboratories"; ?>
	    <a href="index.php?p=<?=$dest; ?>Menu&amp;a=<?=$teacher["id"]; ?>">
		<?=$teacher["codename"]; ?>
	    </a>
	<?php } ?>
	<?php if ($page == "cursus") { ?>
	    <?php if (count($content["instance"])) { ?>
		<h5><?=$Dictionnary["CycleInstances"]; ?></h5>
		<?php foreach ($content["instance"] as $instance) { ?>
		    <a href="index.php?p=CycleMenu&amp;a=<?=$instance["id"]; ?>">
			<?=$instance["codename"]; ?>
		    </a>
		<?php } ?>
	    <?php } ?>
	<?php } else if ($content["id_template"] != -1) { ?>
	    <h5><?=$Dictionnary["Template"]; ?></h5>
	    <a href="index.php?p=CycleTemplateMenu&amp;a=<?=$content["id_template"]; ?>">
		<?=$content["codename_template"]; ?>
	    </a>
	<?php } ?>
    </td>
<?php } else { ?>
    <?php require ("edit_cycle.phtml"); ?>
<?php } ?>
