<table class="content_table">
    <tr>
	<th>#</th>
	<th><?=$Dictionnary["CodeName"]; ?></th>
	<th><?=$Dictionnary["Name"]; ?></th>
	<th><?=$Dictionnary["Description"]; ?></th>
	<th><?=$Dictionnary["NumberAssets"]; ?></th>
    </tr>
    <?php
    $cnt = 0;
    foreach ($fetch as $y)
    {
    $URL = "index.php?p=".$Position."&amp;a=".$y["id"];
    ?>
    <tr class="content_<?=$cnt++ % 2 ? "even" : "odd"; ?>">
	<td <?=clickable($URL); ?>><?=$y["id"]; ?></td>
	<td <?=clickable($URL); ?>><?=$y["codename"]; ?></td>
	<td <?=clickable($URL); ?>><?=$y["name"]; ?></td>
	<td <?=clickable($URL); ?>><?=$y["description"]; ?></td>
	<td <?=clickable($URL); ?>><?=count($y["asset"]); ?></td>
    </tr>
    <?php
    }
    ?>
</table>
<?php
if (is_admin())
require_once("add.phtml");
?>
