<h3><?=$Dictionnary["Class"]; ?>&nbsp;:&nbsp;<?=$fetch["name"]; ?></h3>
<a href="index.php?p=<?=$Position; ?>">
    &larr;
</a>
<table class="content_table">
    <tr>
	<th>#</th>
	<th><?=$Dictionnary["CodeName"]; ?></th>
	<th><?=$Dictionnary["Chapter"]; ?></th>
	<th><?=$Dictionnary["Name"]; ?></th>
	<th><?=$Dictionnary["Content"]; ?></th>
	<th><?=$Dictionnary["Edition"]; ?></th>
    </tr>
    <?php
    foreach ($fetch["asset"] as $assets)
    {
        if ($assets["deleted"] == 0)
        {
    ?>
    <tr>
	<td><?=$assets["id"]; ?></td>
	<td><?=$assets["codename"]; ?></td>
	<td><?=$assets["chapter"]; ?></td>
	<td><?=$assets["name"]; ?></td>
	<td>
	    <?php if ($assets["content"] != "") { ?>
	    <a href="<?=$assets["content"]; ?>" target="_blank">Lien</a>
	    <?php } else if (substr($assets["link"], 0, 4) == "http") { ?>
	    <a href="<?=$assets["link"]; ?>" target="_blank">
		<?=$Dictionnary["Link"]; ?>
	    </a>
	    <?php } else if (strlen($assets["link"]) < 15) { ?>
	    <a href="https://www.youtube.com/embed/<?=$assets["link"]; ?>" target="_blank">
		<?=$Dictionnary["Link"]; ?>
	    </a>
	    <?php } else {
		$host = array_reverse(explode(".", $_SERVER["HTTP_HOST"]));
		$host = "https://video.".$host[1].".".$host[0]."/";
	    ?>
		<a href="<?=$host; ?>videos/embed/<?=$assets["link"]; ?>" target="_blank">
		    <?=$Dictionnary["Link"]; ?>
		</a>
	    <?php } ?>
	</td>
	<td>
	    <?php if (is_admin()) { ?>
	    <form method="post" action="index.php?<?=unrollget(); ?>" style="display: inline-block;">
		<input type="hidden" name="action" value="remove" />
		<input type="hidden" name="id" value="<?=$assets['id']; ?>" />
		<input type="submit" value="&#10007;" style="color: red;" />
	    </form>
	    <form method="post" action="index.php?<?=unrollget(); ?>" style="display: inline-block;">
		<input type="hidden" name="action" value="superremove" />
		<input type="hidden" name="id" value="<?=$assets['id']; ?>" />
		<input type="submit" value="Super &#10007;" style="color: red;" />
	    </form>
	    <br />
	    <?php
	    $act = db_select_all("
	      activity_support.id_activity as id,
              activity.codename as codename,
	      activity.is_template as is_template
              FROM activity_support
              LEFT JOIN activity
              ON activity_support.id_activity = activity.id
              WHERE id_class_asset = {$assets["id"]}
	    ");
	    ?>
	    <?php foreach ($act as $a) { ?>
	    <a href="index.php?p=<?=$a["is_template"] ? "ActivitiesMenu" : "InstancesMenu"; ?>&amp;activity=<?=$a["id"]; ?>">
		<?=$a["codename"]; ?>
	    </a>
	    <?php } ?>

	    <?php } ?>
	</td>
    </tr>
    <?php } ?>
    <?php } ?>
</table>
<?php
if (is_admin())
require_once("add_sub.phtml");
?>
