<br />
<form method="POST" action="index.php?p=<?=$Position; ?>"  class="add_formular" enctype="multipart/form-data">
    <input type="hidden" name="action" value="add" />
    <h2><?=$Dictionnary["AddARoom"]; ?></h2><br />
    <div>
	<input
	    type="text"
		  name="codename"
		  placeholder="<?=$Dictionnary["CodeName"]; ?>"
		  value="<?=try_get($_POST, "codename"); ?>"
	/><br />
	<input
	    type="text"
		  name="capacity"
		  placeholder="<?=$Dictionnary["Capacity"]; ?>"
		  value="<?=try_get($_POST, "capacity"); ?>"
	/><br />
	<br />
	<input type="hidden" name="MAX_FILE_SIZE" value="<?=1024 * 1024 * 2; ?>" />
	<span><?=$Dictionnary["Map"]; ?></span><br />
	<input
	    type="file"
		  name="map"
		  accept="image/png"
		  placeholder="<?=$Dictionnary["Map"]; ?>"
		  value="<?=try_get($_POST, "map"); ?>"
	/><br />
	<span><?=$Dictionnary["Configuration"]; ?></span><br />
	<input
	    type="file"
		  name="conf"
		  placeholder="<?=$Dictionnary["Configuration"]; ?>"
		  value="<?=try_get($_POST, "configuration"); ?>"
	/><br />
	<?php forge_language_formular(["name" => "text"], $_POST); ?>
	<br />
	<input type="submit" value="&#10003;" />
    </div>
</form>

