<div class="page">

    <div style="text-align: center; width: 100%; height: 100px; padding-top: 15px; padding-bottom: 15px; background-color: lightgray;">
	<img src="./res/logo.png" style="widht: 100px; height: 100px;" />
    </div>
    <br />
    <br />

    <div>
	<div style="width: 50%; float: left;">
	    <div>
		<div style="width: 50%; font-weight: bold; float: left;">
		    <?=$Dictionnary["StudentName"]; ?>:
		</div>
		<div style="width: 50%; float: left;">
		    <?=$user["first_name"]; ?> <?=strtoupper($user["family_name"]); ?>
		</div>
	    </div>

	    <div>
		<div style="width: 50%; font-weight: bold; float: left;">
		    <?=$Dictionnary["WithdrawnDate"]; ?>:
		</div>
		<div style="width: 50%; float: left;">
		    <?=date("d/m/Y", time()); ?>
		</div>
	    </div>
	</div>

	<div style="width: 50%; float: left;">
	    <div>
		<div style="width: 50%; font-weight: bold; float: left;">
		    <?=$Dictionnary["ProvidedFor"]; ?>:
		</div>
		<div style="width: 50%; float: left; font-size: x-small;">
		    <?=$user["address_name"]; ?><br />
		    <?=$user["street_name"]; ?><br />
		    <?=$user["postal_code"]; ?>
		    <?=strtoupper($user["city"]); ?><br />
		    <?=$user["country"]; ?>
		</div>
	    </div>
	</div>
    </div>
    <br />
    <br />
    <br />
    <br />


