<br />
<form method="POST" action="index.php?p=<?=$Position; ?>"  class="add_formular"
      enctype="multipart/form-data"
>
    <input type="hidden" name="action" value="add_group" />
    <h2><?=$Dictionnary["AddAGroup"]; ?></h2><br />
    <div>
	<input
	    type="text"
		  name="codename"
		  placeholder="<?=$Dictionnary["GroupName"]; ?>"
		  value="<?=try_get($_POST, "codename"); ?>"
	/><br />
	<input
	    type="file"
		  name="icon"
		  accept="image/png"
		  placeholder="<?=$Dictionnary["Icone"]; ?>"
		  value="<?=try_get($_POST, "icon"); ?>"
	/><br />
	<?php forge_language_formular(["name" => "text", "description" => "textarea"], $_POST); ?>
	<br />
	<input type="submit" value="&#10003;" />
    </div>
</form>




