<?php
if (is_admin())
{
    require_once ("add.phtml");
    echo "<br />";
}
?>

<table class="content_table">
    <tr>
	<th class="id_column">#</th>
	<th class="icon_column"><?=$Dictionnary["Icon"]; ?></th>
	<th class="codename_column"><?=$Dictionnary["CodeName"]; ?></th>
	<th class="name_column"><?=$Dictionnary["Name"]; ?></th>
	<th class="wide_column"><?=$Dictionnary["School"]; ?></th>
	<th><?=$Dictionnary["HowManyStudents"]; ?></th>
	<?php if (is_admin()) { ?>
	<th class="edit_column"><img src="./res/cog.png" /></th>
	<?php } ?>
    </tr>
    <?php
    foreach ($fetch as $content)
    {
        $URL = "index.php?p=".$Position."&amp;a={$content["id"]}";
    ?>
    <tr class="content_<?=$cnt++ % 2 ? "even" : "odd"; ?>">
	<td <?=clickable($URL); ?>><?=$content["id"]; ?></td>
	<td <?=clickable($URL); ?>>
	    <img
		src="<?=$content["icon"] != "" ? $content["icon"] : "res/no_avatar.png"; ?>"
	        alt="<?=$Dictionnary["Avatar"]; ?>"
	        width="50"
	        height="50"
	    />
	</td>
	<td <?=clickable($URL); ?>><?=$content["codename"]; ?></td>
	<td <?=clickable($URL); ?>><?=$content["name"]; ?></td>
	<td>
	    <?php
	    if (isset($content["school"]))
	    {
		foreach ($content["school"] as $sc)
		{
	    ?>
		<a href="index.php?p=SchoolMenu&amp;a=<?=$sc["id"]; ?>">
		    <?=$sc["codename"]; ?>
		</a>
	    <?php
	    }
	    }
	    ?>
	</td>
	<td <?=clickable($URL); ?>><?=count($content["user"]); ?></td>
	<?php
	if (is_admin())
	require ("edition.phtml");
	?>
    </tr>
    <?php } ?>
</table>

