<?php
$top_support = [];
if (is_admin())
{
    $top_support = db_select_all("
	* FROM support WHERE deleted IS NULL ORDER BY codename ASC
    ", "id");
    foreach ($top_support as &$ts)
	$ts["full_load"] = true;
}
else
{
    function enlarge_supports(&$top_support, $id)
    {
	$supports = db_select_all("
                   activity_support.*,
                   support_asset.id_support as id_support_reco
                   FROM activity_support
                   LEFT JOIN support_asset.id = activity_support.id_support_asset
                   WHERE id_activity = {$module->id}
	");
	foreach ($supports as $sup)
	{
	    if ($sub["id_support"] == NULL)
	    {
		$top_support[$sub["id_support"]]["full_load"] = true;
	    }
	    else if ($sub["id_support_asset"])
	    {
		if (!isset($top_support[$sub["id_support_reco"]]))
		    $top_support[$sub["id_support_reco"]]["full_load"] = false;
		$top_support[$sub["id_support_reco"]]["assets"][$sub["id_support_asset"]] = true;
	    }
	}
    }

    $user = get_full_profile($User, []);
    
    foreach ($user->sublayer as $cycle)
    {
	foreach ($cycle->sublayer as $module)
	{
	    enlarge_top_supports($top_support, $module->id);
	    foreach ($module->sublayer as $activity)
		enlarge_top_supports($top_support, $activity->id);
	}
    }
}
?>
<table class="submenu"><tr class="submenutr"><td class="submenutd">
    <?php foreach ($top_support as $k => $v) { ?>
	
    <?php } ?>
</td><td class="submenutd">
    B
</td></tr></table>
