<h2><?=$Dictionnary["Elearning"]; ?></h2>
<i>Cette page est en construction.</i>

<?php

if (isset($_GET["a"]) && is_number($_GET["a"]))
{
    if (($t = db_select_one("* FROM class_asset WHERE id = ".$_GET["a"])) == NULL)
      return ;
    $x = explode("=", $t["fr_link"])[1];

?>
    <h4><?=$t["fr_name"]; ?></h4>
    <iframe
	width="100%"
	height="90%"
	src="https://www.youtube.com/embed/<?=$x; ?>"
	frameborder="0"
	allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
	allowfullscreen>
    </iframe>
<?php

}
else
{
  $limit = "";
  $all = db_select_all("* FROM class");

foreach ($all as $a)
{
    echo "<h3>".$a["fr_name"]."</h3>";
    echo "<div style='width: 100%;'>";
    $asset = db_select_all("
       *
       FROM class_asset
       WHERE id_class = ".$a["id"]."
       ORDER BY chapter ASC
       ");
    foreach ($asset as $t)
    {
	$x = explode("=", $t["fr_link"])[1];
?>
<div style="display: inline-block;">
    <h4><?=$t["fr_name"]; ?></h4>
    <iframe
	width="560"
	height="315"
	src="https://www.youtube.com/embed/<?=$x; ?>"
	frameborder="0"
	allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
	allowfullscreen>
    </iframe>
</div>
<?php
     }
     echo "</div>";
}

}
?>
