    <tr>
	<td colspan="4" style="text-align: right;">
	    <?=$Dictionnary["CreditTotal"]; ?> :&nbsp;&nbsp;
	</td>
	<!--<td><?=$Grade[round($grade_avg / $cnt)]; ?></td>-->
	<td><?=$credit_sum; ?></td>
	<td><?=$credit_available; ?></td>
    </tr>
    <tr>
	<td colspan="4" style="text-align: right;">
	    <?=$Dictionnary["ECTSEquivalent"]; ?> :&nbsp;&nbsp;
	</td>
	<td><?=sprintf("%d", round($credit_sum / (100 / 20))); ?></td>
	</td>
	<td><?=sprintf("%d", round($credit_available / (100 / 20))); ?></td>
    </tr>
</table>
<br />
<div style="width: 100%; min-height: 200px; border: 1px solid gray; text-align: justify;">
    <b style="position: relative; top: 5px; left: 5px;">
	<?=$Dictionnary["GeneralComment"]; ?>:
    </b><br /><br />
    <p style="padding: 10px 10px 10px 10px;">
	<?php foreach ($user->sublayer as $cycle) { ?>
	    <?=str_replace("\n", "<br />", $cycle->commentaries); ?>
	<?php } ?>
    </p>
</div>
<p style="text-align: right; margin-right: 10%;">
    <?=$Dictionnary["DirectorSignature"]; ?> :
</p>
</div>

