<div class="page">

    <div style="text-align: center; width: 100%; height: 50px; padding-top: 15px; padding-bottom: 15px; background-color: lightgray;">
	<?php
	$schools = [];
	foreach ($user->school as $school)
	{
	    foreach ($first_cycle->school as $sch)
	    {
		if ($school["id_school"] == $sch["id"])
		{
		    $schools[] = array_merge($sch, [
			"picture" => $Configuration->SchoolsDir($school["codename"])."icon.png"
		    ]);
		}
	    }
	}
	?>
	<?php $x = 0; ?>
	<?php foreach ($schools as $sc) { ?>
	    <img
		src="<?=$sc["picture"]; ?>"
		style="width: 100px; height: 100px; position: relative; top: -30px; left: calc(-40% + <?=$x; ?>px - 20px);"
	    />
	    <?php $x += 110; ?>
	<?php } ?>
	<?php $x += 10; ?>
	<p style="width: calc(100% - 200px); position: absolute; left: <?=$x; ?>px; top: 15px; height: calc(100% - 20px); text-align: left;">
	    <?php foreach ($schools as $sc) { ?>
		<b><?=$Dictionnary["School"]; ?> <?=$sc["name"]; ?></b><br />
		<?=str_replace("\n", "<br />", $sc["address"]); ?>
	    <?php } ?>
	</p>
    </div>
    <br />

    <div>
	<div style="width: 50%; float: left;">
	    <div>
		<div style="width: 50%; font-weight: bold; float: left;">
		    <?=$Dictionnary["StudentName"]; ?>:
		</div>
		<div style="width: 50%; float: left;">
		    <?=ucfirst($user->first_name); ?> <?=strtoupper($user->family_name); ?>
		</div>
	    </div>

	    <div>
		<div style="width: 50%; font-weight: bold; float: left;">
		    <?=$Dictionnary["WithdrawnDate"]; ?>:
		</div>
		<div style="width: 50%; float: left;">
		    <?=date("d/m/Y", time()); ?>
		</div>
	    </div>
	</div>

	<div style="width: 50%; float: left;">
	    <div>
		<div style="width: 50%; font-weight: bold; float: left;">
		    <?=$Dictionnary["ProvidedFor"]; ?>:
		</div>
		<div style="width: 50%; float: left; font-size: x-small;">
		    <?php if ($user->first_name) $user->address_name = ucfirst($user->first_name)." ".strtoupper($user->family_name); ?>
		    <?=$user->address_name.($user->address_name != "" ? "<br />" : ""); ?>
		    <?=$user->street_name.($user->street_name != "" ? "<br />" : ""); ?>
		    <?=$user->postal_code; ?>
		    <?=strtoupper($user->city).($user->city != "" ? "<br />" : ""); ?>
		    <?=$user->country; ?>
		</div>
	    </div>
	</div>
    </div>
    <br />
    <br />
    <br />


    <div style="width: 100%; background-color: gray; padding-top: 10px; padding-bottom: 10px;">
	<?=$first_cycle->codename; ?>
	(<?=$Dictionnary["Year"]; ?> <?=floor($first_cycle->cycle / 4) + 1; ?>, <?=$Dictionnary["Cycle"]; ?> <?=$first_cycle->cycle % 4 + 1; ?>)
	<?=date("d/m/Y", date_to_timestamp($first_cycle->first_day)); ?> - <?=date("d/m/Y", date_to_timestamp($first_cycle->first_day) + 12 * 7 * 24 * 60 * 60); ?>
    </div>

    <br />

    <table>
	<tr>
	    <th style="width: 3cm;"><?=$Dictionnary["CodeName"]; ?></th>
	    <!--th><?=$Dictionnary["InstanceCode"]; ?></th-->
	    <th><?=$Dictionnary["Name"]; ?></th>
	    <th><?=$Dictionnary["Commentaries"]; ?></th>
	    <th><?=$Dictionnary["Grade"]; ?></th>
	    <th><?=$Dictionnary["Credits"]; ?></th>
	    <th>
		<?=str_replace(
		    " ", "<br />",
		    $Dictionnary["AvailableCredits"]
		); ?>
	    </th>
	</tr>

	<?php $cnt = 0; ?>
	<?php $grade_avg = 0; ?>
	<?php $credit_sum = 0; ?>
	<?php $credit_available = 0; ?>

	
