<?php
require_once ("is_room_full.php");
require_once ("count_slots.php");

// On récupère les infos
if (file_exists(__DIR__."/handle_parameters.php"))
    require_once (__DIR__."/handle_parameters.php");

if ($activity == NULL)
{
    require_once (__DIR__."/../error_net.php");
    return ;
}

// On traite les demandes a l'aide des infos
if (file_exists(__DIR__."/handle_request.php")
    && isset($_POST["action"]))
require_once (__DIR__."/handle_request.php");

require_once (__DIR__."/../error_net.php");

?>
<!--h2><?=$Dictionnary["Activity"]; ?></h2-->

<?php intercom_handle_request("activity", $activity->id); ?>

<?php
$total_students = $activity->nbr_students;
$total_teams = count($activity->team);
if ($activity->unique_session)
{
    $local_students = $activity->unique_session->nbr_students;
    $local_teams = count($activity->unique_session->team);
}
else
{
    $local_students = 0;
    $local_teams = 0;
}

// Deux panneaux, a gauche et a droite
$left_panel = [$Dictionnary["About"] => __DIR__."/about.php",];
if (count($activity->team) > 0)
    $left_panel[$Dictionnary["RegisteredStudents"]] = __DIR__."/users.php";
if (count($activity->support) > 0)
    $left_panel[$Dictionnary["AssociatedCourseMaterial"]] = __DIR__."/material.php";
if (count($activity->session) > 1)
    $left_panel[$Dictionnary["OtherSessions"]] = __DIR__."/other_sessions.php";
if (isset($activity->user_team["id"]) && $activity->max_team_size > 1)
{
    $left_panel[$Dictionnary["Forum"]] = __DIR__."/forum.php";
    $left_panel[$Dictionnary["WorkSplit"]] = __DIR__."/scrum.php";
}

ob_start();
$cnt = 0;
$work = [];
if (@count(@$activity->user_team["work"]))
    $work = [$activity->user_team];
else if (is_admin())
    $work = $activity->team;
foreach ($work as $wk)
{
    if (!is_admin())
	$tlog = " - ".str_replace(".", "_", $User["codename"]);
    else
	$tlog = " - ".$wk["team_name"]." (".$wk["leader"]["codename"].")";
    foreach ($wk["work"] as $wkx)
    {
	$repo = $wkx["repository"];
	$ret = pathinfo($wkx["repository"], PATHINFO_EXTENSION);
	if ($ret == "")
	    $repo .= "*"; // Retro compat...
	$cnt += display_ressources(
	    $repo,
	    datex("d/m/Y H:i:s", $wkx["pickedup_date"]).$tlog,
	    "",
	    $activity->is_assistant
	);
    }
}
$work = ob_get_contents();
ob_get_clean();
if ($activity->evaluation == NULL && $cnt > 0)
    $left_panel[$Dictionnary["WorkDelivered"]] = __DIR__."/work.php";

$right_panel = [
    $Dictionnary["Subject"] => __DIR__."/subject.php",
];
if (count($activity->medal) > 0)
    $right_panel[$Dictionnary["Medals"]] = __DIR__."/medals.php";

ob_start();
$cnt = 0;
$cnt += display_ressources("./dres/activity/".$activity->template_codename."/".$Language."/ressource/*", "", "", $activity->is_teacher);
$cnt += display_ressources("./dres/activity/".$activity->codename."/".$Language."/ressource/*", "", "", $activity->is_teacher);
$list = ob_get_contents();
ob_get_clean();
if ($cnt > 0)
    $right_panel[$Dictionnary["Ressources"]] = __DIR__."/ressources.php";

$right_panel[$Dictionnary["Intercom"]] = __DIR__."/discussion.php";

if ($activity->unique_session && count($activity->unique_session->slot))
    $right_panel[$Dictionnary["AppointmentSlots"]] = __DIR__."/slots.php";
if ($activity->evaluation != NULL)
    $right_panel[$Dictionnary["Evaluation"]] = __DIR__."/evaluation.php";

$right_panel[$Dictionnary["OpinionOnActivity"]] = __DIR__."/opinion.php";
if ($activity->is_teacher)
    $right_panel[$Dictionnary["Administration"]] = __DIR__."/administration.php";
if ($activity->is_assistant)
    $right_panel[$Dictionnary["Logs"]] = __DIR__."/logs.php";

?>

<style>
 .toplist
 {
     font-size: small;
 }
 .content
 {
 }
 <?php if ($activity->current_wallpaper) { ?>
 .background
 {
     background-size: cover;
     background-position: center center;
 }
 .background .instance_button
 {
     box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.5);
     border: 1px solid black;
 }
 .background h1, .background h2, .background h3, .background h4, .background p
 {
     background-clip: content-box;
 }
 .background .blackened *
 {
     font-weight: bold;
     color: white;
     text-shadow:
	 0px 0px 5px black,
	 0px 0px 5px black,
	 0px 0px 5px black,
	 0px 0px 5px black,
	 0px 0px 5px black
     ;
 }
 .background .blackened input
 {
     color: rgb(200, 143, 26);
     text-shadow:
	 0px 0px 3px black,
	 0px 0px 3px black,
	 0px 0px 3px black,
	 0px 0px 3px black,
	 0px 0px 3px black
     ;
 }
 .leftbackground
 {
     background-image: url("<?=$activity->current_wallpaper; ?>");
 }
 .rightbackground
 {
     /* background-image: url("<?=$activity->current_wallpaper; ?>"); */
 }
 .double_horizontal.background
 {
     /*
     background-image: url("<?=$activity->current_wallpaper; ?>");
     background-position: 0px 30px;
     background-repeat: no-repeat;
     */
 }
 <?php } ?>

</style>

<script>
 var SelectedMedalField = null;

 function SelectThis(but)
 {
     if (SelectedMedalField)
	 SelectedMedalField.style.backgroundColor = "white";
     SelectedMedalField = but;
     SelectedMedalField.style.backgroundColor = "lightgreen";
     var medbuttons = document.getElementsByClassName("medbuttons");
     for (var i = 0; i < medbuttons.length; ++i)
	 medbuttons.item(i).classList.remove("bin");
 }
 
 function AddMedal(name, button)
 {
     if (!SelectedMedalField)
	 return ;
     button = document.getElementById(button);
     let res = SelectedMedalField.value.split(";");
     let newarray = [];
     let fnd = false;

     for (var i = 0; i < res.length; ++i)
     {
	 if (res[i] == name)
	     fnd = true;
	 else
	     newarray.push(res[i]);
     }

     if (fnd == false)
     {
	 if (SelectedMedalField.value != "")
	     SelectedMedalField.value = SelectedMedalField.value + ";";
	 SelectedMedalField.value = SelectedMedalField.value + name;
	 // button.style.backgroundColor = "gray";
	 button.classList.add('bin');
     }
     else
     {
	 SelectedMedalField.value = newarray.join(";");
	 // button.style.backgroundColor = "";
	 button.classList.remove('bin');
     }
 }
</script>

<div
    class="double_horizontal background"
    style="height: 100%;"
>
    <div style="height: 100%;">
	<?php
	tabpanel(
	    $left_panel,
	    $Position.$activity->id."left",
	    $Dictionnary["About"],
	    "toplist",
	    "round_box leftbackground background"
	);
	?>
    </div>
    <div style="height: 100%;">
	<?php
	tabpanel(
	    $right_panel,
	    $Position.$activity->id."right",
	    $Dictionnary["Subject"],
	    "toplist",
	    "round_box"
	);
	?>
    </div>
</div>


