<div style="position: relative; width: 98%; margin-left: 1%; margin-top: 1%; height: 30px;">
    <?php require ("single_team_name.php"); ?>
    <section id="team_presence<?=$cteam["id"]; ?>">
	<?php require ("single_team_presence.php"); ?>
    </section>

    <div style="position: absolute; width: 40%; text-align: right; right: 0px;">
	<?php
	if ($activity->is_assistant)
	{
	    require ("forms/deliveries.php");
	    if ($activity->teamable)
		require ("forms/add_user.phtml");
	    if (count($cteam["user"]) < $activity->min_team_size)
		require ("forms/complete_team.phtml");
	}
	if (($activity->is_assistant || $cteam["leader"]["id"] == $User["id"]) && $activity->teamable)
	    require ("forms/lock_team.phtml");
	
	if ($activity->is_assistant)
	    require ("forms/delete_full_team.phtml");
	else if (!$activity->registered && $cteam["canjoin"] && $cteam["real_members"] < $activity->max_team_size)
	    require ("forms/join_team.phtml");
	?>
    </div>
</div>

<?php if ($activity->teamable) { ?>
    <div style="
		position: relative;
		height: 170px;
		margin: 1%;
		">
	<div id="team_<?=$cteam["id"]; ?>_medal_list"
	     style="
		    position: absolute;
		    left: 0px;
		    width: calc(100% / 2 - 10px);
		    height: 100%;
		    ">
	    <?php $medalteam = true; ?>
	    <?php get_activity_medal_for_team(
		$cteam,
		$activity->reference_activity == -1 ?
		$activity->id :
		$activity->reference_activity
	    ); ?>
	    <?php $medlist = $cteam["medal"]; ?>
	    <?php require ("medal_list.php"); ?>
	</div>

	<?php
	if ($activity->is_assistant)
	    require ("forms/team_comment_medal.phtml");
	else
	{
	?>   
	    <div style="
			width: calc((100% - 170px) / 2 - 10px);
			height: calc(170px);
			position: absolute;
			top: 0px; right: 0px;
			border: 1px solid gray; border-radius: 5px;
			"
	    >
		<?php if (@strlen($cteam["commentaries"]["content"])) { ?>
		    <?=markdown($cteam["commentaries"]["content"], true); ?>
		    <br /><i style="font-size: x-small;">
			<?=$Dictionnary["LastEditFrom"]; ?>:
			<?php $auth = resolve_codename("user", $cteam["commentaries"]["id_user"], "codename", true); ?>
			<?php display_nickname($auth->value); ?>,
			<?=human_date($cteam["commentaries"]["comment_date"]); ?>
		    </i>
		<?php } else { ?>
		    <i><?=$Dictionnary["NoCommentToDisplay"]; ?></i>
		<?php } ?>
	    </div>
	<?php
	}
	?>
    </div>
<?php } ?>

<?php foreach ($cteam["user"] as $usr) { ?>
    <div style="
		position: relative;
		height: 170px;
		margin: 1%;
		">
	<?php require ("team_member.phtml"); ?>
    </div>
<?php } ?>
