<br />
<form method="POST" action="index.php?<?=unrollget(); ?>" enctype="multipart/form-data"
      class="add_formular">
    <input type="hidden" name="action" value="add_asset" />
    <!--input type="hidden" name="MAX_FILE_SIZE" value="<?=1024 * 1024 * 200; ?>" /-->
    <input type="hidden" name="id_class" value="<?=$_GET['a']; ?>" />

    <h2><?=$Dictionnary["AddAFile"]; ?></h2><br />
    <div>
	<input
	    type="text"
	    name="codename"
	    placeholder="<?=$Dictionnary["CodeName"]; ?>"
	    value="<?=try_get($_POST, "codename"); ?>"
	/>
	<input
	    type="number"
	    name="chapter"
	    placeholder="<?=$Dictionnary["Chapter"]; ?>"
	    value="<?=try_get($_POST, "chapter"); ?>"
	/>
	<br /><br />
	<?php forge_language_formular(["name" => "text", "link" => "text", "content" => "file"], $_POST); ?>
	<br />
	<input type="submit" value="&#10003;" />
    </div>
</form>



