<div>
    <h2 class="alignable_blocks"><?=$Dictionnary["Members"]; ?></h2>
    <form
	class="alignable_blocks searchbar"
	method="get"
	onsubmit="return use_search('/api/user', this, 'userlist');"
    >
	<input
	    type="text"
	    id="searchbar"
	    placeholder="<?=$Dictionnary["Search"]; ?>"
	/>
    </form>
</div>

<?php if (is_admin()) { ?>
  <table class="edit_console"><tr><td><div class="fullscreen scrollable" id="userlist">
<?php }?>

<?php foreach (fetch_users() as $user) require ("display_user.phtml"); ?>

<?php if (is_admin()) { ?>
    </div></td><td class="formular_slot">
        <?php require ("add_user.phtml"); ?>
    </td></tr></table>
<?php } ?>
  
