<?php
if (file_exists(__DIR__."/handle_parameters.php"))
    require_once (__DIR__."/handle_parameters.php");
require_once (__DIR__."/../error_net.php");
?>

<div>
    <script>
     function use_search(action, obj)
     {
	 var target = document.getElementById("userlist");
	 var searchbar = document.getElementById("searchbar");

	 if (searchbar.value != "")
	     obj.action = action + "/" + searchbar.value;
	 else
	     obj.action = action;
	 silent_submit(obj, target, null, null, null);
	 return (false);
     }
    </script>
    <h2 class="alignable_blocks"><?=$Dictionnary["Members"]; ?></h2>
    <form
	class="alignable_blocks"
	method="get"
	onsubmit="return use_search('/api/user', this);"
    >
	<input
	    type="text"
	    id="searchbar"
	    placeholder="<?=$Dictionnary["Search"]; ?>"
	/>
    </form>
</div>

<?php if (is_admin()) { ?>
  <table class="edit_console"><tr><td><div class="fullscreen scrollable" id="userlist">
<?php }?>

<?php foreach (fetch_users() as $user) require ("display_user.phtml"); ?>

<?php if (is_admin()) { ?>
    </div></td><td class="formular_slot">
        <?php require ("add_user.phtml"); ?>
    </td></tr></table>
<?php } ?>
  
