CREATE TABLE IF NOT EXISTS `billing_bank_transaction` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `fingerprint` char(64) NOT NULL,
  `operation_date` datetime NOT NULL,
  KEY `operation_date` (`operation_date`),
  `value_date` datetime DEFAULT NULL,
  `label` varchar(512) NOT NULL,
  `amount` int(11) NOT NULL,
  `pointage` varchar(255) NOT NULL DEFAULT '',
  `bank_comment` text DEFAULT NULL,
  `status` enum('pending','matched','ignored') NOT NULL DEFAULT 'pending',
  KEY `status` (`status`),
  `match_type` varchar(32) DEFAULT NULL,
  `match_id` int(11) DEFAULT NULL,
  `id_user` int(11) DEFAULT NULL,
  KEY `id_user` (`id_user`),
  `id_organization` int(11) DEFAULT NULL,
  KEY `id_organization` (`id_organization`),
  `id_billing_entry` int(11) DEFAULT NULL,
  KEY `id_billing_entry` (`id_billing_entry`),
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  UNIQUE KEY `billing_bank_transaction_unique` (`id_school`, `fingerprint`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
