CREATE TABLE `user_money_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_user` int(11) NOT NULL,
  KEY `id_user` (`id_user`),
  `amount` int(11) NOT NULL,
  `source_type` varchar(64) NOT NULL,
  `source_key` varchar(255) NOT NULL,
  UNIQUE KEY `user_money_unique_source` (`id_user`, `source_type`, `source_key`),
  `id_activity` int(11) DEFAULT NULL,
  KEY `id_activity` (`id_activity`),
  `id_medal` int(11) DEFAULT NULL,
  KEY `id_medal` (`id_medal`),
  `id_team` int(11) DEFAULT NULL,
  KEY `id_team` (`id_team`),
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `comment` text DEFAULT NULL,
  `insert_date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `billing_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `tariff_year` int(11) NOT NULL DEFAULT 0,
  KEY `tariff_year` (`tariff_year`),
  `name` varchar(255) NOT NULL,
  `amount_once` int(11) NOT NULL DEFAULT 0,
  `amount_twice` int(11) NOT NULL DEFAULT 0,
  `amount_four` int(11) NOT NULL DEFAULT 0,
  `amount_twelve` int(11) NOT NULL DEFAULT 0,
  `registration_fee` int(11) NOT NULL DEFAULT 0,
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `billing_entry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_user` int(11) NOT NULL,
  KEY `id_user` (`id_user`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `id_template` int(11) DEFAULT NULL,
  KEY `id_template` (`id_template`),
  `label` varchar(255) NOT NULL,
  `amount` int(11) NOT NULL,
  `entry_type` varchar(32) NOT NULL DEFAULT 'tuition',
  KEY `entry_type` (`entry_type`),
  `due_date` datetime NOT NULL,
  KEY `due_date` (`due_date`),
  `invoice_reference` varchar(128) DEFAULT NULL,
  UNIQUE KEY `billing_entry_invoice_reference_unique` (`invoice_reference`),
  `invoice_filename` varchar(255) DEFAULT NULL,
  `sent_date` datetime DEFAULT NULL,
  `paid_date` datetime DEFAULT NULL,
  KEY `paid_date` (`paid_date`),
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `billing_payment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_user` int(11) NOT NULL,
  KEY `id_user` (`id_user`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `amount` int(11) NOT NULL,
  `payment_date` datetime NOT NULL,
  KEY `payment_date` (`payment_date`),
  `transfer_reference` varchar(255) DEFAULT NULL,
  KEY `transfer_reference` (`transfer_reference`),
  `comment` text DEFAULT NULL,
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
