CREATE TABLE `user_money_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_user` int(11) NOT NULL,
  KEY `id_user` (`id_user`),
  `amount` int(11) NOT NULL,
  `source_type` varchar(64) NOT NULL,
  `source_key` varchar(255) NOT NULL,
  UNIQUE KEY `user_money_unique_source` (`id_user`, `source_type`, `source_key`),
  `id_activity` int(11) DEFAULT NULL,
  KEY `id_activity` (`id_activity`),
  `id_medal` int(11) DEFAULT NULL,
  KEY `id_medal` (`id_medal`),
  `id_team` int(11) DEFAULT NULL,
  KEY `id_team` (`id_team`),
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `comment` text DEFAULT NULL,
  `insert_date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `billing_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `buyer_organization_id` int(11) DEFAULT NULL,
  KEY `buyer_organization_id` (`buyer_organization_id`),
  `buyer_routing_code` varchar(255) NOT NULL DEFAULT '',
  `tariff_year` int(11) NOT NULL DEFAULT 0,
  KEY `tariff_year` (`tariff_year`),
  `name` varchar(255) NOT NULL,
  `invoice_type` varchar(32) NOT NULL DEFAULT 'school',
  KEY `invoice_type` (`invoice_type`),
  `amount_once` int(11) NOT NULL DEFAULT 0,
  `amount_twice` int(11) NOT NULL DEFAULT 0,
  `amount_four` int(11) NOT NULL DEFAULT 0,
  `amount_twelve` int(11) NOT NULL DEFAULT 0,
  `registration_fee` int(11) NOT NULL DEFAULT 0,
  `vat_rate` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `billing_entry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_user` int(11) DEFAULT NULL,
  KEY `id_user` (`id_user`),
  `id_organization` int(11) DEFAULT NULL,
  KEY `id_organization` (`id_organization`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `buyer_routing_code` varchar(255) NOT NULL DEFAULT '',
  `id_template` int(11) DEFAULT NULL,
  KEY `id_template` (`id_template`),
  `label` varchar(255) NOT NULL,
  `amount` int(11) NOT NULL,
  `amount_ht` int(11) NOT NULL DEFAULT 0,
  `entry_type` varchar(32) NOT NULL DEFAULT 'tuition',
  KEY `entry_type` (`entry_type`),
  `related_entry_id` int(11) DEFAULT NULL,
  KEY `related_entry_id` (`related_entry_id`),
  `invoice_type` varchar(32) NOT NULL DEFAULT 'school',
  KEY `invoice_type` (`invoice_type`),
  `vat_rate` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `due_date` datetime NOT NULL,
  KEY `due_date` (`due_date`),
  `invoice_reference` varchar(128) DEFAULT NULL,
  `deleted_invoice_reference` varchar(128) DEFAULT NULL,
  UNIQUE KEY `billing_entry_invoice_reference_unique` (`invoice_reference`),
  `invoice_filename` varchar(255) DEFAULT NULL,
  `sent_date` datetime DEFAULT NULL,
  `paid_date` datetime DEFAULT NULL,
  KEY `paid_date` (`paid_date`),
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `billing_payment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_user` int(11) DEFAULT NULL,
  KEY `id_user` (`id_user`),
  `id_organization` int(11) DEFAULT NULL,
  KEY `id_organization` (`id_organization`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `amount` int(11) NOT NULL,
  `payment_date` datetime NOT NULL,
  KEY `payment_date` (`payment_date`),
  `transfer_reference` varchar(255) DEFAULT NULL,
  KEY `transfer_reference` (`transfer_reference`),
  `comment` text DEFAULT NULL,
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `organization_account_entry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `id_organization` int(11) NOT NULL,
  KEY `id_organization` (`id_organization`),
  `movement_type` enum('debit','credit') NOT NULL,
  KEY `movement_type` (`movement_type`),
  `amount` int(11) NOT NULL,
  `movement_date` datetime NOT NULL,
  KEY `movement_date` (`movement_date`),
  `label` varchar(255) NOT NULL,
  `reference` varchar(255) NOT NULL DEFAULT '',
  `comment` text DEFAULT NULL,
  `document_name` varchar(255) DEFAULT NULL,
  `document_path` varchar(512) DEFAULT NULL,
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `billing_bank_transaction` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `id_school` int(11) NOT NULL,
  KEY `id_school` (`id_school`),
  `fingerprint` char(64) NOT NULL,
  `operation_date` datetime NOT NULL,
  KEY `operation_date` (`operation_date`),
  `value_date` datetime DEFAULT NULL,
  `label` varchar(512) NOT NULL,
  `amount` int(11) NOT NULL,
  `pointage` varchar(255) NOT NULL DEFAULT '',
  `bank_comment` text DEFAULT NULL,
  `status` enum('pending','matched','ignored') NOT NULL DEFAULT 'pending',
  KEY `status` (`status`),
  `match_type` varchar(32) DEFAULT NULL,
  `match_id` int(11) DEFAULT NULL,
  `id_user` int(11) DEFAULT NULL,
  KEY `id_user` (`id_user`),
  `id_organization` int(11) DEFAULT NULL,
  KEY `id_organization` (`id_organization`),
  `id_billing_entry` int(11) DEFAULT NULL,
  KEY `id_billing_entry` (`id_billing_entry`),
  `id_actor` int(11) DEFAULT NULL,
  KEY `id_actor` (`id_actor`),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  UNIQUE KEY `billing_bank_transaction_unique` (`id_school`, `fingerprint`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `billing_electronic_document` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_school` int(11) NOT NULL,
  `direction` varchar(16) NOT NULL DEFAULT 'outgoing',
  `flow_type` varchar(32) NOT NULL DEFAULT 'ereporting_transaction',
  `document_type` varchar(32) NOT NULL DEFAULT 'invoice',
  `source_type` varchar(64) DEFAULT NULL,
  `source_id` int(11) DEFAULT NULL,
  `local_reference` varchar(128) NOT NULL DEFAULT '',
  `issue_date` datetime DEFAULT NULL,
  `due_date` datetime DEFAULT NULL,
  `currency` char(3) NOT NULL DEFAULT 'EUR',
  `seller_organization_id` int(11) DEFAULT NULL,
  `buyer_organization_id` int(11) DEFAULT NULL,
  `buyer_user_id` int(11) DEFAULT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'prepared',
  `provider_key` varchar(64) DEFAULT NULL,
  `provider_document_id` varchar(255) DEFAULT NULL,
  `transmission_id` varchar(255) DEFAULT NULL,
  `transport_attempts` int(11) NOT NULL DEFAULT 0,
  `last_transport_attempt_at` datetime DEFAULT NULL,
  `next_transport_retry_at` datetime DEFAULT NULL,
  `last_transport_error` varchar(255) DEFAULT NULL,
  `review_note` text DEFAULT NULL,
  `review_closed_at` datetime DEFAULT NULL,
  `regulatory_validation_status` varchar(32) DEFAULT NULL,
  `regulatory_validation_at` datetime DEFAULT NULL,
  `regulatory_validation_details` longtext DEFAULT NULL,
  `canonical_json` longtext NOT NULL,
  `canonical_sha256` char(64) NOT NULL,
  `raw_format` varchar(32) DEFAULT NULL,
  `raw_filename` varchar(255) DEFAULT NULL,
  `raw_path` varchar(512) DEFAULT NULL,
  `id_actor` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billing_electronic_document_source` (`source_type`, `source_id`),
  KEY `id_school` (`id_school`),
  KEY `direction` (`direction`),
  KEY `flow_type` (`flow_type`),
  KEY `status` (`status`),
  KEY `seller_organization_id` (`seller_organization_id`),
  KEY `buyer_organization_id` (`buyer_organization_id`),
  KEY `buyer_user_id` (`buyer_user_id`),
  KEY `provider_document_id` (`provider_document_id`),
  KEY `next_transport_retry_at` (`next_transport_retry_at`),
  KEY `regulatory_validation_status` (`regulatory_validation_status`),
  UNIQUE KEY `billing_electronic_document_remote` (`id_school`, `direction`, `provider_key`, `provider_document_id`),
  KEY `id_actor` (`id_actor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `billing_electronic_event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_document` int(11) NOT NULL,
  `event_code` varchar(64) NOT NULL,
  `event_source` varchar(32) NOT NULL DEFAULT 'local',
  `event_date` datetime NOT NULL DEFAULT current_timestamp(),
  `external_id` varchar(255) NOT NULL DEFAULT '',
  `payload` longtext DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `id_document` (`id_document`),
  KEY `event_code` (`event_code`),
  KEY `event_date` (`event_date`),
  KEY `external_id` (`external_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
