CREATE TABLE IF NOT EXISTS `billing_electronic_document` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_school` int(11) NOT NULL,
  `direction` varchar(16) NOT NULL DEFAULT 'outgoing',
  `flow_type` varchar(32) NOT NULL DEFAULT 'ereporting_transaction',
  `document_type` varchar(32) NOT NULL DEFAULT 'invoice',
  `source_type` varchar(64) DEFAULT NULL,
  `source_id` int(11) DEFAULT NULL,
  `local_reference` varchar(128) NOT NULL DEFAULT '',
  `issue_date` datetime DEFAULT NULL,
  `due_date` datetime DEFAULT NULL,
  `currency` char(3) NOT NULL DEFAULT 'EUR',
  `seller_organization_id` int(11) DEFAULT NULL,
  `buyer_organization_id` int(11) DEFAULT NULL,
  `buyer_user_id` int(11) DEFAULT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'prepared',
  `provider_key` varchar(64) DEFAULT NULL,
  `provider_document_id` varchar(255) DEFAULT NULL,
  `transmission_id` varchar(255) DEFAULT NULL,
  `transport_attempts` int(11) NOT NULL DEFAULT 0,
  `last_transport_attempt_at` datetime DEFAULT NULL,
  `next_transport_retry_at` datetime DEFAULT NULL,
  `last_transport_error` varchar(255) DEFAULT NULL,
  `review_note` text DEFAULT NULL,
  `review_closed_at` datetime DEFAULT NULL,
  `regulatory_validation_status` varchar(32) DEFAULT NULL,
  `regulatory_validation_at` datetime DEFAULT NULL,
  `regulatory_validation_details` longtext DEFAULT NULL,
  `canonical_json` longtext NOT NULL,
  `canonical_sha256` char(64) NOT NULL,
  `raw_format` varchar(32) DEFAULT NULL,
  `raw_filename` varchar(255) DEFAULT NULL,
  `raw_path` varchar(512) DEFAULT NULL,
  `id_actor` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `billing_electronic_document_source` (`source_type`, `source_id`),
  KEY `id_school` (`id_school`),
  KEY `direction` (`direction`),
  KEY `flow_type` (`flow_type`),
  KEY `status` (`status`),
  KEY `seller_organization_id` (`seller_organization_id`),
  KEY `buyer_organization_id` (`buyer_organization_id`),
  KEY `buyer_user_id` (`buyer_user_id`),
  KEY `provider_document_id` (`provider_document_id`),
  KEY `next_transport_retry_at` (`next_transport_retry_at`),
  KEY `regulatory_validation_status` (`regulatory_validation_status`),
  UNIQUE KEY `billing_electronic_document_remote` (`id_school`, `direction`, `provider_key`, `provider_document_id`),
  KEY `id_actor` (`id_actor`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `billing_electronic_event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_document` int(11) NOT NULL,
  `event_code` varchar(64) NOT NULL,
  `event_source` varchar(32) NOT NULL DEFAULT 'local',
  `event_date` datetime NOT NULL DEFAULT current_timestamp(),
  `external_id` varchar(255) NOT NULL DEFAULT '',
  `payload` longtext DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `id_document` (`id_document`),
  KEY `event_code` (`event_code`),
  KEY `event_date` (`event_date`),
  KEY `external_id` (`external_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
