<?php
if (!isset($cycle_stack))
    $cycle_stack = $user->merged_sublayers;
$curcycle = ($cyc = $cycle_stack[array_key_first($cycle_stack)])->matters;
$merged_cycles = $cyc->cycles;

$cursuses = [];
foreach ($cyc->cursus as $cs)
    if (trim($cs) != "" )
	$cursuses[] = trim($cs);

$min_credit = 0;
$max_credit = 0;
$cur_credit = 0;
foreach ($curcycle as $module) {
    $min_credit += $module->credit_d;
    $max_credit += $module->credit_a;
    $cur_credit += $module->get_credit();
}
?>
<style>
 .profile_matter td, .profile_matter th
 {
     text-align: center;
     font-size: small;
 }
 .profile_activity td, .profile_activity th, .profile_activity a
 {
     text-decoration: none;
     color: black;
     text-align: center;
     font-size: x-small;
 }
 .profile_activity th
 {
     font-size: small;
 }

</style>
<table><tr><td>
    <p style="text-align: left; font-size: small; padding-left: 20px">
	<br />
	<b><?=$Dictionnary["Credits"]."</b> : $cur_credit / ($min_credit - $max_credit)"; ?>
	    <?php $first_time = true; ?>
	    <?php $cursus = ""; ?>
	    <?php $cursuses = array_filter($cursuses); ?>
	    <?php foreach ($cursuses as $cursus) { ?>
		<?php if ($first_time) { ?>
		    <br /><b><?=$Dictionnary["Curriculum"]; ?></b> :
		    <?php $first_time = false; ?>
		<?php } ?>
		<?=isset($Dictionnary[$cursus]) ? $Dictionnary[$cursus] : $cursus; ?>
	    <?php } ?>
	    <br /><br />
    </p>
</td><td>
    
</td><td>
    <?php if (is_admin()) { ?>
	<?php
	$modules = [];
	foreach ($curcycle as $module)
	    $modules[] = $module->id;
	?>
	<form method="post" action="<?=unrollurl(["silent" => 1, "modules" => implode(",", $modules), "id_cycle" => implode(",", $merged_cycles)]); ?>" target="_blank">
	    <input
		type="submit"
		value="<?=$Dictionnary["GenerateReportCard"]; ?>"
		style="width: 100%; height: 30px;"
	    />
	</form>
    <?php } ?>
</td></tr></table>
<table class="profile_matter" style="width: 100%; border-top: 1px solid black;"><tr><th style="width: 20%;">
    <?=$Dictionnary["Module"]; ?>
</th><th style="width: 10%;">
    <?=$Dictionnary["AvailableCredits"]; ?>
</th><th style="width: 10%;">
    <?=$Dictionnary["AcquiredCredit"]; ?>
</th><th style="width: 70px;">
    <?=$Dictionnary["Grade"]; ?>
</th><th>
    <?=$Dictionnary["Medals"]; ?>
</th></tr>

<?php
$lighter = "255, 255, 255, 0.33";
$darker = "0, 0, 0, 0.33";
$neutral = "255, 255, 255, 0.0";
?>
<?php $alpha = 1; ?>
<?php foreach ($curcycle as $module) { ?>
    <?php if ($module->hidden) continue ; ?>
    <?php $alpha += 1; ?>
    <tr style="background-color: rgba(<?=$alpha % 2 ? $lighter : $neutral; ?>); border-top: 1px solid black;"><td>
	<a href="index.php?p=ModulesMenu&amp;a=<?=$module->id; ?>">
	    <h5><?=strlen(@$module->name) ? $module->name : $module->codename; ?></h5>
	</a>
    </td><td style="font-size: x-small;">
	<?=sprintf("%02d", $module->credit_d); ?>
	<?=sprintf("%02d", $module->credit_c); ?>
	<?=sprintf("%02d", $module->credit_b); ?>
	<?=sprintf("%02d", $module->credit_a); ?>
    </td><td style="font-size: x-small;">
	<?=$module->get_credit(); ?>
    </td><td style="font-size: x-small;">
	<div
	    <?php
	    $grade = [
		"empty", "grade_e", "grade_d", "grade_c", "grade_b", "grade_a", "grade_a"
	    ];
	    if ($module->done_date != NULL && date_to_timestamp($module->done_date) < now())
		$func = $grade[$module->grade + 1];
	    else
		$func = "";
	    ?>
	    class="medal_box_picture"
	    style="
		   margin-left: 10px; margin-right: 10px;
		   background-position: center center;
		   background-image: url('/genicon.php?function=<?=$func; ?>');
		   width: 50px !important;
		   height: 50px !important;
		   border-radius: 50px;
		   border: 2px black solid;
		   "
	></div>
    </td>
    <?php if ($module->validation != FullActivity::GRADE_VALIDATION) { ?>
	<td rowspan="2">
	    <div class="full_size_table" style="overflow-y: auto; height: 250px; scrollbar-width: 5px;">
		<?php foreach (sort_by_medal_grade($module->medal, true) as $medal) { ?>
		    <?php
		    if (!isset($medal["eliminatory"]) &&
			($medal["type"] != 0 || ($medal["role"] == 0 && $medal["success"] == 0))
		    )
		    continue ;
		    if (isset($medal["module_level"])) echo "level";
		    ?>
		    <div
			title="<?=medal_tooltip($medal); ?>"
			       class="medal_box_picture"
			style="
			       position: relative;
			       display: inline-block; margin-left: 5px; margin-right: 5px; margin-top: 2px;
			       background-image: url('<?=$medal["icon"]; ?>');
			       <?php if (strstr($medal["command"], " sband ") !== false) { ?>
			       width: 46px !important;
			       height: 46px !important;
			       border-radius: 23px;
			       border: 2px black solid;
			       <?php } else { ?>
			       width: 50px !important;
			       height: 50px !important;
			       <?php } ?>
			       <?php if ($medal["success"] == 0 && $medal["type"] == 0) { ?>
			         <?php if ($medal["failure"] > 0) { ?>
			             filter: grayscale(1);
			             opacity: 0.5;
				   <?php } else { ?>
			             opacity: 0.5;
				 <?php } ?>
			       <?php } ?>
			       "
		    >
			<?php if ($medal["module_medal"] && $module->validation == FullActivity::RANK_VALIDATION && $medal["role"] != 0) { ?>
			    <img
				src="res/grade_<?=["d", "c", "b", "a", "a"][$medal["role"] - 1]; ?>.png"
				style="
				     position: absolute;
				     <?php if (strstr($medal["command"], " sband ") !== false) { ?>
				     top: -2px;
				     <?php } else { ?>
				     top: 0px;
				     <?php } ?>
				     right: -10px;
				     width: 20px;
				     height: 20px;
				     "
			    />
			<?php } ?>
			<?php if ($medal["local"]) { ?>
			    <img
				src="res/local.png"
				style="position: absolute; bottom: 0px; right: -10px; width: 20px; height: 20px;"
			    />
			<?php } ?>
			<?php if ($medal["success"] == 0 && $medal["failure"] > 0 && $medal["type"] == 0) { ?>
			    <img
				src="res/cross.png"
				style="position: absolute; bottom: 0px; left: -10px; width: 30px; height: 30px;"
			    />
			<?php } ?>
		    </div>
		<?php } ?>
	    </div>
	</td>
    <?php } else { ?>
	<td></td>
    <?php } ?>
    </tr>
    <tr>
	<?php if ($module->validation != FullActivity::GRADE_VALIDATION) { ?>
	    <td colspan="4">
	<?php } else { ?>
	    <td colspan="5">
	<?php } ?>
	    <?php require ("progress.php"); ?>
	</td>
    </tr>
    <?php if (count($module->sublayer)) { ?>
	<tr style="background-color: rgba(<?=$darker; ?>);"><td colspan="5">
	    <table style="width: 100%;" class="profile_activity">
		<tr><th>
		    <?=$Dictionnary["Activity"]; ?>
		</th><th>
		    <?=$Dictionnary["Type"]; ?>
		</th><th>
		    <?=$Dictionnary["DoneDate"]; ?>
		</th><th>
		    <?=$Dictionnary["Medals"]; ?>
		</th><th>
		    <?=$Dictionnary["Commentaries"]; ?>
		</th><th>
		    <?=$Dictionnary["Status"]; ?>
		</th><th>
		    <?=$Dictionnary["DeliveredWork"]; ?>
		</th></tr>
		<?php $beta = 0; ?>
		<?php foreach ($module->sublayer as $activity) { ?>
		    <?php $beta += 1; ?>
		    <tr style="background-color: rgba(<?=$beta % 2 ? $lighter : $neutral; ?>);"><td>
			<a href="index.php?p=ActivityMenu&amp;a=<?=$activity->id; ?>&amp;<?=$activity->id_session; ?>">
			    <?=$activity->name ?: $activity->codename; ?>
			</a>
		    </td><td>
			<?php if ($activity->type != -1) { ?>
			    <?=$Dictionnary[$ActivityType[$activity->type]["codename"]]; ?>
			<?php } else { ?>
			    /
			<?php } ?>
		    </td><td>
			<?php ($sess = new FullActivity)->build($activity->id, false, true, $activity->id_session); ?>
			<?php if ($activity->id_session != -1 && $sess->type_type == 2) { ?>
			    <?php if (isset($sess->unique_session->end_date)) { ?>
				<?=human_date($sess->unique_session->end_date); ?>
			    <?php } ?>
			<?php } else { ?>
			    <?=human_date($activity->pickup_date); ?>
			<?php } ?>
		    </td><td>
			<?php foreach ($activity->medal as $med) { ?>
			    <span
				<?php if ($med["success"] > 0) { ?>
				    style="font-weight: bold;"
				<?php } else { ?>
				    style="color: gray;"
				<?php } ?>
			    >
				<?=$med["codename"]; ?><?php if ($med["local"]) { ?>(L)<?php } ?>
			    </span>
			<?php } ?>
		    </td><td>

		    </td><td>
			<?php if ($activity->registered == false) { ?>
			    <?=$Dictionnary["NotSubscribed"]; ?>
			<?php } else if ($activity->present->cumulated) { ?>
			    <?=$Dictionnary["Present"]; ?>
			<?php } else if ($activity->late->cumulated) { ?>
			    <?=$Dictionnary["Late"]; ?>
			<?php } else if ($activity->missing->cumulated) { ?>
			    <?=$Dictionnary["Missing"]; ?>
			<?php } else { ?>
			    <?=$Dictionnary["SingleSubscribed"]; ?>
			<?php } ?>
		    </td><td>
			/
		    </td></tr>
		<?php } ?>
	    </table>
	    <br />
	</td></tr>
    <?php } ?>
<?php } ?>
</table>

<?php
array_shift($cycle_stack);
