<?php $language = ""; ?>
<?php if (user_storage_can_write_something($user->id)) { ?>
    <?php $js = "silent_submit(this, 'file_browser');"; ?>
    <form
	method="post"
	onsubmit="return <?=$js; ?>;"
	action="/api/user/<?=$user->id; ?>/file"
    >
	<label for="file"><?=$Dictionnary["File"]; ?></label><br />
	<input id="path2" type="hidden" name="path" value="" />
	<input
	    type="file"
		  name="file"
		  multiple="true"
		  onchange="document.getElementById('path2').value = document.getElementById('pathfile_browser').value; <?=$js; ?>"
	/>
    </form>
<?php } ?>

<?php
$type = "file";
$page = "user";
$id = $user->id;
$path = user_storage_default_browse_space((int)$user->id);
$target = $Configuration->UsersDir($user->codename).$path."/";
require ("./tools/template/path_browser.phtml");

