<?php
$user = $User;
?>

<style>
 table, td
 {
     border: 1px black solid;
 }
</style>

<table class="full_size_table">
    <tr><td>
	<table class="full_size_table"><tr><td style="width: 300px; vertical-align: top;">
	    <p style="text-align: center;">
		<b style="font-size: xx-large;"><?php display_nickname($user, false); ?></b><br />
		<?php display_avatar($user); ?>
	    </p>
	    <table class="uservalues">
		<tr><td><b><?=$Dictionnary["CodeName"]; ?></b>:</td><td><?=$user["codename"]; ?></td></tr>
		<tr><td><b><?=$Dictionnary["FirstName"]; ?></b>:</td><td><?=$user["first_name"]; ?></td></tr>
		<tr><td><b><?=$Dictionnary["FamilyName"]; ?></b>:</td><td><?=$user["family_name"]; ?></td></tr>
		<tr><td><b><?=$Dictionnary["BirthDate"]; ?></b>:</td><td><?=$user["birth_date"] ? human_date($user["birth_date"], true) : ""; ?></td></tr>
		<tr><td><b><?=$Dictionnary["Phone"]; ?></b>:</td><td><?=$user["phone"]; ?></td></tr>
		<tr><td><b><?=$Dictionnary["Address"]; ?></b>:</td><td>
		    <input
			readonly
			disabled="disabled"
			style="width: 100%;"
			type="text"
			value="<?=$user["address_name"]; ?> <?=$user["street_name"]; ?> <?=$user["postal_code"]; ?> <?=$user["city"]; ?> <?=$user["country"]; ?>"
		    />
		</td></tr>
		<tr><td><b><?=$Dictionnary["MemberSince"]; ?></b>:</td><td><?=human_date($user["registration_date"], true); ?></td></tr>
	    </table>
	</td><td>
	    <table class="full_size_table">
		<?php if (is_admin() || $user["id"] == $User["id"]) { ?>
		    <tr><td>
			Fichiers associés au compte (Mettre un browser ici)
		    </td></tr>
		<?php } ?>
		<tr><td>
		    Médailles personnelles
		</td></tr>
	    </table>
	</td></tr></table>
    </td><td>
	Score
    </td></tr><tr>
	<td
	    style="height: 50%; background-image: url('/pages/profile/stats.php?w=960&amp;h=400&amp;e=<?=now(); ?>&amp;s<?=now() - 7 * 24 * 60 * 60; ?>'); background-size: 100% 100%;"
	>
	    <img src="" />
	</td>
	<td>
	<?php
	$panel = [
	    $Dictionnary["AuthorizedFunctions"] => __DIR__."/authorized_functions.phtml",
	    $Dictionnary["ManagedActivities"] => __DIR__."/managed_activities.phtml",
	    $Dictionnary["Intercom"] => __DIR__."/intercom.phtml",
	];
	tabpanel($panel, $Position.$user["id"], $Dictionnary["Profile"]);
	?>	
    </td></tr>
</table>

