<?php foreach ($user->group as $lab) { ?>
    <?php $icon = $Configuration->GroupsDir($lab["codename"])."avatar.png"; ?>
    <div
	onclick="document.location='index.php?p=LaboratoryMenu&amp;a=<?=$lab["id"]; ?>';"
	style="
		 position: relative;
		 margin: 20px 20px 20px 20px;
		 border-radius: 20px;
		 display: inline-block;
		 width: 200px;
		 height: 200px;
		 background-size: contain;
		 background-color: rgba(255, 255, 255, 0.5);
		 background-image: url('<?=file_exists($icon) ? $icon : "res/no_avatar_lab.png"; ?>');
		 "
    >
	<?php if (!file_exists($icon)) { ?>
	    <p style="
		      position: absolute;
		      vertical-align: middle;
		      bottom: 40%;
		      width: calc(100% - 80px);
		      text-align: center;
		      padding-left: 40px;
		      padding-right: 40px;
		      "
	    >
		<?=$lab["name"]; ?>
	    </p>
	<?php } ?>
    </div>
<?php } ?>
