<?php foreach ($user->school as $school) { ?>
    <?php $icon = $Configuration->SchoolsDir($school["codename"])."icon.png"; ?>
    <div
	onclick="document.location='index.php?p=SchoolMenu&amp;a=<?=$school["id"]; ?>"
	class="school_profile_icon"
	style="background-image: url('<?=file_exists($icon) ? $icon : "res/no_avatar_lab.png"; ?>');"
    >
	<?php if (!file_exists($icon)) { ?>
	    <p>
		<?=$school["name"]; ?>
	    </p>
	<?php } ?>
    </div>
<?php } ?>
<?php
foreach ($user->medals as $medal) { ?>
    <img
	src="/genicon.php?function=<?=$medal["codename"]; ?>&amp;shape=sband"
	alt="<?=$medal["name"]; ?>"
	width="200"
	height="200"
	style="
	     display: inline-block;
	     padding: 0;
	     margin: 20px 20px 20px 20px;
	     border-radius: 20px;
	     "
	onclick="document.location = 'index.php?p=MedalsMenu&amp;a=<?=$medal["id"]; ?>'";
    />
<?php } ?>


