<?php
$start = $_GET["s"];
$end = $_GET["e"];
$_GET["lm"] = "m";

$start = db_form_date($start, true);
$end = db_form_date($end, true);

$query = db_select_all("
  declaration_date, present, begin_date, session.id_activity, team.id_session
  FROM team
  LEFT JOIN session ON session.id = team.id_session AND session.id_activity != -1 AND session.deleted IS NULL
  LEFT JOIN user_team ON team.id = user_team.id_team
  WHERE user_team.id_user = {$user->id}
  AND session.begin_date >= '$start' AND session.begin_date <= '$end'
");

$_GET["d"] = [];
$_GET["d"]["presence"] = [];
$_GET["d"]["late"] = [];
$_GET["d"]["mispresence"] = [];

foreach ($query as $p)
{
    if (!strlen(@$p["declaration_date"]))
	$p["declaration_date"] = $p["begin_date"];
    $d = date_to_timestamp($p["declaration_date"]) / 60 / 60 / 24;
    if ($p["present"] == 1)
    {
	if (!isset($_GET["d"]["presence"][$d]))
	    $_GET["d"]["presence"][$d] = 0;
	$_GET["d"]["presence"][$d] += 1;
    }
    else if ($p["present"] == -1)
    {
	if (!isset($_GET["d"]["late"][$d]))
	    $_GET["d"]["late"][$d] = 0;
	$_GET["d"]["late"][$d] += 1;
    }
    else if ($p["present"] == -2)
    {
	if (!isset($_GET["d"]["mispresence"][$d]))
	    $_GET["d"]["mispresence"][$d] = 0;
	$_GET["d"]["mispresence"][$d] += 1;
    }
}

$_GET["d"] = json_encode($_GET["d"], JSON_UNESCAPED_SLASHES);
$_GET["d"] = base64_encode($_GET["d"]);
$params = [];
foreach ($_GET as $gk => $gv)
    $params[] = "$gk=$gv";
$params = implode("&amp;", $params);
?>
<div class="statsin" style="background-image: url(/tools/profile_stats.php?<?=$params; ?>);"></div>
