<div style="width: 100%; background-color: gray;">
    <br />
    <?=$cycle->codename; ?>
    (<?=$Dictionnary["Year"]; ?> <?=floor($cycle->cycle / 4) + 1; ?>, <?=$Dictionnary["Cycle"]; ?> <?=$cycle->cycle % 4 + 1; ?>)
    <?=date("d/m/Y", date_to_timestamp($cycle->first_day)); ?> - <?=date("d/m/Y", date_to_timestamp($cycle->first_day) + 12 * 7 * 24 * 60 * 60); ?>
    <br />
    <br />
</div>

<br />
<br />

<table>
    <tr>
	<th style="width: 3cm;"><?=$Dictionnary["CodeName"]; ?></th>
	<!--th><?=$Dictionnary["InstanceCode"]; ?></th-->
	<th><?=$Dictionnary["Name"]; ?></th>
	<th><?=$Dictionnary["Commentaries"]; ?></th>
	<th><?=$Dictionnary["Grade"]; ?></th>
	<th><?=$Dictionnary["Credits"]; ?></th>
    </tr>

    <?php $cnt = 0; ?>
    <?php $grade_avg = 0; ?>
    <?php $credit_sum = 0; ?>
    <?php $credit_available = 0; ?>
    <?php foreach ($cycle->sublayer as $module) { ?>
    <?php if ($module->credit == 0) continue ; ?>
    <tr>
	<td>
	    <?php $x = explode("_", $module->codename); ?>
	    <?=$x[0]; ?>
	</td>
	<!--td>
	     <?=$x[1]; ?>
	     </td-->
	<td>
	    <?=$module->name; ?>
	</td>
	<td>
	    <?php if ($module->commentaries) { ?>
	    <p>
		<?=$module->commentaries; ?>
	    </p>
	    <?php } ?>
	    <div style="column-count: 2; font-size: xx-small;">
		<!--
		<?=$Dictionnary["Presence"]; ?>: <?=$module->present; ?><br />
		<?=$Dictionnary["Late"]; ?>: <?=$module->late; ?>
		(<?=$Dictionnary["CumulatedLate"]; ?> <?=$cycle->cumulated_late->cumulated / 60 / 60; ?>h<?=($cycle->cumulated_late->cumulated / 60) % 60; ?>m)<br />
		<?=$Dictionnary["Missing"]; ?>: <?=$module->missing; ?>
		<?=$Dictionnary["DeliveredWork"]; ?>: <?=$module->work->cumulated; ?><br />
		<?=$Dictionnary["NoWork"]; ?>: <?=$module->nowork->cumulated; ?>
		-->
	    </div>
	</td>
	<td><?=$Grade[$module->grade]; ?></td>
	<td>/<!--<?=sprintf("% 2d", $module->acquired_credit); ?>/<?=sprintf("% 2d", $module->credit); ?>--></td>
    </tr>
    <?php $grade_avg += $module->grade * $module->credit; ?>
    <?php $credit_sum += $module->acquired_credit; ?>
    <?php $credit_available += $module->credit; ?>
    <?php $cnt += $module->credit; ?>
    <?php } ?>

    <!--tr>
	<td colspan="3"></td>
	<td>
	    <?=$Grade[round($grade_avg / $cnt)]; ?>
	</td>
	<td>
	    <?=sprintf("% 2d", $credit_sum); ?>/<?=sprintf("% 2d", $credit_available); ?>
	</td>
    </tr-->
</table>
<br />
<div style="width: 100%; min-height: 100px; border: 1px solid gray; text-align: left;">
    <b><?=$Dictionnary["GeneralComment"]; ?>:</b><br /><br />
    <?=$cycle->commentaries; ?>
</div>

