<div class="roomdiv">
    <div class="map" style="background-image: url('<?=$room["map"]; ?>');">
	<?php foreach ($room["desk"] as $desk) { ?>
	    <?php
	    $Description = [
		[$Dictionnary["DeskName"], $desk["codename"]],
		[$Dictionnary["Type"], $desk["type"]],
		[$Dictionnary["IpAddress"], $desk["ip"]],
		[$Dictionnary["MacAddress"], $desk["mac"]],
		[$Dictionnary["Status"], $Dictionnary[["Free", "Used", "Locked", "Shutdown"][$desk["status"]]]]
	    ];
	    ob_start(); ?>
	    <table class="mapinfo">
		<?php foreach ($Description as $desc) { ?>
		    <tr><td><b><?=$desc[0]; ?>:</b></td><td><?=$desc[1]; ?></td></tr>
		<?php } ?>
		<tr><td colspan="2">
		    <?php foreach ($desk["users"] as $usr) { ?>
			<?php if ($usr["distant"] == 0) { ?>
			    <?=$Dictionnary["OccupiedBy"].": "; ?>
			<?php } else { ?>
			    <?=$Dictionnary["ConnectedTo"].": "; ?>
			<?php } ?>
			<a href="index.php?p=ProfileMenu&amp;a=<?=$usr["id"]; ?>">
			    <?=$usr["codename"]; ?>
			</a><?php if ($usr["locked"]) { ?>
			    &#128274;
			<?php } ?>
			<?php echo "\n"; ?>
		    <?php } ?>
		</td></tr>
		<tr><td colspan="2"><?=$desk["misc"]; ?></td></tr>
	    </table>
	    <?php $deskdesc = ob_get_clean(); ?>
	    <div
		class="desk"
		style="
		       right: <?=1250 - $desk["x"]; ?>px;
		       top: <?=$desk["y"]; ?>px;
		       background: url('<?=$Types[(int)$desk["type"]]; ?>'), <?=$Color[(int)$desk["status"]]; ?>;
		       border-color: <?=$BColor[(int)$desk["status"]]; ?>;
		       "
		onmouseover="document.getElementById('deskinfo<?=$room["id"]; ?>').innerHTML = '<?=htmlentities(str_replace("\n", "<br />", $deskdesc)); ?>';"
	    >
	    </div>
	<?php } ?>
    </div>
    <div class="info">
	<br />
	<h5><?=$room["name"]; ?><?=is_admin() ? " (".$room["codename"].")" : ""; ?></h5>
	<?php $js = "silent_submit(this);"; ?>
	<form
	    method="put"
	    action="/api/room/<?=$room["id"]; ?>"
	    onsubmit="return <?=$js; ?>;"
	    style="height: <?=$roomh = ($isdir = is_director_for_room($room["id"])) ? 180 : 100; ?>px; font-size: small;"
	>
	    <label for="capacity"><?=$Dictionnary["ComputerCapacity"]; ?></label>
	    : <?=$room["computer_capacity"]; ?><br />
	    <label for="capacity"><?=$Dictionnary["AvailableComputer"]; ?></label>
	    : <?=$room["computer_available"]; ?><br />
	    <label for="capacity"><?=$Dictionnary["SeatCapacity"]; ?></label>
	    <?php if ($isdir) { ?>
	    <input
		type="text"
		onchange="<?=$js; ?>"
		name="capacity"
		style="width: 50px;"
		value="<?=$room["capacity"] ? $room["capacity"] : "0"; ?>"
	    /><br />
	    <br />
	    <label for="map"><b><?=$Dictionnary["EditMap"]; ?></b></label><br />
	    <input
		type="file"
		onchange="<?=$js; ?>"
		name="map"
	    /><br />
	    <label for="configuration"><b><?=$Dictionnary["EditConfiguration"]; ?></b></label><br />
	    <input
		type="file"
		onchange="<?=$js; ?>"
		name="configuration"
	    /><br />
	    <br />
	    <?php } else { ?>
		: <?=$room["capacity"]; ?><br />
	    <?php } ?>
	</form>
	<div id="column scrollable" style="position: relative;">
	    <?php list_of_links([
		"hook_name" => "room",
		"hook_id" => $room["id"],
		"linked_name" => "school",
		"linked_elems" => $room["school"],
		"admin_func" => "only_admin"
	    ]); ?>		    
	</div>
	<p class="deskinfo" id="deskinfo<?=$room["id"]; ?>" style="bottom: 0px; height: calc(100% - 200px);"></p>
    </div>
</div>
