<?php
$subject_update_url = intercom_api_url($intercom, NULL, [
    "_method" => "subget",
    "live" => 1,
    "page" => $intercom["page"],
    "page_size" => $intercom["page_size"]
]);
?>
<form
    id="<?=$intercom["div"]; ?>_update_request"
    method="get"
    action="<?=htmlentities($subject_update_url); ?>"
    data-mode="subject"
    data-hash="<?=$intercom["content_hash"]; ?>"
    data-page="<?=$intercom["page"]; ?>"
    data-page-size="<?=$intercom["page_size"]; ?>"
    data-on-last-page="<?=$intercom["on_last_page"] ? 1 : 0; ?>"
    onsubmit="return false;"
></form>
<div
    id="<?=$intercom["div"]; ?>_subject_header"
    style="
	    height: 30px;
	    text-align: center;
	    font-size: x-large;
	    position: absolute;
	    top: 20px;
	    left: 10px;
	    right: 10px;
	    vertical-align: top;"
>
    <?php require ("intercom_subject_header.phtml"); ?>
</div>

<div style="height: 110px; position: absolute; top: 60px; left: 10px; right: 10px;">
    <form
	<?php $js = "silent_submitf(this, {tofill: '".$intercom["div"]."', clear_form: true, after_success: intercom_after_full_subject_update, after_success_parameter: '".$intercom["div"]."'});"; ?>
	method="post"
	action="<?=intercom_api_url_html($intercom); ?>"
	onsubmit="return <?=$js; ?>"
	style="width: calc(100% - 20px);
		height: 110px;
		margin-left: 10px;
		position: relative;
		"
    >
	<input type="hidden" name="full" value="1" />
	<?php if (isset($intercom["allow_visibility"]) && $intercom["allow_visibility"]) { ?>
	    <select
		name="visibility"
		style="position: absolute; top: 0px; right: 50px; width: 150px; height: 30px;"
	    >
		<option value="0" <?=((int)$intercom["default_visibility"] == 0) ? "selected" : ""; ?>><?=$Dictionnary["Public"]; ?></option>
		<option value="1" <?=((int)$intercom["default_visibility"] == 1) ? "selected" : ""; ?>><?=$Dictionnary["Administrative"]; ?></option>
		<?php if ($intercom["misc_type"] == "user") { ?>
		    <option value="2" <?=((int)$intercom["default_visibility"] == 2) ? "selected" : ""; ?>><?=$Dictionnary["PrivateMessage"]; ?></option>
		<?php } ?>
	    </select>
	<?php } else { ?>
	    <input type="hidden" name="visibility" value="<?=isset($intercom["default_visibility"]) ? (int)$intercom["default_visibility"] : intercom_visibility($intercom["misc_type"]); ?>" />
	<?php } ?>
	<input type="hidden" name="laboratory" value="" />
	<input
	    type="text"
	    name="title"
	    id="<?=$intercom["div"]; ?>_title"
	    style="
		  width: <?=isset($intercom["allow_visibility"]) && $intercom["allow_visibility"] ? "calc(100% - 210px)" : "calc(100% - 50px)"; ?>; height: 30px;
		  position: absolute; top: 0px; left: 0px;
		  "
	    placeholder="<?=$Dictionnary["Title"]; ?>"
	/>
	<textarea
	    id="<?=$intercom["div"]; ?>_message"
	    placeholder="<?=$Dictionnary["Message"]; ?>"
	    name="message"
	    style="
		resize: none;
		width: calc(100% - 50px);
		height: 70px;
		position: absolute;
		top: 40px;
		left: 0px;
		"
	></textarea>
	<input
	    type="button"
	    onclick="<?=$js; ?>"
	    style="
		  width: 40px;
		  height: 100%;
		  position: absolute;
		  top: 0px; right: 0px;"
	    value="+"
	/>
    </form>
</div>

<div style="height: 50px; left: 10px; right: 10px; position: absolute; top: 180px;">
    <div style="width: 50px; position: absolute; left: 0px;"></div>
    <div style="
		position: absolute;
		left: 50px;
		right: 450px;
		text-align: center;
		"
    >
	<?=$Dictionnary["Title"]; ?>
    </div>
    <div style="width: 50px; position: absolute; right: 400px; text-align: center;">#</div>
    <div style="width: 200px; position: absolute; right: 200px; text-align: center;">
	<?=$Dictionnary["CreationBy"]; ?>
    </div>
    <div style="width: 200px; position: absolute; right: 0px; text-align: center;">
	<?=$Dictionnary["LastModificationBy"]; ?>
    </div>
</div>

<div
    id="<?=$intercom["div"]; ?>_subject_list"
    style="
	position: absolute;
	top: 210px;
	bottom: 10px;
	left: 10px;
	right: 10px;
	overflow-y: auto;
	"
>
    <?php require ("intercom_subject_list.phtml"); ?>
</div>
