<?php
$subject = $intercom["subjects"][0];
$msgbox = $intercom["div"]."_msg";
$action = intercom_api_url($intercom, $subject["id"]);
$message_update_url = intercom_api_url($intercom, $subject["id"], [
    "_method" => "subget",
    "live" => 1,
    "page" => $subject["page"],
    "page_size" => $subject["page_size"]
]);
?>
<form
    id="<?=$intercom["div"]; ?>_update_request"
    method="get"
    action="<?=htmlentities($message_update_url); ?>"
    data-mode="message"
    data-hash="<?=$intercom["content_hash"]; ?>"
    data-page="<?=$subject["page"]; ?>"
    data-page-size="<?=$subject["page_size"]; ?>"
    data-count="<?=$subject["nbr_message"]; ?>"
    data-last-id="<?=$subject["last_message_id"]; ?>"
    data-on-last-page="<?=$subject["on_last_page"] ? 1 : 0; ?>"
    onsubmit="return false;"
></form>
<div class="intercom_messages" style="
	    height: 96%;
	    width: calc(100% - 20px);
	    margin-left: 10px;
	    position: relative;
	    ">

    <div
	id="<?=$intercom["div"]; ?>_message_controls"
	style="height: 40px; width: 100%; position: absolute; top: 0px; left: 0px;"
    >
	<?php require ("intercom_message_controls.phtml"); ?>
    </div>

    <div id="<?=$msgbox; ?>" style="
	     width: 100%;
	     position: absolute;
	     top: 50px;
	     bottom: <?=$subject["on_last_page"] ? "170px" : "10px"; ?>;
	     left: 0px;
	     overflow-y: auto;
	     border-radius: 10px;
	     box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.2);
	     ">
	<?php require ("intercom_message_list.phtml"); ?>
    </div>

    <div
	id="<?=$intercom["div"]; ?>_message_composer"
	style="position: absolute; height: 150px; bottom: 10px; width: 100%;"
    >
	<?php require ("intercom_message_composer.phtml"); ?>
    </div>
</div>

