<?php if ($subject["on_last_page"]) { ?>
    <form
	<?php $js = "silent_submitf(this, {tofill: '".$intercom["div"]."', clear_form: true, after_success: intercom_after_full_message_update, after_success_parameter: '".$intercom["div"]."'});"; ?>
	method="post"
	action="<?=$action; ?>"
	onsubmit="return <?=$js; ?>;"
	style="width: 100%; height: 100%; position: relative;"
    >
	<input type="hidden" name="page" value="-1" />
	<input type="hidden" name="full" value="1" />
	<textarea name="message"
		  style="width: calc(90%);
			height: 100%;
			resize: none;
			position: absolute; top: 0px; left: 0px;"
	></textarea>
	<input
	    type="button"
	    style="width: 9%; height: 100%; margin-left: 1%;
		  position: absolute; right: 0px; top: 0px;"
	    onclick="<?=$js; ?>"
	    value="+"
	/>
    </form>
<?php } ?>
