<span
    title="<?=htmlentities($Dictionnary["Channel"]." ".ucfirst($intercom["name"])); ?>"
    style="
        display: inline-block;
        max-width: min(100%, calc(100% - 170px));
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        vertical-align: middle;
    "
>
    <?=$Dictionnary["Channel"]; ?> <?=ucfirst($intercom["name"]); ?>
</span>

<?php
$pbrowser = $intercom;
$action =
    "/api/intercom/{$intercom["id_misc"]}".
    "/{$intercom["misc_type"]}"
;
require ("intercom_page_browser.phtml");
?>
