<?php
$subject = $intercom["subjects"][0];
$msgbox = $intercom["div"]."_msg";
$action =
    "/api/intercom/{$subject["id_misc"]}".
    "/{$subject["misc_type"]}".
    "/{$subject["id"]}"
;
?>
<div class="intercom_messages" style="
	    height: 96%;
	    width: calc(100% - 20px);
	    margin-left: 10px;
	    position: relative;
	    ">

    <div style="height: 40px; width: 100%; position: absolute; top: 0px; left: 0px;">
	<div style="width: 50px; 100%; position: absolute; top: 0px; left: 0px;">
	    <form
		<?php $js = "silent_submitf(this, {tofill: '".$intercom["div"]."'})"; ?>
		method="get"
		action="<?=$intercom["base_url"]; ?>"
		onsubmit="return <?=$js; ?>"
	    >
		<input
		    type="button"
		    value="&larr;"
		    style="width: 40px; height: 30px; margin-top: 5px;"
		    onclick="return <?=$js; ?>"
		/>
	    </form>
	</div>
	<div style="width: 70%; height: 40px; position: absolute; top: 0px; left: 50px; display: table;">
	    <h5 style="display: table-cell; vertical-align: middle; fon-size: large;">
		<?=$intercom["name"]." - ".htmlentities($subject["title"]); ?>
	    </h5>
	</div>
	<?php $pbrowser = $subject; ?>
	<?php require ("intercom_page_browser.phtml"); ?>
    </div>

    <div id="<?=$msgbox; ?>" style="
	     width: 100%;
	     <?php if ($subject["on_last_page"]) { ?>
	     height: calc(100% - 80px - 150px);
	     <?php } else { ?>
	     height: calc(100% - 80px);
	     <?php } ?>
	     position: absolute;
	     top: 50px;
	     left: 0px;
	     overflow-y: auto;
	     border-radius: 10px;
	     box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.2);
	     ">
	<?php require ("intercom_message_list.phtml"); ?>
    </div>

    <?php if ($subject["on_last_page"]) { ?>
	<div style="position: absolute; height: 150px; bottom: 10px; width: 100%;">
	    <form
		<?php $js = "silent_submitf(this, {tofill: '$msgbox'})"; ?>
		method="post"
		action="<?=$action; ?>"
		onsubmit="return <?=$js; ?>;"
		style="width: 100%; height: 100%; position: relative;"
	    >
		<input type="hidden" name="page" value="-1" />
		<textarea name="message"
			  style="width: calc(90%);
				height: 100%;
				resize: none;
				position: absolute; top: 0px; left: 0px;"
		></textarea>
		<input
		    type="button"
		    style="width: 9%; height: 100%; margin-left: 1%;
			  position: absolute; right: 0px; top: 0px;"
		    onclick="<?=$js; ?>"
		    value="+"
		/>
	    </form>
	</div>
    <?php } ?>
</div>

