<?php
/*
** $page : template ou module
** $path : le chemin du dossier ouvert depuis le dossier racine des ressources
** $target : le chemin du dosser ouvert depuis le dossier racine du site web
** $language : la langue qu'on utilise actuellement. NA si c'est pour toutes les langues
** $id : l'identifiant associé à l'objet contenant tous ces fichiers
** $type : la nature des fichiers parcourus
** $fbid : la base du nom de l'id du navigateur
*/
if ($type !== NULL && $id !== NULL)
    $api = "/api/$page/$id/$type";
else
    $api = "/api/$page";

if (!isset($nocd))
    $nocd = false;
else
    $nocd = !!$nocd;
if (!isset($hide_path_browser))
    $hide_path_browser = $nocd;
else
    $hide_path_browser = !!$hide_path_browser;
if (!isset($path_browser_can_cd))
    $path_browser_can_cd = !$nocd;
else
    $path_browser_can_cd = !!$path_browser_can_cd;

if (!@strlen($fbid))
    $fbid = "file_browser";
$js = "silent_submit(this, '$fbid$language');";
?>
<form
    style="width: 100%;"
	   method="put"
	   onsubmit="return <?=$js; ?>"	
           action="<?=$api; ?>"
>
    <input type="hidden" name="language" value="<?=$language; ?>" />
    <input type="hidden" name="fbid" value="<?=$fbid; ?>" />
    <input type="hidden" name="nocd" value="<?=$nocd ? 1 : 0; ?>" />
    <input type="hidden" name="path_browser_can_cd" value="<?=$path_browser_can_cd ? 1 : 0; ?>" />
    <input
	id="path<?=$fbid.$language; ?>"
	class="path_browser"
	name="path"
	value="<?=$path == "" ? "/" : $path; ?>"
	<?php if (!$hide_path_browser) { ?>
	    type="text"
	    <?php if ($path_browser_can_cd) { ?>
		onchange="return <?=$js; ?>"
	    <?php } else { ?>
		readonly="readonly"
	    <?php } ?>
	<?php } else { ?>
	    type="hidden"
	<?php } ?>
    />
</form>
<div
    class="file_browser"
    id="<?=$fbid.$language; ?>"
    <?php if (isset($file_browser_height)) { ?>
	   style="height: <?=$file_browser_height; ?>; overflow: auto;"
           <?php unset($file_browser_height); ?>
    <?php } ?>
>
    <?php require ("file_browser.phtml"); ?>
</div>
