<h2><?=$Dictionnary["AboutYou"]; ?>, <?php display_nickname($User, false); ?></h2>
<br />
<table><tr><td>
    <?php display_avatar($User); ?>
</td><td>
    <h5 style="text-align: center;"><?=$Dictionnary["StudentStatusGraph"]; ?></h5>
    <?php

    $label = $Dictionnary["HourTotal"];
    // 8 heures par jour + 4h par week end (l'exam) + 4h le soir par sem)
    // Ca fait 50h par semaine en moyenne. Cela inclu les devoirs.
    // Sachant qu'en math sup, c'est 55-60h, et spé 60-70h d'après les stats.
    $logcursor = [$wavg, 0, 200, 100];
    require (__DIR__."/../../tools/student_status.php");

    $label = $Dictionnary["Presence"];
    $logcursor = [$aavg, $amin, $amax, 0.8 * $amax];
    require (__DIR__."/../../tools/student_status.php");

    $label = $Dictionnary["MedalGain"];
    $logcursor = [$mavg, $mmin, $mmax, 0.25 * $mmax];
    require (__DIR__."/../../tools/student_status.php");

    $label = $Dictionnary["GlobalIndicator"];
    $logcursor = [$pronostic * 100, 0, 100, 50];
    require (__DIR__."/../../tools/student_status.php");
    ?>
</td></tr></table>

<p style="font-size: small; width: 90%; margin-left: 5%; text-align: center;">
    <!--
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;<?=$Dictionnary["SecretIdentity"]; ?>
    <span class="hidden_mouse">
	<?php
	if (@strlen($User["outside_secret"]) == 0)
	{
	    $secret = openssl_random_pseudo_bytes(8);
 	    $secret = str_replace("=", "", base64_encode($secret));
	    $secret = str_replace("/", "", $secret);
	    $Database->query("
	        UPDATE user
	        SET outside_secret = '$secret'
	        WHERE id = ".$User["id"]
	    );
	}
	?>
	<br /><br />
	<?=crc32($User["outside_secret"]); ?>
    </span>
    -->
</p>

<?php if ((@strlen($User["birth_date"]) && datex("d/m/Y", time()) == datex("d/m/Y", date_to_timestamp($User["birth_date"])))) { ?>
    <p style="text-align: center;">
	<br />
	<b><?=$Dictionnary["HappyBirthday"]; ?>!</b>
    </p>
<?php } ?>

<p style="text-align: center;">
    <br />
    <?php $today_time = get_student_log(); ?>
    Aujourd'hui, vous avez travaillé <?=(int)($today_time / 60.0 / 60.0); ?> heures, <?=(int)(($today_time / 60.0) % 60); ?> minutes et <?=(int)($today_time % 60); ?> secondes.
    <?php if (($wai = where_am_i()) != []) { ?>
	<?php $rooms = $trooms = fetch_rooms(-1, true); ?>
	<?php foreach ($trooms as $room) { ?>
	    <?php if (isset($wai["id"]) && $room["id"] == $wai["id"]) { ?>
		<br /><br />
		<?=$Dictionnary["YouAreLocatedInRoom"]; ?> '<?=$room["name"]; ?>'
	    <?php } ?>
	<?php } ?>
    <?php } ?>
</p>
