<?php if ($silent) return ; ?>
<?php require_once ("collect_dashboard_activities.php"); ?>
<?php require_once ("collect_dashboard_projects.php"); ?>
<?php require_once ("collect_dashboard_matters.php"); ?>
<?php if ($User == NULL) { ?>
    <?php require ("welcome.phtml"); ?>
<?php } else { ?>
    <table id="home_table">
	<tr><td>
	    <div id="welcome"><?php require ("welcome.phtml"); ?></div>
	</td><td>
	    <div style="text-align: center;">
		<?php require_once ("last_medals.php"); ?>
	    </div>
	</td><td rowspan="2">
	    <div><?php // require_once ("intercom.php"); ?></div>
	</td><td rowspan="2">
	    <?php
	    $participate = collect_dashboard_activities(
		time(),
		first_second_of_day(time()) + 60 * 60 * 24 * 2,
		false
	    );
	    $managed = collect_dashboard_activities(
		time(),
		first_day_of_week(time()) + 60 * 60 * 24 * 14,
		true
	    );
	    $activities["participate"] = $participate["participate"];
	    $activities["managed"] = $managed["managed"];
	    ?>
	    <div class="tinyscroll">
		<?php require_once ("assistant.php"); ?>
		<?php require_once ("matters.phtml"); ?>
		<?php require_once ("projects.phtml"); ?>
		<?php require_once ("activities.phtml"); ?>
		<?php if (count($activities["managed"])) { ?>
		    <?php require_once ("managed.phtml"); ?>
		<?php } ?>
	    </div>    
	</td></tr>
	<tr>
	    <?php
	    $powerbox =
		count($User["children"])
		|| $OriginalUser["authority"] >= ADMINISTRATOR
	    ;
	    ?>
	    <td <?=!$powerbox ? 'colspan="2"' : ""; ?>>
		<div id="about_you"><?php require ("about_you.phtml"); ?></div>
	    </td>
	    <?php if ($powerbox) { ?>
		<td>
		    <div
			<?php $alerts = []; ?>
			<?php if ($OriginalUser["authority"] >= ADMINISTRATOR) { ?>
			    <?php $alerts = retrieve_alerts(); ?>
			<?php } ?>
			<?php if (isset($alerts) && count($alerts)) { ?>
			    id="powerbox"
			<?php } ?>
			class="tinyscroll"
		    >
			<?php require ("power.phtml"); ?>
		    </div>
		</td>
	    <?php } ?>
	</tr>
    </table>
<?php } ?>

<?php // full_backup(); ?>
