<?php $projects = collect_dashboard_matters(time()); ?>
<?php if (count($projects)) { ?>
    <h3><?=$Dictionnary["OpenedModules"]; ?>:</h3>
    <table style="text-align: center;">
	<tr>
	    <th><?=$Dictionnary["Name"]; ?></th>
	    <th><?=$Dictionnary["EndDate"]; ?></th>
	</tr>
	<?php foreach ($projects as $act) { ?>
	    <tr class="home_activity">
		<td>
		    <a
			href="index.php?p=ModulesMenu&amp;a=<?=$act["id"]; ?>"
			style="color: gray;"
		    >
			<?=$act["name"]; ?>
		    </a>
		</td>
		<td>
		    <?php if ($act["close_date"] != NULL) { ?>
			<?=datex("d/m", date_to_timestamp($act["close_date"])); ?>
			<?php if ($act["soon"]) { ?>
			    <?=$Dictionnary["EndThisWeek"]; ?>
			<?php } ?>
		    <?php } ?>
		</td>
	    </tr>
	<?php } ?>
    </table>
    <br />
<?php } ?>
