<?php if (count($User["children"])) { ?>
    <h2><?=$Dictionnary["ImpersonateAsParent"]; ?>:</h2>
    <form action="index.php?<?=unrollget(); ?>" method="post">
	<select name="children" style="width: 49%;">
	    <?php foreach ($User["children"] as $children) { ?>
		<option value="<?=$children["id"]; ?>"><?=$children["codename"]; ?></option>
	    <?php } ?>
	</select>
	<input type="submit" value="<?=$Dictionnary["Impersonate"]; ?>" style="width: 49%;" />
    </form>
    <br />
<?php } ?>

<?php if ($OriginalUser["codename"] != $User["codename"] && $ParentConnexion) { ?>
    <?php
    echo $Dictionnary["FakeLoggedAs"]." ".$User["codename"]."<br />";
    echo $Dictionnary["RealIdentity"]." ".$OriginalUser["codename"]."<br />";
    ?>
    <form action="index.php?<?=unrollget(); ?>" method="post">
	<?=$Dictionnary["CancelImpersonate"].":"; ?>
	<input type="hidden" name="children" value="<?=$OriginalUser["codename"]; ?>" />
	<input type="submit" value="X" />
    </form>
    <br />
<?php } ?>

<?php if ($OriginalUser["authority"] >= ADMINISTRATOR) { ?>
    <h2><?=$Dictionnary["AdministrationPower"]; ?></h2>
<?php } ?>

<div>
    <?php if ($OriginalUser["authority"] >= ADMINISTRATOR && $ParentConnexion == false) { ?>
	<?php if ($OriginalUser["codename"] != $User["codename"]) { ?>
	    <?php
	    $alerts[] = $Dictionnary["FakeLoggedAs"]." ".$User["codename"];
	    $alerts[] = $Dictionnary["RealIdentity"]." ".$OriginalUser["codename"];
	    ?>
	    <form action="index.php?<?=unrollget(); ?>" method="post">
		<?=$Dictionnary["CancelImpersonate"].":"; ?>
		<input type="hidden" name="log_as" value="<?=$OriginalUser["codename"]; ?>" />
		<input type="submit" value="X" />
	    </form>
	<?php } ?>
	<form action="index.php?<?=unrollget(); ?>" method="post">
	    <?=$Dictionnary["Impersonate"].":<br />"; ?>
	    <input type="text" name="log_as" placeholder="<?=$Dictionnary["Login"]; ?>" style="width: 49%;" />
	    <input type="submit" value="<?=$Dictionnary["Impersonate"]; ?>" style="width: 49%;" />
	</form>
    <?php } ?>
    <br />

    <?php if ($User["authority"] >= ADMINISTRATOR) { ?>
	<form method="post" action="index.php?<?=unrollget(); ?>">
	    <?php if (isset($User["admin_mode"]) && $User["admin_mode"]) { ?>
		<?php $alerts[] = "<br />".$Dictionnary["AdminModeEnabled"]; ?>
		<input
		    type="submit"
		    name="admin_mode"
		    value="<?=$Dictionnary["DisableAdminMode"]; ?>"
		    style="width: 99%; height: 50px;"
		/>
	    <?php } else { ?>
		<input
		    type="submit"
		    name="admin_mode"
		    value="<?=$Dictionnary["EnableAdminMode"]; ?>"
		    style="width: 99%; height: 50px;"
		/>
	    <?php } ?>
	</form>
    <?php } ?>
</div>

<?php
if (isset($alerts) && count($alerts))
{
    echo "<br />";
    echo "<h3>".$Dictionnary["Warning"]."!</h3><br />";
    echo "<span style=\"font-size: x-small;\">";
    foreach ($alerts as $a)    {
	echo $a."<br />";
    }
    echo "</span>";
}
?>
