<?php $projects = collect_dashboard_projects(time()); ?>
<?php if (count($projects)) { ?>
    <h3><?=$Dictionnary["CurrentProjects"]; ?>:</h3>
    <table style="text-align: center;">
	<tr>
	    <th><?=$Dictionnary["Name"]; ?></th>
	    <th><?=$Dictionnary["EndDate"]; ?></th>
	</tr>
	<?php foreach ($projects as $act) { ?>
	    <tr class="home_activity">
		<td>
		    <a
			href="index.php?p=ActivityMenu&amp;a=<?=$act["id"]; ?>"
			<?php if ($act["subscribed"] == false) { ?>
			    style="color: gray;"
			<?php } ?>
		    >
			<?=$act["name"]; ?>
		    </a>
		</td>
		<td>
		    <?php if ($act["subscribed"] && $act["pickup_date"] != NULL) { ?>
			<?=datex("d/m", date_to_timestamp($act["pickup_date"])); ?>
			<?php if ($act["soon"]) { ?>
			    <?=$Dictionnary["EndThisWeek"]; ?>
			<?php } ?>
		    <?php } else if ($act["close_date"] != NULL) { ?>
			<?=datex("d/m", date_to_timestamp($act["close_date"])); ?>
			<?php if ($act["subsoon"]) { ?>
			    <?=$Dictionnary["EndThisWeek"]; ?>
			<?php } ?>
		    <?php } ?>
		</td>
	    </tr>
	<?php } ?>
    </table>
    <br />
<?php } ?>
