<a href="index.php?p=ActivityMenu&amp;a=<?=$Session->id_activity; ?>&amp;b=<?=$Session->id; ?>" class="<?=($Session->registered || $Session->slot_reserved) ? "registered_act" : "unregistered_act"; ?>">

    <?php
    // Il faudra remplacer ca par des propriété de type d'activité...
    if ($Session->parent->type == 5 || $Session->parent->type == 6)
	$background = 'background-image: url(\'./res/double_rays.png\'); background-repeat: repeat; background-size: 25%;';
    else if ($Session->parent->type == 7 || ($Session->parent->type >= 10 && $Session->parent->type <= 13))
	$background = 'background-image: url(\'./res/rays.png\'); background-repeat: repeat; background-size: 25%;';
    else if ($Session->parent->type == 8 || $Session->parent->type == 9)
	$background = 'background-image: url(\'./res/antirays.png\'); background-repeat: repeat; background-size: 25%;';
    else
	$background = "";
    ?>

    <div
	class="calendar_activity tinyscroll"
	style="
	       width: calc(<?=$Session->width; ?>% - 6px);
	       left: calc(<?=$Session->left; ?>% + 2px);
	       top: calc(<?=$Session->top; ?>% + 2px);
	       height: calc(<?=$Session->height > 5 ? $Session->height : 5; ?>% - 4px);
	       background-color: <?=color_from_name($Session->parent->parent_codename, ["white"]); ?>;
	       border-radius: 5px;
	       <?=$background; ?>
	       "
    >
	<p class="calendar_basic_info">
	    <?php if (@strlen($Session->parent->name) != 0) { ?>
		<span><?=ucfirst($Session->parent->name); ?></span><br />
		<?=ucfirst($Dictionnary[$Session->parent->type_name]); ?><br />
		<i><?=ucfirst($Session->parent->parent_name); ?></i>
	    <?php } else { ?>
		<i><?=ucfirst($Session->parent->parent_name); ?></i><br />
		<?=ucfirst($Dictionnary[$Session->parent->type_name]); ?>
	    <?php } ?>
	</p>
	<p class="calendar_basic_info">
	    <?=sprintf("%02d:%02d", $Session->start_hour, $Session->start_minute); ?>
	    -
	    <?=sprintf("%02d:%02d", $Session->end_hour, $Session->end_minute); ?>
	</p>
	<p class="calendar_basic_info">
	    <?php foreach ($Session->room as $room) { ?>
		<?=$room["name"]; ?><br />
	    <?php } ?>
	</p>
	<p class="calendar_basic_info">

	</p>
	<?php if ($Session->registered != NULL && 0) { // Non affiché, car la transparence devrait suffire ?>
	    <p class="calendar_basic_info">
		<b><?=$Dictionnary["Registered"]; ?></b>
	    </p>
	<?php } ?>
	<br />
	<?php require ("missing_icon.phtml"); ?>
    </div>
</a>
