<a href="index.php?p=ActivityMenu&amp;a=<?=$Session->id_activity; ?>&amp;b=<?=$Session->id; ?>" class="<?=($Session->registered || $Session->slot_reserved) ? "registered_act" : "unregistered_act"; ?>">

    <?php
    // Il faudra remplacer ca par des propriété de type d'activité...
    if ($Session->parent->type == 5 || $Session->parent->type == 6)
	$background = 'background-image: url(\'./res/double_rays.png\'); background-repeat: repeat; background-size: 25%;';
    else if ($Session->parent->type == 7 || ($Session->parent->type >= 10 && $Session->parent->type <= 13))
	$background = 'background-image: url(\'./res/rays.png\'); background-repeat: repeat; background-size: 25%;';
    else if ($Session->parent->type == 8 || $Session->parent->type == 9)
	$background = 'background-image: url(\'./res/antirays.png\'); background-repeat: repeat; background-size: 25%;';
    else
	$background = "";
    ?>

    <div
	class="calendar_activity tinyscroll"
	       style="width: <?=$Session->width; ?>%; left: <?=$Session->left; ?>%; top: <?=$Session->top; ?>%; height: <?=$Session->height; ?>%; background-color: <?=color_from_name($Session->parent->parent_codename, ["white"]); ?>; <?=$background; ?>"
    >
	<p class="calendar_basic_info">
	    <?php if (@strlen($Session->parent->name) != 0) { ?>
		<b><?=ucfirst($Session->parent->name); ?></b><br />
		<?=ucfirst($Dictionnary[$Session->parent->type_name]); ?><br />
		<i><?=ucfirst($Session->parent->parent_name); ?></i>
	    <?php } else { ?>
		<i><?=ucfirst($Session->parent->parent_name); ?></i><br />
		<?=ucfirst($Dictionnary[$Session->parent->type_name]); ?>
	    <?php } ?>
	</p>
	<p class="calendar_basic_info">
	    <?=sprintf("%02d:%02d", $Session->start_hour, $Session->start_minute); ?>
	    -
	    <?=sprintf("%02d:%02d", $Session->end_hour, $Session->end_minute); ?>
	</p>
	<p class="calendar_basic_info">
	    <?php foreach ($Session->room as $room) { ?>
		<?=$room["name"]; ?><br />
	    <?php } ?>
	</p>
	<p class="calendar_basic_info">

	</p>
	<?php if ($Session->registered != NULL) { ?>
	    <p class="calendar_basic_info">
		<b><?=$Dictionnary["Registered"]; ?></b>
	    </p>
	<?php } ?>
    </div>

    <?php
    $no_room = count($Session->room) == 0;
    $no_teacher = count($Session->parent->teacher) == 0;
    $no_slots = count($Session->slot) == 0 && ($Session->parent->type == 7 || ($Session->parent->type >= 10 && $Session->parent->type <= 13));
    ?>

    <?php if (is_admin() && ($no_room || $no_teacher || $no_slots) && $Session->end_date > time()) { ?>
	<!-- ICONES D'INFORMATIONS -->
	<div class="calendar_edit_box" id="<?=$Session->parent->codename; ?>" style="top: <?="calc(".$Session->top."% + ".$Session->height."% + 1px)"; ?>; left: <?=$Session->left; ?>%; width: <?=$Session->width; ?>%;">
	    <?php if ($no_room) { ?>
		<img src="res/rromms.png" alt="<?=$Dictionnary["NoRoom"]; ?>" width="20" height="20" />
	    <?php } ?>
	    <?php if ($no_teacher) { ?>
		<img src="res/rprofile.png" alt="<?=$Dictionnary["NoTeacher"]; ?>" width="20" height="20" />
	    <?php } ?>
	    <?php if ($no_slots) { ?>
		<img src="res/rmodules.png" alt="<?=$Dictionnary["NoSlots"]; ?>" width="20" height="20" />
	    <?php } ?>
	</div>
    <?php } ?>
</a>
