<h2><?=$Dictionnary["AddASchool"]; ?></h2><br />
<form onsubmit="return false;" method="POST" action="/api/school" style="text-align: center;">

    <input
	type="text"
	name="codename"
	placeholder="<?=$Dictionnary["CodeName"]; ?>"
    /><br />
    
    <input
	type="text"
	name="legal_name"
	placeholder="<?=$Dictionnary["LegalName"]; ?>"
    /><br />

    <input
	type="phone"
	name="phone"
	placeholder="<?=$Dictionnary["Phone"]; ?>"
    /><br />

    <input
	type="mail"
	name="mail"
	placeholder="<?=$Dictionnary["Mail"]; ?>"
    /><br />

    <input
	type="text"
	name="main_info"
	placeholder="<?=$Dictionnary["Name. Address. Company Immatriculation."]; ?>"
    /><br />

    <input
	type="text"
	name="school_info"
	placeholder="<?=$Dictionnary["School Type. School Immatriculation."]; ?>"
    /><br />

    <input
	type="text"
	name="formation_info"
	placeholder="<?=$Dictionnary["Training Organization Immatriculation."]; ?>"
    /><br />

    <input
	type="text"
	name="alternation_info"
	placeholder="<?=$Dictionnary["Apprenticeship Training Center Immatriculation."]; ?>"
    /><br />
    <br />

    <label for="icon"><?=$Dictionnary["SchoolLogo"]; ?></label>
    <input
	type="file"
	name="icon"
	placeholder="<?=$Dictionnary["SchoolLogo"]; ?>"
    /><br />
    <br />

    <?php forge_language_formular(["name" => "text"], $_POST); ?>

    <input
	type="button"
	onclick="silent_submitf(this.parentNode, {tofill: 'schoollist', toclear: 'schoollist', wrapper: 'schools', clear_form: true});"
	value="<?=$Dictionnary["AddASchool"]; ?>"
    />
</form>
