<?php
$school_tabs = [
    "Configuration" => __DIR__."/configuration_tab.phtml",
    "Personnel" => __DIR__."/staff_tab.phtml",
    "Élèves" => __DIR__."/students_tab.phtml",
    "Cycles" => __DIR__."/cycles_tab.phtml",
    "Contrats" => __DIR__."/contracts_tab.phtml",
    "Mail" => __DIR__."/mail_tab.phtml",
];
?>

<div class="school_admin_page" id="school<?=$school["id"]; ?>_configuration">
    <div class="school_admin_header">
        <div class="school_admin_icon">
            <?php $pic = school_site_logo_path($school, false, true); ?>
            <?php $pic_version = file_exists($pic) ? filemtime($pic) : 0; ?>
            <div style="background-image: url('<?=$pic; ?>?<?=$pic_version; ?>');"></div>
        </div>
        <div class="school_admin_title">
            <h3><?=$Dictionnary["SchoolConfiguration"]; ?></h3>
            <p><?=$Dictionnary["CodeName"]; ?>: <b><?=$school["codename"]; ?></b></p>
            <p>Organisation liée : <b><?=htmlspecialchars($school["organization_codename"] ?? "", ENT_QUOTES); ?></b></p>
        </div>
    </div>

    <?php tabpanel(
        $school_tabs,
        "school-admin-".$school["id"],
        "Configuration",
        "school-tab-button",
        "school-tab-content"
    ); ?>
</div>
