<td style="padding-left: 0px !important; padding-right: 0px !important; margin: 0;">
    <br />
    <table class="no_border"><tr><td>
	<?php list_of_links([
	    "hook_name" => "school",
	    "hook_id" => $content["id"],
	    "linked_name" => [
		"table" => "user",
		"name" => "director",
		"placeholder" => "Director",
		"" => "director",
	    ],
	    "linked_elems" => $content["director"],
	]); ?>
	<br />
    </td><td>

	<?php $js = "window.confirm('".$Dictionnary["ConfirmDeletion"]."') && silent_submit(this, 'cyclelist');" ?>
	<form
	    method="delete"
		    action="/api/school/<?=$content["id"]; ?>"
		    style="width: 100%; height: 100%;"
		    onsubmit="return <?=$js; ?>;"
	>
	    <input
		type="button"
		onclick="<?=$js; ?>"
		value="&#10007;"
		style="color: red; width: 50px; height: 100%;"
	    />
	</form>
    </td></tr></table>
</td>
