<td>
    <?php list_of_links([
	"hook_name" => "school",
	"hook_id" => $content["id"],
	"linked_name" => [
	    "table" => "user",
	    "name" => "director",
	    "placeholder" => "Director",
	    "" => "director",
	],
	"linked_elems" => $content["director"],
    ]); ?>
</td><td>
    <?php list_of_links([
	"hook_name" => "school",
	"hook_id" => $content["id"],
	"linked_name" => [
	    "table" => "user",
	    "name" => "teacher",
	    "placeholder" => "Teacher",
	    "" => "teacher",
	],
	"linked_elems" => $content["teacher"],
    ]); ?>
</td><td>
    <?php list_of_links([
	"hook_name" => "school",
	"hook_id" => $content["id"],
	"linked_name" => [
	    "table" => "user",
	    "name" => "commercial",
	    "placeholder" => "Commercial",
	    "" => "commercial",
	],
	"linked_elems" => $content["commercial"],
    ]); ?>
</td><td>
    <?php list_of_links([
	"hook_name" => "school",
	"hook_id" => $content["id"],
	"linked_name" => [
	    "table" => "user",
	    "name" => "secretariat",
	    "placeholder" => "Secretariat",
	    "" => "secretariat",
	],
	"linked_elems" => $content["secretariat"],
    ]); ?>
</td><td>
    <?php list_of_links([
	"hook_name" => "school",
	"hook_id" => $content["id"],
	"linked_name" => [
	    "table" => "user",
	    "name" => "librarian",
	    "placeholder" => "Library",
	    "" => "librarian",
	],
	"linked_elems" => $content["librarian"],
    ]); ?>
</td><td>
    <?php $js = "window.confirm('".$Dictionnary["ConfirmDeletion"]."') && silent_submit(this, 'cyclelist');" ?>
    <form
	method="delete"
	action="/api/school/<?=$content["id"]; ?>"
	style="width: 100%;"
	onsubmit="return <?=$js; ?>;"
    >
	<input
	    type="button"
	    onclick="<?=$js; ?>"
	    value="&#10007;"
	    style="color: red; background-color: #202020; width: 50px; height: 50px;"
	/>
    </form>
</td>
