<?php $URL = unrollurl(["a" => $content["id"]]); ?>

<tr>
    <td <?=clickable($URL); ?>><?=$content["id"]; ?></td>
    <td <?=clickable($URL); ?>>
	<?php $pic = school_site_logo_path($content, false, true); ?>
	<?php $pic_version = file_exists($pic) ? filemtime($pic) : 0; ?>
	<div
	    style="background-image: url('<?=$pic; ?>?<?=$pic_version; ?>');
		   background-size: contain;
		   width: 150px;
		   height: 150px;
		   "
	></div>
    </td>
    <td><?=$content["codename"]; ?></td>
    <td <?=clickable($URL); ?>><?=$content["name"]; ?></td>
    <?php if (!is_admin()) { ?>
	<td>
	    <?php foreach ($content["director"] as $dir) { ?>
		<a href="index.php?p=ProfileMenu&amp;<?=$dir["id"]; ?>"
		><?=$dir["codename"]; ?></a><br />
	    <?php } ?>
	</td><td>
	    <?php foreach ($content["teacher"] as $dir) { ?>
		<a href="index.php?p=ProfileMenu&amp;<?=$dir["id"]; ?>"
		><?=$dir["codename"]; ?></a><br />
	    <?php } ?>
	</td><td>
	    <?php foreach ($content["commercial"] as $dir) { ?>
		<a href="index.php?p=ProfileMenu&amp;<?=$dir["id"]; ?>"
		><?=$dir["codename"]; ?></a><br />
	    <?php } ?>
	</td><td>
	    <?php foreach ($content["secretariat"] as $dir) { ?>
		<a href="index.php?p=ProfileMenu&amp;<?=$dir["id"]; ?>"
		><?=$dir["codename"]; ?></a><br />
	    <?php } ?>
	</td><td>
	    <?php foreach ($content["librarian"] as $dir) { ?>
		<a href="index.php?p=ProfileMenu&amp;<?=$dir["id"]; ?>"
		><?=$dir["codename"]; ?></a><br />
	    <?php } ?>
	</td>
    <?php } else { ?>
	<?php require ("edit_school.phtml"); ?>
    <?php } ?>
</tr>
