<style>
 .outline .outlinee p, .outline h2, .outline a, .outline .gradetab
 {
     /*
	-webkit-text-stroke: 1px black;
	text-stroke: 1px black;
      */
     background-color: rgba(255, 255, 255, 0.5);
     border-radius: 10px;
     padding: 10px 10px 10px 10px;
     margin: 10px 10px 10px 10px;
 }
 .outline hr
 {
     margin-top: 5px;
 }
 .outline .gradetab, .outline .outlinee .subbuttons
 {
     margin-top: 20px;
 }
 .gradetab th, .gradetab td
 {
     border-radius: 5px;
     box-shadow: inset 0px 1px 3px rgb(55, 55, 55);
     padding: 2px 2px 2px 2px;
     font-size: small;
 }
 .module_bonus_grade input
 {
     width: 30px;
     height: calc(100% / 5);
     display: inline-block;
     text-align: center;
 }
 .module_bonus_grade span
 {
     text-align: center;
     width: 15px;
     display: inline-block;
 }
 .module_nickname
 {
     text-align: center;
 }
 .module_nickname *
 {
     color: black;
 }
 .medal_scrollbar
 {
     height: 20px;
     width: 100%;
     background-color: lightgray;
     position: relative;
     border-radius: 10px;
 }
 .medal_scrollbar_cursor
 {
     user-select: none;
     height: 20px;
     width: 20%;
     position: absolute;
     top: 0px;
     left: 0px;
     background-color: rgb(200, 143, 26);
     border-radius: 10px;
 }
 .medal_scroll
 {
     height: 100%;
     width: 100%;
     overflow-x: hidden;
 }
</style>
<script>
 function load_medal_panel(form, div)
 {
     silent_submitf(form, {tofill: div});
 }
 
 function switch_medal(formid)
 {
     let form = document.getElementById(formid + "form");
     let stat = document.getElementById(formid + "status");
     let div = document.getElementById(formid);
  
     stat.value = stat.value == 1 ? 0 : 1;
     silent_submitf(form, {});
     if (stat.value == 0)
	 div.style.opacity = 0.30;
     else
	 div.style.opacity = 1.00;
 }
  

 function subscribe_to_matter(panel)
 {
     //
     document.getElementById("resume_" + panel).style.display = "none";
 }
 <?php if (isset($_GET["b"]) && $_GET["b"] == 1) { ?> 
 localStorage.setItem("admin_module", 1);
 <?php } ?>

 var last_click;
 
 function hscroll(id, start = false)
 {
     if (start)
     {
	 last_click = CurrentMousePosition;
	 CurrentLeftClickStatus = true;
     }
     if (CurrentLeftClickStatus == false)
	 return ;
     var bar = document.getElementById("medal_scrollbar" + id);
     var cur = document.getElementById("medal_scrollbar_cursor" + id);
     var space = document.getElementById("medal_scroll" + id);
     var table = document.getElementById("medal_scroll_table" + id);
     var left = cur.offsetLeft;

     left -= last_click.x - CurrentMousePosition.x;
     last_click.x = CurrentMousePosition.x;
     
     if (left < 0)
	 left = 0;
     if (left + cur.offsetWidth >= bar.offsetWidth)
	 left = bar.offsetWidth - cur.offsetWidth;

     cur.style.left = left + "px";

     left = left / (bar.offsetWidth - cur.offsetWidth);
     space.scrollLeft = (table.offsetWidth - space.offsetWidth) * left;
     setTimeout(hscroll, 20, id);
 }
 
 function adapt_scroll_size(id)
 {
     var bar = document.getElementById("medal_scrollbar" + id);
     var cur = document.getElementById("medal_scrollbar_cursor" + id);
     var space = document.getElementById("medal_scroll" + id);
     var table = document.getElementById("medal_scroll_table" + id);
     if (!bar || !cur || !space || !table)
     {
	 setTimeout(adapt_scroll_size, 300, id);
	 return ;
     }
     var val = space.offsetWidth / table.offsetWidth;

     if (val > 1.0)
	 val = 1;
     if (val < 0)
	 val = 0.01;
     cur.style.width = val * bar.offsetWidth;
     // Parceque l'adaptation n'a pas lieu si c'est pas fait...
     setTimeout(adapt_scroll_size, 300, id);
 }
 
</script>
<?php
function sort_by_codename($a, $b)
{
    return (strcmp($a->codename, $b->codename));
}
?>
<?php $DBCache = true; ?>
<?php $requested_listed = false; ?>
<?php if (isset($_GET["a"])) { ?>
    <?php require_once ("load_requested_activity.php"); ?>
<?php } ?>
<?php require_once ("load_my_activities.php"); ?>
<?php require_once ("load_managed_activities.php"); ?>

<table class="submenu"><tr class="submenutr"><td class="submenutd">
    <div class="module_menubar">
	<?php
	require_once ("matter_menu.phtml");
	if (isset($mdatas) && count($mdatas))
	    require_once ("managed_menu.phtml");
	?>
    </div>
</td><td class="submenutd">
    <?php $is_admin_module = false; ?>
    <?php foreach ($datas as $data) { ?>
	<?php foreach ($data["matter_to_sort"] as $matter) { ?>
	    <div
		class="module_panel"
		id="module_<?=$matter->id; ?>"
		style="display: none;"		
	    >
	        <?php require ("module.phtml"); ?>
	    </div>
	<?php } ?>
    <?php } ?>
    <?php $is_admin_module = true; ?>
    <?php foreach ($mdatas as $matters) { ?>
	<?php foreach ($matters as $matter) { ?>
	    <div
		class="module_panel"
		id="module_<?=$matter->id; ?>"
		style="display: none;"		
	    >
		<?php require ("module.phtml"); ?>
	    </div>
	    <div
		class="module_panel module_admin_panel"
		id="module_<?=$matter->id; ?>_admin"
		style="display: none; margin-left: 20px; margin-right: 20px;"
	    >
		<?php require ("module_admin.php"); ?>
	    </div>
	<?php } ?>
    <?php } ?>
    <?php if (isset($requested->id) && $requested_listed == false) { ?>
	<?php $is_admin_module = $requested->is_teacher; ?>
	    <div
		class="module_panel"
		id="module_<?=$requested->id; ?>"
		style="display: none;"		
	    >
		<?php $matter = $requested; ?>
		<?php require ("module.phtml"); ?>
	    </div>
	    <?php if ($is_admin_module) { ?>
		<div
		    class="module_panel module_admin_panel"
		    id="module_<?=$requested->id; ?>_admin"
		    style="display: none"
		>
		    <?php require ("module_admin.php"); ?>
		</div>
	    <?php } ?>
    <?php } ?>

    <div
	class="module_panel"
	id="resume"
	style="display: none;"		
    >
        <?php require_once ("resume.php"); ?>
    </div>
</td></tr></table>

<script>
 <?php if (isset($_GET["a"])) { ?>
 display_panel("module", <?=$_GET["a"]; ?>);
 <?php } else { ?>
 var ls = localStorage.getItem('module<?=$User["id"]; ?>');
 if (ls == null)
     display_panel("module", -1);
 else
     display_panel("module", ls);
 <?php } ?>
</script>
