<?php foreach ($mdatas as $year => $matters) { ?>
    
    <h3 style="
	       border-top: 1px solid gray;
	       padding-top: 5px;
	       position: relative;"
    >
	<?php $dd = explode("/", $year); ?>
	<?=$Dictionnary["ManagedActivities"]; ?> <?=$dd[1]."/".$dd[0]; ?>
	<br />
	<span style="font-size: small"></span>
	<input
	    id="menu_managed<?=$year; ?>_button"
	    type="button"
	    onclick="roll_unroll('menu_managed<?=$year; ?>');"
	    class="rollbutton"
	    value="+"
	/>
	<script>
	 var tmp = localStorage.getItem('menu_managed<?=$year; ?>');
	 document.getElementById('menu_managed<?=$year; ?>_button').value
	 = (tmp != null) ? tmp : '+'
	 ;
	</script>
    </h3>
    
    <ul id="menu_managed<?=$year; ?>">
	<br />
	<?php
	$sorted_matters = $matters;
	usort($sorted_matters, "sort_by_codename");
	?>
	<?php foreach ($sorted_matters as $matter) { ?>
	    <li>
		<a onclick="display_panel('module', <?=$matter->id; ?>);" style="cursor: pointer;">
		    <div class="module_link" id="module_link<?=$matter->id; ?>">
			<h4 style="width: 70%;">
			    <?=$matter->fr_name ?: "<span style=\"color: lightgray;\">".$Dictionnary["ActivityWithNoName"]."</span>"; ?>
			</h4>
			<h4 class="flammes" style="font-weight: bold; color: white; font-size: xx-small; color: lightgray;">
			    (<?=$matter->codename; ?>)
			</h4>
		    </div>
		</a>
	    </li>
	<?php } ?>
	<br />
    </ul>
    <script>
     roll_unroll('menu_managed<?=$year; ?>');
    </script>

<?php } ?>
