<h2><?=$Dictionnary["Matter"]; ?></h2>
<a onclick="display_matter(-1);">
    <?=$Dictionnary["AllMatters"]; ?>
</a>
<br />
<?php foreach ($datas as $data) { ?>

    <?php $cycle = $data["cycle"]; ?>
    <?php $matter_to_sort = $data["matter_to_sort"]; ?>
    
    <h3 style="border-top: 1px solid gray; padding-top: 5px;">
	<?=$Dictionnary["Cycle"]; ?>
	<?=strlen(@$cycle->name) ? $cycle->name : $cycle->codename; ?>
	<br />
	<span style="font-size: small;">
	    (<?=$Dictionnary["Year"]; ?> <?=ceil(($cycle->cycle + 1) / 4); ?>,
	    <?=$Dictionnary["Trimester"]; ?> <?=(int)$cycle->cycle % 4 + 1; ?>,
	    <?=$data["min_cred"]."-".$data["max_cred"]." ".$Dictionnary["Credit(s)"]; ?>)
	</span>
	<br /><br />
    </h3>
    
    <ul>
	<?php foreach ($matter_to_sort as $matter) { ?>
	    <li>
		<?php if (cursus_match($matter->cycle, $matter->cursus, $User["cycle"])) { ?>
		    <img
			src="res/mandatory.png"
			style="float: left; width: 20px; height: 20px;
			     position: relative; left: -5px;"
			title="<?=$Dictionnary["Mandatory"]; ?>"
		    />
		<?php } ?>
		
		<a onclick="display_matter(<?=$matter->id; ?>);" style="cursor: pointer;">
		    <div style="z-index: 0; padding-left: 20px; position: relative;" id="module_link<?=$matter->id; ?>" class="module_link">
			<h4 style="width: 70%; <?=$matter->registered ? "font-weight: bold; color: white;" : "font-weight: lighter; color: lightgrey;"; ?>">
			    <?=$matter->name ?:
			       $matter->template_codename ?:
			       $matter->codename
			    ; ?>
			</h4>
			<h4 class="flammes" style="<?=$matter->registered ? "font-weight: bold; color: white;" : "font-weight: lighter; color: darkgrey;"; ?>">
			    (<?=$matter->credit_d."-".$matter->credit_a; ?>
			    <?=$Dictionnary["Credit(s)"]; ?>)
			</h4>
			<?php
			// $valid_activities[$matter->id] = $matter->registered ? 1 : 0;
			?>
		    </div>
		</a></li>
	<?php } ?>
    </ul>
    <br />
<?php } ?>
