<?php
function sort_by_name($a, $b)
{
    if (strlen($a->name))
	$aa = $a->name;
    else if (strlen($a->template_codename))
	$aa = $a->template_codename;
    else
	$aa = $a->codename;
    if (strlen($b->name))
	$bb = $b->name;
    else if (strlen($b->template_codename))
	$bb = $b->template_codename;
    else
	$bb = $b->codename;
    return (strcmp($aa, $bb));
}

if (!count($user->merged_sublayers))
    return ;
uksort($user->merged_sublayers, "sort_year_month_reverse");
?>
<h2><?=$Dictionnary["Matter"]; ?></h2>
<a href="index.php?p=ModulesMenu">
    <?=$Dictionnary["AllMatters"]; ?>
</a>
<br />

<?php foreach ($user->merged_sublayers as $cycle) { ?>

    <?php
    $or = [];
    foreach ($cycle->cycles as $cyc)
	$or[] = " activity_cycle.id_cycle = $cyc ";
    $or = " ( ".implode(" OR ", $or)." ) ";
    $matters = db_select_all("
          activity.id, activity_cycle.cursus as cursus
          FROM activity_cycle
          LEFT JOIN activity ON activity_cycle.id_activity = activity.id
          WHERE $or
          AND (activity.parent_activity IS NULL OR activity.parent_activity = -1)
          AND activity.deleted IS NULL
    ");
    if (count($matters) == 0)
	echo $Dictionnary["Empty"];
    $matter_to_sort = [];
    $min_cred = 0;
    $max_cred = 0;
    foreach ($matters as $matid)
    {
	($matter = new FullActivity)->build($matid["id"]);
	if ($matter->hidden)
	    continue ;
	$matter->cycle = $cyc;
	$matter->cursus = explode(";", $matid["cursus"]);
	$min_cred += $matter->credit_d;
	$max_cred += $matter->credit_a;
	$matter_to_sort[] = $matter;
    }
    uasort($matter_to_sort, "sort_by_name");
    ?>
    
    <h3 style="border-top: 1px solid gray; padding-top: 5px;">
	<?=$Dictionnary["Cycle"]; ?> <?=strlen(@$cycle->name) ? $cycle->name : $cycle->codename; ?><br />
	<span style="font-size: small;">
	    (<?=$Dictionnary["Year"]; ?> <?=ceil(($cycle->cycle + 1) / 4); ?>,
	    <?=$Dictionnary["Trimester"]; ?> <?=(int)$cycle->cycle % 4 + 1; ?>,
	    <?="$min_cred-$max_cred ".$Dictionnary["Credit(s)"]; ?>)
	</span>
	<br /><br />
    </h3>
    <ul>
	<?php foreach ($matter_to_sort as $matter) { ?>

	    <li>
		<?php if (cursus_match($matter->cycle, $matter->cursus, $User["cycle"])) { ?>
		    <img src="res/mandatory.png" style="float: left; width: 20px; height: 20px; position: relative; left: -5px;" title="<?=$Dictionnary["Mandatory"]; ?>" />
		<?php } ?>
		<a href="<?=unrollurl(["a" => $matter->id]); ?>">
		<h4 style="z-index: 0; padding-left: 20px; position: relative; <?=$matter->registered ? "font-weight!: bold; color: white;" : "font-weight: lighter; color: darkgrey;"; ?>">
		    <?=$matter->name ?:
		       $matter->template_codename ?:
		       $matter->codename
		    ; ?>
		    <span class="flammes">
			(<?=$matter->credit_d."-".$matter->credit_a; ?>
			<?=$Dictionnary["Credit(s)"]; ?>)
		    </span>
		    <?php
		    $valid_activities[$matter->id] = $matter->registered ? 1 : 0;
		    ?>
		</h4>
	    </a></li>
	<?php } ?>
    </ul>
    <br />
<?php } ?>
