<div class="module_menu tinyscroll" style="overflow: auto; direction: rtl;">
    <div style="direction: ltr; padding-left: 3%; padding-top: 10px;">
	<h2><?=$Dictionnary["Modules"]; ?></h2>
	<a href="index.php?p=<?=$Position; ?>">
	    <?=$Dictionnary["SeeAvailableModules"]; ?>
	</a>
	<br />
	<br />
	<?php
	foreach ($profile->sublayer as &$cycle)
	{
	?>
	<h3><?=$cycle->codename; ?></h3>
	<?php
	foreach ($cycle->sublayer as &$module)
	{
	if ($module->registered == false && 0) //////////////////////////////////////
	continue ;
        ?>
	<?php
	if ($module->id == $current_module)
	{
	$color = "color: red";
	}
	else
	$color = "";
	?>
	<a href="index.php?p=<?=$Position; ?>&amp;a=<?=$module->id; ?>" style="<?=$color; ?>">
	    <?=$module->name; ?>
	</a><br />
        <?php
	}
	?><br /><?php
	}
	?>
	<br />
	<h2><?=$Dictionnary["TeachedModules"]; ?></h2>
	<br />
	MODELE TEST
	<br />
    </div>
</div>
