<?php
$cycles = db_select_all("
    cycle.*, cycle.id as id_cycle, {$Language}_name as name FROM cycle
    LEFT JOIN user_cycle ON cycle.id = user_cycle.id_cycle
    WHERE user_cycle.id_user = {$User["id"]}
    AND cycle.is_template = 0
    ORDER BY cycle.cycle DESC
    ");

// On rassemble les cycles communs. (Par exemple, l'EF4+l'EF4 Spécialité)
$cycles = merge_cycles($cycles);

if (count($cycles)) { ?>
    <h2><?=$Dictionnary["Matter"]; ?></h2>
    <br />
    <?php foreach ($cycles as $cycle) { ?>
	<h3 style="border-top: 1px solid gray; padding-top: 5px;">
	    <?=$Dictionnary["Cycle"]; ?> <?=$cycle["name"] ?: $cycle["codename"]; ?><br />
	    <span style="font-size: small;">
		(<?=$Dictionnary["Year"]; ?> <?=ceil(($cycle["cycle"] + 1) / 4); ?>,
		<?=$Dictionnary["Trimester"]; ?> <?=(int)$cycle["cycle"] % 4 + 1; ?>)
	    </span>
	    <br /><br />
	</h3>
	<ul>
	    <?php
	    if (count($cycle["matters"]) == 0)
		echo $Dictionnary["Empty"];
	    foreach ($cycle["matters"] as $mat) { ?>
		<?php ($matter = new FullActivity)->build($mat["id"], false, false); ?>
		<?php if ($matter->hidden) continue ; ?>
		<li><a href="<?=unrollurl(["a" => $matter->id]); ?>">
		    <h4 style="position: relative;">
			<?=$matter->registered ? "<b>" : ""; ?>
			<?=$matter->fr_name ?:
			   $matter->template_codename ?:
			   $matter->codename
			; ?>
			<?=$matter->registered ? "</b>" : ""; ?>
			<span class="flammes">
			    (<?=$matter->credit_d."-".$matter->credit_a; ?>
			    <?=$Dictionnary["Credit(s)"]; ?>)
			</span>
			<?php
			$valid_activities[$matter->id] = $matter->registered ? 1 : 0;
			?>
		    </h4>
		</a></li>
	    <?php } ?>
	</ul>
	<br />
    <?php } ?>
<?php } ?>

<?php
$matters = db_select_all("
  activity.id
  FROM activity
  LEFT JOIN activity_teacher ON activity_teacher.id_activity = activity.id
  LEFT JOIN laboratory ON activity_teacher.id_laboratory = laboratory.id
  LEFT JOIN user_laboratory ON laboratory.id = user_laboratory.id_laboratory
    AND user_laboratory.authority > 0

  LEFT JOIN activity_cycle ON activity_cycle.id_activity = activity.id
  LEFT JOIN cycle_teacher ON cycle_teacher.id_cycle = activity_cycle.id_cycle
  LEFT JOIN laboratory as lab ON cycle_teacher.id_laboratory = lab.id
  LEFT JOIN user_laboratory as userlab ON lab.id = userlab.id_laboratory
    AND userlab.authority > 0

  LEFT JOIN school_cycle ON school_cycle.id_cycle = activity_cycle.id_cycle
  LEFT JOIN user_school ON school_cycle.id_school = user_school.id_school
    AND user_school.authority = 1

  WHERE (activity_teacher.id_user = {$User["id"]}
    OR user_laboratory.id_user = {$User["id"]}
    OR cycle_teacher.id_user = {$User["id"]}
    OR userlab.id_user = {$User["id"]}
    OR (user_school.id_user = {$User["id"]} AND user_school.authority = 1)
    OR ".(is_admin() ? "1" : "0")."
  )
  AND activity.parent_activity = -1
  AND activity.is_template = 0
  GROUP BY activity.id
  ORDER BY activity.codename
  ");
if (count($matters)) { ?>
    <h2><?=$Dictionnary["ManagedActivities"]; ?></h2>
    <ul>
	<?php foreach ($matters as $mat) { ?>
	    <?php ($matter = new FullActivity)->build($mat["id"], false, false); ?>
	    <li><a href="<?=unrollurl(["a" => $matter->id]); ?>">
		<h4>
		    <?=$matter->codename; ?>: <?=$matter->fr_name; ?>
		</h4>
		<?php $valid_activities[$matter->id] = 2; ?>
	    </a></li>
	<?php } ?>
    </ul>
<?php } ?>
