<?php ($matter = new FullActivity)->build($module); ?>

<?php $nbline = 0; ?>
<table class="module_tab">
    <tr><td colspan="3" style="position: relative;">
	<h2><?=$matter->name ?: $matter->codename; ?></h2>
	<?php if (is_teacher_for_activity($matter->id)) { ?>
	    <a href="<?=unrollurl(["b" => 1]); ?>" style="position: absolute; width: 20%; left: calc((100% - 20%) / 2); top: 10px; text-align: center; z-index: 1;">
		<?=$Dictionnary["ManageModule"]; ?>
	    </a>
	    <?php
	    $link = [
		"p" => "InstancesMenu",
		"a" => $matter->id
	    ];
	    ?>
	    <a href="<?=unrollurl($link); ?>" style="position: absolute; right: 40px; top: 10px; z-index: 1;">
		<?=$Dictionnary["SeeInstanceConfiguration"]; ?>
	    </a>
	<?php } ?>
	<hr style="border-color: lightgray;" />
    </td></tr>
    <tr><td style="padding-top: 0px;">
    <?php if ($matter->emergence_date != NULL) { ?>
	<b><?=$Dictionnary["EmergenceDate"]; ?></b>:
	<?=litteral_date($matter->emergence_date); ?>
	<?php $nbline += 1; ?>
	<br />
    <?php } ?>
    <?php if ($matter->registration_date != NULL) { ?>
	<b><?=$Dictionnary["RegistrationOpenDate"]; ?></b>:
	<?=litteral_date($matter->registration_date); ?>
	<?php $nbline += 1; ?>
	<br />
    <?php } ?>
    <?php if ($matter->close_date != NULL) { ?>
	<b><?=$Dictionnary["RegistrationCloseDate"]; ?></b>:
	<?=litteral_date($matter->close_date); ?>
	<?php $nbline += 1; ?>
	<br />
    <?php } ?>
    <?php if ($matter->done_date != NULL) { ?>
	<b><?=$Dictionnary["DoneDate"]; ?></b>:
	<?=litteral_date($matter->done_date); ?>
	<?php $nbline += 1; ?>
	<br />
    <?php } ?>
    
    <?php if ($matter->maximum_subscription != -1) { ?>
	<?php $nbline += 1; ?>
	<?=$Dictionnary["MaximumSubscription"].": ".$matter->maximum_subscription; ?>
    <?php } ?>
</td><td style="padding: 0;">
    <?php require_once ("grade_array.phtml"); ?>
</td><td style="padding-top: 0px; text-align: center;">

    <?php if ($matter->subscription != FullActivity::AUTOMATIC_SUBSCRIPTION) { ?>

	<?php if (!period($matter->registration_date, $matter->close_date)) { ?>
	    <b><?=$Dictionnary["SubscriptionPeriodIsClose"]; ?></b>
	<?php } else { ?>
	    <?php $js = "silent_submit(this); setTimeout(function() { location.reload(); }, 500);"; ?>
	    <form method="put" action="/api/module/<?=$module; ?>/registration">
		<?php if ($matter->registered) { ?>
		    
		    <?php if ($matter->allow_unregistration == false) { ?>
			<input type="button" value="<?=$Dictionnary["Subscribed"]; ?>" style="width: 100%; height: 70px; border-radius: 10px; font-size: large; border: 0;" />
		    <?php } else { ?>
			<input type="button" onclick="<?=$js; ?>" value="<?=$Dictionnary["Unsubscribe"]; ?>" style="width: 100%; height: 70px; border-radius: 10px; font-size: large; border: 0;" />
		    <?php } ?>
		    
		<?php } else if ($matter->registered == false) { ?>
		    <input
			type="button"
			onclick="<?=$js; ?>"
			value="<?=$Dictionnary["Subscribe"]; ?>"
			style="width: 100%; height: 70px; border-radius: 10px; font-size: large; border: 0;"
		    /><br /><br />
		    <?php if ($matter->allow_unregistration == false) { ?>
			<b style="color: white;"><?=$Dictionnary["UnsubscribeIsForbidden"]; ?>.</b><br />
		    <?php } ?>
		<?php } ?>
	    </form>
	<?php } ?>
	
    <?php } ?>

</td></tr><tr><td colspan="3">
    <?=$matter->description; ?>
</td></tr><tr><td colspan="3" class="medalscroll">
    <div>
	<?php if (!count($matter->medal)) { ?>
	    <span style="position: relative; top: 10px; left: 10px; font-style: italic; color: gray;">
		<?=$Dictionnary["NoAssociatedMedalToMatter"]; ?>
	    </span>
	<?php } ?>
	<?php foreach ($matter->medal as $medal) { ?>
	    <div
		class="medal_box_picture"
		style="
		       display: inline-block; margin-left: 5px; margin-right: 5px;
		       background-image: url('<?=$medal["icon"]; ?>');
		       <?php if ($medal["band"] != NULL) { ?>
		       border-radius: 50px;
		       border: 4px black solid;
		       width: 92px !important; height: 92px !important;
		       <?php } ?>
		       "
	    ></div>
	<?php } ?>
    </div>
</td></tr></table>
	
<?php foreach ($matter->subactivities as $act) { ?>
    <?php require ("module_tab.php"); ?>
<?php } ?>
