<div class="module_block" style="position: relative;">
    <h2 style="font-size: large; height: 15%;"><?=$module->name; ?></h2>
    <p style="font-size: small; height: 50%">
	<?=$module->description; ?>
    </p>
    <table style="width: 100%; height: 20%;">
	<tr>
	    <td>
		<b><?=$Dictionnary["Credits"]; ?></b>: <?=$module->credit; ?><br />
		<b><?=$Dictionnary["Cycle"]; ?></b>: <?=$cycle->codename; ?><br />
		<b><?=$Dictionnary["Subscribed"]; ?></b>: <?=$module->registered ? $Dictionnary["Yes"] : $Dictionnary["No"]; ?><br />
		<?php if ($module->allow_unregistration == 0) { ?>
		     <b><?=$Dictionnary["UnsubscribeIsForbidden"]; ?></b>
		<?php } ?>
	    </td>
	    <td>
		<?php
		if ($module->emergence_date)
		    echo "<b>".$Dictionnary["EmergenceDate"]."</b>:".human_date($module->emergence_date);
		if ($module->done_date)
		    echo "<b>".$Dictionnary["DoneDate"]."</b>:".human_date($module->done_date);
		if ($module->registration_date)
		    echo "<b>".$Dictionnary["RegistrationDate"]."</b>:".human_date($module->registration_date);
		if ($module->close_date)
		    echo "<b>".$Dictionnary["CloseDate"]."</b>:".human_date($module->close_date);
		?>
	    </td>
	    <td>
		<form method="post" action="index.php?<?=unrollget(); ?>" style="height: 100%;">
		    <?php if ($module->registered == false) { ?>
		    <input type="hidden" name="action" value="subscribe" />
		    <input type="hidden" name="module" value="<?=$module->id; ?>" />
		    <input type="submit" value="<?=$Dictionnary["Subscribe"]; ?>" style="width: 100%; height: 100%;" />
		    <?php } else { ?>
		    <input type="hidden" name="action" value="unsubscribe" />
		    <input type="hidden" name="module" value="<?=$module->id; ?>" />
		    <input type="submit" value="<?=$Dictionnary["Unsubscribe"]; ?>" style="width: 100%; height: 100%;" />
		    <?php } ?>
	    </td>
	</tr>
    </table>
</div>
