<?php $nbline = 0; ?>
<table
    <?php if (strlen(@$matter->full_activity->current_wallpaper)) { ?>
	class="module_tab outline"
	style="background-image: url('<?=$matter->full_activity->current_wallpaper; ?>'); background-size: cover;"
    <?php } else { ?>
        class="module_tab"
    <?php } ?>
>
    <tr><td colspan="6" style="position: relative;">
	<h2><?=$matter->name ?: $matter->codename; ?></h2>
	<h5 style="position: absolute; top: 15px; right: 15px;">
	    <?=$matter->name ? $matter->codename." #".$matter->id : "#".$matter->id; ?>
	</h5>
	<hr style="border-color: lightgray;" />
    </td></tr>
    <tr>
	<td colspan="2" style="text-indent: 40px; text-align: justify;" class="outlinee">
	    <p>
		<?=markdown($matter->description, true); ?>
	    </p>
	</td><td colspan="2" class="outlinee">
	    <p>
		<?php
		$date_source = $matter->full_activity;
		require ("list_of_dates.php");
		?>
	    </p>
	</td><td style="padding: 0;" style="width: 400px;">
	    <?php require ("grade_array.phtml"); ?>
	</td><td style="padding-top: 0px; text-align: center;" class="outlinee">
	    <p class="subbuttons">
		<?php
		if ($is_admin_module)
		    require ("module_admin_button.php");
		else 
		    require ("module_subscription.php");
		?>
	    </p>
	</td>
    </tr>
    <tr>
	<td colspan="6" class="medalscroll" style="min-height: 50px;">
 	    <div style="text-align: center; min-height: 50px;">
		<?php if (!count($matter->medal)) { ?>
		    <span style="position: relative; top: 10px; left: 10px; font-style: italic; color: gray;">
			<?=$Dictionnary["NoAssociatedMedalToMatter"]; ?>
		    </span>
		<?php } ?>
		<?php $matter->medal = sort_by_medal_grade($matter->medal, false); ?>
		<?php $medal_size = 92; ?>
		<?php $edit_medal = false; ?>
		<?php foreach ($matter->medal as $medal) { ?>
		    <?php if ($medal["role"] == 0) continue ; ?>
		    <?php require ("single_medal.phtml"); ?>
		<?php } ?>
	    </div>
	</td>
    </tr>
</table>

<?php foreach ($matter->sublayer as $act) { ?>
    <?php $act = $act->full_activity; ?>
    <?php require ("activity.php"); ?>
<?php } ?>
