<?php
/////// LISTE DES MODULES ACCESSIBLES
$registered = [];
$unregistered = [];
foreach ($profile->sublayer as &$cycle)
{
    if ($cycle->done || date_to_timestamp($cycle->first_day) > time())
	continue ;
    foreach ($cycle->sublayer as &$module)
    {
	if ($module->registered)
	    $registered[] = &$module;
	else
	    $unregistered[] = &$module;
    }
}
foreach ($unregistered as $module)
{
    require (__DIR__."/module_entry.phtml");
}
foreach ($registered as $module)
{
    require (__DIR__."/module_entry.phtml");
}
?>
