<?php

/*
 * Internship calendar -> standalone session synchronizer (stage 4B).
 *
 * The Dabsic calendar remains authoritative.  This layer only materializes its
 * T half-days into session rows carrying the stable provenance introduced in
 * stage 4A.  Manual sessions and sessions generated by another document are
 * never considered by the diff.
 */

require_once (__DIR__."/internship_calendar.php");
require_once (__DIR__."/internship_session_plan.php");

function internship_session_sync_source_from_output($output_key)
{
    $output_key = trim((string)$output_key);
    if (!preg_match('/^user-document:([0-9]+):[a-f0-9]{32}:[0-5]$/D', $output_key, $m))
        return (NULL);
    if (strlen($output_key) > 96)
        return (NULL);
    return ([
        "id_user" => (int)$m[1],
        "source_type" => "document",
        "source_id" => $output_key,
    ]);
}

function internship_session_sync_existing($source_type, $source_id)
{
    global $Database;

    $source_type = $Database->real_escape_string((string)$source_type);
    $source_id = $Database->real_escape_string((string)$source_id);
    $rows = db_select_all("
        id, deleted,
        id_activity, id_laboratory, id_team, id_user,
        name, source_type, source_id, source_key,
        begin_date, end_date, maximum_subscription
        FROM session
        WHERE source_type = '$source_type'
          AND source_id = '$source_id'
        ORDER BY id ASC
    ");
    $out = [];
    foreach ($rows as $row)
    {
        $key = trim((string)($row["source_key"] ?? ""));
        if ($key === "")
            continue ;
        $out[$key] = $row;
    }
    return ($out);
}

function internship_session_sync_row_differs(array $existing, array $desired)
{
    foreach (["id_activity", "id_laboratory", "id_team", "id_user"] as $field)
        if ((int)($existing[$field] ?? 0) !== (int)($desired[$field] ?? 0))
            return (true);
    foreach (["name", "source_type", "source_id", "source_key", "begin_date", "end_date"] as $field)
        if ((string)($existing[$field] ?? "") !== (string)($desired[$field] ?? ""))
            return (true);
    if (($existing["maximum_subscription"] ?? NULL) !== NULL)
        return (true);
    if (($existing["deleted"] ?? NULL) !== NULL && trim((string)$existing["deleted"]) !== "")
        return (true);
    return (false);
}

function internship_session_sync_diff(array $desired, array $existing)
{
    $diff = [
        "create" => [],
        "update" => [],
        "delete" => [],
        "unchanged" => [],
    ];

    foreach ($desired as $key => $session)
    {
        if (!isset($existing[$key]))
            $diff["create"][$key] = $session;
        else if (internship_session_sync_row_differs($existing[$key], $session))
            $diff["update"][$key] = ["existing" => $existing[$key], "desired" => $session];
        else
            $diff["unchanged"][$key] = $existing[$key];
    }

    foreach ($existing as $key => $session)
        if (!isset($desired[$key]) &&
            (($session["deleted"] ?? NULL) === NULL || trim((string)$session["deleted"]) === ""))
            $diff["delete"][$key] = $session;

    return ($diff);
}

function internship_session_sync_sql_string($value)
{
    global $Database;
    return ("'".$Database->real_escape_string((string)$value)."'");
}

function internship_session_sync_insert(array $session)
{
    global $Database;

    $name = internship_session_sync_sql_string($session["name"] ?? "Stage en entreprise");
    $source_type = internship_session_sync_sql_string($session["source_type"] ?? "document");
    $source_id = internship_session_sync_sql_string($session["source_id"] ?? "");
    $source_key = internship_session_sync_sql_string($session["source_key"] ?? "");
    $begin = internship_session_sync_sql_string($session["begin_date"] ?? "");
    $end = internship_session_sync_sql_string($session["end_date"] ?? "");

    return ($Database->query("
        INSERT INTO session
            (id_activity, id_laboratory, id_team, id_user, name,
             source_type, source_id, source_key,
             begin_date, end_date, maximum_subscription, deleted)
        VALUES
            (-1, -1, -1, ".(int)$session["id_user"].", $name,
             $source_type, $source_id, $source_key,
             $begin, $end, NULL, NULL)
    ") !== NULL);
}

function internship_session_sync_update(array $entry)
{
    global $Database;

    $existing = $entry["existing"];
    $session = $entry["desired"];
    $id = (int)($existing["id"] ?? 0);
    if ($id <= 0)
        return (false);

    $name = internship_session_sync_sql_string($session["name"] ?? "Stage en entreprise");
    $source_type = internship_session_sync_sql_string($session["source_type"] ?? "document");
    $source_id = internship_session_sync_sql_string($session["source_id"] ?? "");
    $source_key = internship_session_sync_sql_string($session["source_key"] ?? "");
    $begin = internship_session_sync_sql_string($session["begin_date"] ?? "");
    $end = internship_session_sync_sql_string($session["end_date"] ?? "");

    return ($Database->query("
        UPDATE session
        SET id_activity = -1,
            id_laboratory = -1,
            id_team = -1,
            id_user = ".(int)$session["id_user"].",
            name = $name,
            source_type = $source_type,
            source_id = $source_id,
            source_key = $source_key,
            begin_date = $begin,
            end_date = $end,
            maximum_subscription = NULL,
            deleted = NULL
        WHERE id = $id
          AND source_type = ".internship_session_sync_sql_string($existing["source_type"] ?? "")."
          AND source_id = ".internship_session_sync_sql_string($existing["source_id"] ?? "")."
          AND source_key = ".internship_session_sync_sql_string($existing["source_key"] ?? "")."
    ") !== NULL);
}

function internship_session_sync_delete(array $session)
{
    global $Database;

    $id = (int)($session["id"] ?? 0);
    if ($id <= 0)
        return (false);
    return ($Database->query("
        UPDATE session
        SET deleted = NOW()
        WHERE id = $id
          AND deleted IS NULL
          AND source_type = ".internship_session_sync_sql_string($session["source_type"] ?? "")."
          AND source_id = ".internship_session_sync_sql_string($session["source_id"] ?? "")."
          AND source_key = ".internship_session_sync_sql_string($session["source_key"] ?? "")."
    ") !== NULL);
}

function internship_session_sync_plan_for_output($output_key, $file)
{
    $source = internship_session_sync_source_from_output($output_key);
    if ($source === NULL)
        return (["ok" => true, "applicable" => false]);
    if (!is_string($file) || !is_file($file) || !is_readable($file))
        return (["ok" => false, "error" => "MissingFile", "details" => (string)$file]);

    $loaded = load_configuration($file, [], false);
    if ($loaded->is_error() || !is_array($loaded->value))
        return (["ok" => false, "error" => "InvalidFile", "details" => (string)$file]);

    // A normal user-document form is not necessarily an internship agreement.
    // Presence of the structured calendar is the discriminator; unrelated
    // documents are deliberately ignored instead of being treated as errors.
    if (internship_session_plan_calendar($loaded->value) === NULL)
        return (["ok" => true, "applicable" => false]);

    $plan = internship_session_plan(
        $loaded->value,
        $source["id_user"],
        $source["source_id"]
    );
    if (!$plan["ok"])
        return ($plan);
    $plan["applicable"] = true;
    return ($plan);
}

function internship_session_sync_output($output_key, $file)
{
    global $Database;

    $plan = internship_session_sync_plan_for_output($output_key, $file);
    if (!$plan["ok"] || empty($plan["applicable"]))
        return ($plan);

    $existing = internship_session_sync_existing($plan["source_type"], $plan["source_id"]);
    $diff = internship_session_sync_diff($plan["sessions"], $existing);

    if ($Database->query("START TRANSACTION") === NULL)
        return (["ok" => false, "error" => "CannotEdit", "details" => "internship session transaction"]);

    $ok = true;
    foreach ($diff["create"] as $session)
        if (!internship_session_sync_insert($session))
        {
            $ok = false;
            break ;
        }
    if ($ok)
        foreach ($diff["update"] as $entry)
            if (!internship_session_sync_update($entry))
            {
                $ok = false;
                break ;
            }
    if ($ok)
        foreach ($diff["delete"] as $session)
            if (!internship_session_sync_delete($session))
            {
                $ok = false;
                break ;
            }

    if (!$ok)
    {
        $Database->query("ROLLBACK");
        return (["ok" => false, "error" => "CannotEdit", "details" => "internship sessions"]);
    }
    if ($Database->query("COMMIT") === NULL)
    {
        $Database->query("ROLLBACK");
        return (["ok" => false, "error" => "CannotEdit", "details" => "internship session commit"]);
    }

    $counts = [
        "created" => count($diff["create"]),
        "updated" => count($diff["update"]),
        "deleted" => count($diff["delete"]),
        "unchanged" => count($diff["unchanged"]),
    ];
    if ($counts["created"] || $counts["updated"] || $counts["deleted"])
        add_log(EDITING_OPERATION,
            "Internship calendar synchronized for user #".(int)$plan["student_id"].
            " from ".$plan["source_id"].": +".$counts["created"].
            " ~".$counts["updated"]." -".$counts["deleted"],
            (int)$plan["student_id"]);

    return ([
        "ok" => true,
        "applicable" => true,
        "source_type" => $plan["source_type"],
        "source_id" => $plan["source_id"],
        "student_id" => $plan["student_id"],
        "counts" => $counts,
    ]);
}

function internship_session_validate_output($output_key, $file)
{
    $source = internship_session_sync_source_from_output($output_key);
    if ($source === NULL)
        return (["ok" => true, "applicable" => false, "errors" => [], "warnings" => []]);
    if (!is_string($file) || !is_file($file) || !is_readable($file))
        return (["ok" => false, "applicable" => true, "errors" => ["fichier Dabsic introuvable"], "warnings" => []]);

    $loaded = load_configuration($file, [], false);
    if ($loaded->is_error() || !is_array($loaded->value))
        return (["ok" => false, "applicable" => true, "errors" => ["fichier Dabsic invalide"], "warnings" => []]);
    return (internship_session_validate_configuration(
        $loaded->value,
        $source["id_user"],
        $source["source_id"]
    ));
}

function internship_session_sync_deactivate_source($source_type, $source_id, $id_user = 0, $reason = "")
{
    global $Database;

    $source_type = trim((string)$source_type);
    $source_id = trim((string)$source_id);
    if ($source_type === "" || $source_id === "")
        return (["ok" => true, "applicable" => false, "deactivated" => 0]);

    $type_sql = internship_session_sync_sql_string($source_type);
    $id_sql = internship_session_sync_sql_string($source_id);
    $active = db_select_all("id FROM session
        WHERE source_type = $type_sql
          AND source_id = $id_sql
          AND deleted IS NULL");
    if (!count($active))
        return (["ok" => true, "applicable" => true, "deactivated" => 0]);

    if ($Database->query("UPDATE session
        SET deleted = NOW()
        WHERE source_type = $type_sql
          AND source_id = $id_sql
          AND deleted IS NULL") === NULL)
        return (["ok" => false, "error" => "CannotEdit", "details" => "internship session deactivation"]);

    $count = count($active);
    $reason = trim((string)$reason);
    add_log(EDITING_OPERATION,
        "Internship sessions deactivated from $source_id".
        ($reason !== "" ? " ($reason)" : "").": -$count",
        (int)$id_user);
    return (["ok" => true, "applicable" => true, "deactivated" => $count]);
}

function internship_session_sync_deactivate_output($output_key, $reason = "")
{
    $source = internship_session_sync_source_from_output($output_key);
    if ($source === NULL)
        return (["ok" => true, "applicable" => false, "deactivated" => 0]);
    return (internship_session_sync_deactivate_source(
        $source["source_type"],
        $source["source_id"],
        $source["id_user"],
        $reason
    ));
}
